dashboard/src/components/LinkWithIcon/LinkWithIcon.tsx, dashboard/src/components/Section/Section.tsx, dashboard/src/components/Section/SectionGroup.tsx, dashboard/src/main.tsx, dashboard/src/routes/BuildDetails/BuildDetails.tsx
- Add build details section component
- Add navigation to build details
- Add mocked build details section
- Run the docker compose
- Other option is to run `pnpm run dev` in dashboard
- Go to `http://localhost/build/aaaa` or `http://localhost:5173/build/aaaa`
=> Feat: add section build details

dashboard/src/api/TreeDetails.tsx, dashboard/src/components/Filter/Drawer.tsx, dashboard/src/components/FilterList/FilterList.stories.tsx, dashboard/src/components/FilterList/FilterList.tsx, dashboard/src/components/Tabs/Tabs.tsx, dashboard/src/components/Tabs/TreeDetailsTab.tsx, dashboard/src/routes/TreeDetails/TreeDetails.tsx, dashboard/src/routes/TreeDetails/TreeDetailsFilter.tsx, dashboard/src/routes/TreeDetails/TreeDetailsFilterList.tsx
=> feat: add FilterList to TreeDetails page

backend/README.md, backend/kernelCI_app/urls.py, backend/kernelCI_app/views/TreeDetailsView.py, backend/kernelCI_app/views/TreeView.py, backend/kernelCI_app/views/__init__.py, backend/kernelCI_app/views/buildDetailsView.py, backend/requests/build-details-get.sh
Add the `/api/build/<build_id>` endpoint which will be used in TreeDetails page
- run Django dev server with:
```sh
python manage.py runserver
```
- and make a request to `/api/build/<build_id>`, such as :
```sh
curl --location 'http://localhost:8000/api/build/0dayci:build:6681e0032e96c85bf5ad3a80'
```
=> feat: add buildDetails endpoint

README.md, backend/README.md, backend/kernelCI/settings.py, backend/utils/validation.py, docker-compose.yml
This PR introduces several changes to improve the security and
deployment settings of the application. The `SECRET_KEY` is now fetched
from environment variables, and the `DEBUG` setting is set to `False` by
default, but can be overridden by an environment variable.
Additionally, several security-related settings have been added, such as
`SESSION_COOKIE_SECURE`, `CSRF_COOKIE_SECURE`, `SECURE_SSL_REDIRECT`,
and `SECURE_HSTS_SECONDS`.
The README.md file has also been updated with instructions on how to
generate a `DJANGO_SECRET_KEY` and check if the application is ready for
deployment.
=> feat(settings): enhance security and deployment settings

dashboard/src/routes/TreeDetails/TreeDetailsFilter.tsx
- drop Maintainer
- drop Estimate to complete
- rename status filter from Valid/Invalid to Sucess/Failure
we still needed to drop the hardcoded `Tree` and `Commit/tag` and get these values from kcidb, 
which will be done after #8
=> fix: drop fields from the filter summary that have no data in the kcidb

backend/kernelCI_app/urls.py, backend/kernelCI_app/views/bootsView.py, backend/requests/boots-get.sh, dashboard/.prettierrc, dashboard/package.json, dashboard/pnpm-lock.yaml, dashboard/src/api/TreeDetails.tsx, dashboard/src/components/Cards/BaseCard.tsx, dashboard/src/components/CardsGroup/CardsGroup.tsx, dashboard/src/components/ColoredCircle/ColoredCircle.tsx, dashboard/src/components/ListingContent/ListingContent.tsx, dashboard/src/components/ListingItem/ListingItem.tsx, dashboard/src/components/StatusChart/StatusCharts.tsx, dashboard/src/components/Summary/Summary.tsx, dashboard/src/components/Table/BaseTable.tsx, dashboard/src/components/Tabs/Boots/BootsTab.tsx, dashboard/src/components/Tabs/Boots/index.tsx, dashboard/src/components/Tabs/TreeDetailsTab.tsx, dashboard/src/types/database.ts, dashboard/src/types/tree/TreeDetails.tsx, dashboard/src/utils/constants/database.ts
This commit introduces a new tab in the TreeDetails page, the BootsTab.
This tab provides a detailed view of the boot tests for a specific tree.
It includes various components such as StatusChart, ConfigsList,
ErrorsSummary, LineChartCard, PlatformsWithError, and ErrorCountList.
Each component represents a specific aspect of the boot tests data.
The BootsTab data is fetched using the useBootsTab hook from the
/api/tree/{treeId}/boot endpoint. The data includes statusCounts,
errorCounts, configCounts, bootHistory, errorCountPerArchitecture,
compilersPerArchitecture, platformsWithError, and errorMessageCounts.
This commit also includes the necessary types and constants related to
the boot tests data.
Additionally, some existing components were updated to accommodate the
new features and …
=> Feat/boots UI start

dashboard/index.html
There is no space between 'Kernel' and 'CI'.
=> fix title of the dashboard to KernelCI

backend/kernelCI_app/urls.py, backend/kernelCI_app/views/testDetailsView.py, backend/requests/test-details-get.sh
- Added a new endpoint `/api/tests/<str:test_id>` to retrieve test details.
- Implemented `TestDetails` view to handle GET requests for test details.
- Created a new SQL query to fetch test details and their descendants.
- Added a test script `test-details-get.sh` to verify the new endpoint.
- Updated `urls.py` to include the new endpoint.
This change allows users to fetch detailed information about specific tests, including their build information and related metadata.
Closes #92 
Use the test-details-get script to get the request
=> feat(api): add endpoint for test details retrieval

dashboard/src/hooks/usePagination.tsx, dashboard/src/pages/TreeDetails/Tabs/Build/BuildTab.tsx
=> fix(#20): set the start index correctly when some filter is applied

dashboard/src/locales/messages/index.ts, dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx
- move strings to locale file
- add brackets that were missing in html component
=> fix: small fizes in boots tab

backend/kernelCI_app/urls.py, backend/kernelCI_app/views/testsByCommitHashView.py, backend/kernelCI_app/views/treeCommitsHistory.py, backend/kernelCI_app/views/treeTestsView.py, backend/requests/tree-commit-history.sh
New Endpoint for Tree Commits History:
Added a new API endpoint /tree/<str:commit_hash>/commits to retrieve the commit history for a specific commit hash.
It returns the history of commits along with build statistics for a given commit_hash, filtered by origin, git_url, and git_branch query parameters.
Modifications to URL Configuration:
Updated urls.py to include the new path for the Tree Commits History endpoint.
Added TODO comments to replace f-string SQL queries with parameterized queries in testsByCommitHashView.py and treeTestsView.py to prevent SQL injection and improve security.
**New Script for Testing:**
Added a new script tree-commit-history.sh under the requests directory to facilitate testing of the new endpoint. The script uses httpie to make requests to the newly added …
=> feat: tree navigation endpoints (builds page)

dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx
Remove a duplicate emoji in the BootsTab that was defined in both the localization and the page file.
| Previous | Now |
| <img width="1411"  src="https://github.com/user-attachments/assets/501fb58a-0a4d-4c35-8e7d-a564cffab49b"> | <img width="1411" src="https://github.com/user-attachments/assets/1aa8f638-d5cf-4f50-9958-aaa0f3eb016b"> |
=> fix(BootsTab): remove duplicated emoji

backend/kernelCI_app/views/treeTestsView.py, backend/requests/boots-get.sh, dashboard/src/components/ListingItem/ListingItem.tsx, dashboard/src/components/Status/Status.tsx, dashboard/src/components/Summary/Summary.tsx, dashboard/src/locales/messages/index.ts, dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/TreeDetails/Tabs/TestCards.tsx, dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/types/tree/TreeDetails.tsx
- make config cards show tests statuses on Boot and Test tabs
- rename Erros `Summary` to `Summary`
- make summary show tests statuses
Close: #199
=> fix: make config cards show tests statuses on Boot and Test tabs

dashboard/src/components/Accordion/Accordion.tsx, dashboard/src/components/Table/BootsTable.tsx, dashboard/src/components/Table/TreeTable.tsx, dashboard/src/locales/messages/index.ts, dashboard/src/pages/TreeDetails/Tabs/HeaderWithInfo.tsx
- add HeaderWithInfo component 
- add tooltip on Status header in `Build`, `Boot`, `Test` tab
Close: #233 
https://github.com/user-attachments/assets/85763faf-d926-4f0e-b4fa-cc68f96ef9ad
=> feat: show tooltip when hover on Status column

dashboard/src/components/StatusChart/StatusCharts.tsx, dashboard/src/pages/TreeDetails/Tabs/Build/BuildTab.tsx, dashboard/src/pages/TreeDetails/Tabs/TestCards.tsx
| Previous | Now |
| ![image](https://github.com/user-attachments/assets/cf429da5-a727-4831-992b-27f1b914bd8e)| ![image](https://github.com/user-attachments/assets/d48c2ffe-e64c-4efc-9996-d5a5d68bd96f) |
Close #259
=> fix: use grouped status in status chart for all tree details tab

dashboard/src/components/Table/BootsTable.tsx, dashboard/src/components/Table/TestsTable.tsx, dashboard/src/pages/TreeDetails/Tabs/Build/BuildTab.tsx, dashboard/src/types/general.ts, dashboard/src/types/tree/TreeDetails.tsx, dashboard/src/utils/status.ts
| <img width="449" alt="image" src="https://github.com/user-attachments/assets/a3ecac29-b088-4ca7-bd57-a40f5f6cdf2c"> | <img width="342" alt="image" src="https://github.com/user-attachments/assets/f8815052-3b82-4c02-8e4d-db8a18a5287e"> |
Close #253
=> fix: group the filter values of tab tables

dashboard/src/components/Status/Status.tsx, dashboard/src/components/Summary/Summary.tsx
| <img width="138" alt="image" src="https://github.com/user-attachments/assets/11932c54-3150-44a7-9a16-0a99600470c4"> | <img width="155" alt="image" src="https://github.com/user-attachments/assets/ff680986-aea7-49cc-8cf6-ff4f246cf527">|
Close #283
=> fix: Summary card status not showing in Build tab

dashboard/src/pages/TestDetails/TestDetails.tsx, dashboard/src/types/tree/TestDetails.tsx
- misc fields are json strings and must be parsed before being used as an object
| <img width="146" alt="image" src="https://github.com/user-attachments/assets/7c2c7da0-6fb5-4e77-91aa-7cf971f32c57"> | <img width="242" alt="image" src="https://github.com/user-attachments/assets/a13b0108-e45f-4e60-a41c-d7e48eaf9639"> |
Close #261
=> fix: wrong usage of misc platform field

dashboard/src/components/Accordion/Accordion.tsx, dashboard/src/components/Table/TestsTable.tsx, dashboard/src/pages/BuildDetails/BuildDetailsTestSection.tsx
=> fix: use GroupedTestStatus in every test tables

dashboard/src/api/buildTests.ts, dashboard/src/pages/BuildDetails/BuildDetailsTestSection.tsx, dashboard/src/types/general.ts
| <img width="1156" alt="image" src="https://github.com/user-attachments/assets/31c0cde0-0fa2-4076-bc2d-105f7f264d08"> | <img width="1142" alt="image" src="https://github.com/user-attachments/assets/e067f76c-f69c-4677-84d5-6d14ca64baa1"> |
Close #288 
Tested using: http://localhost:5173/tree/5f5673607153e36fc1b83583b41973a75529ab99/build/redhat:1450845118-aarch64-kernel?tableFilter=%7B%22buildsTable%22%3A%22all%22%2C%22bootsTable%22%3A%22all%22%2C%22testsTable%22%3A%22all%22%7D&origin=maestro&currentTreeDetailsTab=treeDetails.builds&diffFilter=%7B%7D&treeInfo=%7B%22gitBranch%22%3A%22for-kernelci%22%2C%22gitUrl%22%3A%22https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Farm64%2Flinux.git%22%2C%22treeName%22%3A%22arm64%22%2C%22commitName%2 …
=> fix: build details table

dashboard/src/components/Table/TreeTable.tsx
Date and time now are shown when hovering over date.
| ![image](https://github.com/user-attachments/assets/9aa674f8-553d-44bc-8994-23b96992d1a9) | ![image](https://github.com/user-attachments/assets/ac47f55c-260b-40ae-be11-1d42faf9f2e7) |
Closes #228
=> feat(dashboard): date and time on tooltip

backend/kernelCI_app/views/groupedTestsView.py, dashboard/src/components/Table/TestsTable.tsx, dashboard/src/utils/status.ts
failed tests should show fail and inconclusive should show inconclusive
http://localhost:5173/tree/5f5673607153e36fc1b83583b41973a75529ab99?tableFilter=%7B%22bootsTable%22%3A%22success%22%2C%22buildsTable%22%3A%22all%22%2C%22testsTable%22%3A%22success%22%7D&origin=maestro&currentTreeDetailsTab=treeDetails.tests&diffFilter=%7B%7D&treeInfo=%7B%22gitBranch%22%3A%22for-kernelci%22%2C%22gitUrl%22%3A%22https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Farm64%2Flinux.git%22%2C%22treeName%22%3A%22arm64%22%2C%22commitName%22%3A%22v6.11-rc7-105-g5f5673607153e%22%2C%22headCommitHash%22%3A%225f5673607153e36fc1b83583b41973a75529ab99%22%7D
=> fix(tests-table): failed tests are failed and error is inconclusive

backend/kernelCI_app/urls.py, backend/kernelCI_app/utils.py, backend/kernelCI_app/views/treeDetailsSlowView.py, backend/kernelCI_app/views/treeTestsView.py, dashboard/src/api/TreeDetails.tsx, dashboard/src/components/Accordion/Accordion.tsx, dashboard/src/components/Table/BootsTable.tsx, dashboard/src/components/Table/TestsTable.tsx, dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/TreeDetails/Tabs/TestCards.tsx, dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/types/general.ts, dashboard/src/types/tree/TreeDetails.tsx, dashboard/src/utils/filters.ts
Check if the information present on the endpoint /tree/<commit_hash>/full is sufficient for the tests and boots tabs.
http://localhost:8000/api/tree/4f8fa5a023dce383394ddfbfdd908964226b051a/full?origin=maestro&git_url=https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git&git_branch=for-next
http://localhost:8000/api/tree/3e7256c41c6572b4e5b6eb024090f8b0730d7304/full?origin=maestro&git_url=https://android.googlesource.com/kernel/common&git_branch=android-mainline
=> feat: improve tests boot query peformance

backend/kernelCI/settings.py, backend/kernelCI_app/urls.py
Added http cache to all backend paths
=> feat: add http cache

dashboard/src/components/Accordion/Accordion.tsx
Fix: The test tab was using` test.path` to navigate to TestDetails when it should have been using `test.id`
| ![image](https://github.com/user-attachments/assets/ced40915-6918-4c8b-8192-52e689b3110f) | ![image](https://github.com/user-attachments/assets/29852fe5-c3bf-4273-851c-3acb1a42546b) |
=> fix: test path was being used as test id

dashboard/src/pages/TreeDetails/Tabs/CommitNavigationGraph.tsx
Test counts on commit history graph was wrong, this fix it
Closes #307
** Disclaimer **
This PR was already approved but it was sent to the wrong branch, that is why this will be merged without approve
=> fix(commit-history-graph): fix test counts

backend/README.md, backend/kernelCI/settings.py
Added two environment variables `DEBUG` and `DEBUG_SQL_QUERY` for
debugging. The `DEBUG_SQL_QUERY` variable is separated to control
verbose SQL query logging. Updated settings to handle these variables
and configure logging accordingly.
Closes #268
=> feat(debug): add SQL query debugging option

dashboard/src/components/ColoredCircle/ColoredCircle.tsx
Improves visibility of zeroed errors.
| ![image](https://github.com/user-attachments/assets/2666a036-299b-432b-b68c-d00322af0895) | ![image](https://github.com/user-attachments/assets/373b1d8c-e900-4681-87e5-a8b9f0a12d23) |
Closes #316
=> feat(dashboard): lighter red for 0 errors

dashboard/package.json, dashboard/pnpm-lock.yaml, dashboard/src/components/Accordion/Accordion.tsx, dashboard/src/components/Table/BootsTable.tsx, dashboard/src/components/Table/TreeTable.tsx, dashboard/src/components/TooltipDateTime/TooltipDateTime.tsx, dashboard/src/components/TooltipDateTime/index.tsx, dashboard/src/pages/BuildDetails/BuildDetails.tsx, dashboard/src/pages/TreeDetails/Tabs/Build/BuildTab.tsx, dashboard/src/utils/utils.ts
Adds timezone offset to dates at main page and other places:
| ![Screenshot from 2024-09-16 11-21-15](https://github.com/user-attachments/assets/f2c1ca20-ebdd-49fa-9ea7-15369701c2ce) | ![image](https://github.com/user-attachments/assets/0c7b034e-708f-4414-b67f-092a73530c26) | 
Closes #305
=> feat(dashboard): adding tz offset to dates

dashboard/src/pages/TreeDetails/Tabs/CommitNavigationGraph.tsx, dashboard/src/utils/utils.ts
Showing date and time on tooltips.
| ![image](https://github.com/user-attachments/assets/193506fd-e5f4-4e83-9ca0-51db9bce33b4) | ![image](https://github.com/user-attachments/assets/a0908c20-4f3b-4b12-aace-6dcacc114ffd) | 
Closes #229
=> feat(dashboard): adding dateTime on graphs

README.md, backend/README.md, dashboard/README.md, docs/Onboarding.md
Added a comprehensive onboarding guide to help new contributors get
acquainted with the KernelCI Dashboard project. The guide includes
tasks for setting up the backend and frontend, understanding the
database, and completing a real task.
=> feat(docs): add onboarding guide for new contributors

backend/kernelCI_app/views/buildStatusCountView.py, backend/requests/build-status-count-get.sh, dashboard/src/types/tree/TreeDetails.tsx
- Added `log_excerpt` field to the SQL query in `BuildStatusCountView`.
- Updated the JSON response to include `log_excerpt`.
- Modified the test request script to an example with log_excerpt data
- Updated `BuildCountsResponse` type to include `log_excerpt`.
Closes #347
=> feat: include log excerpt in build status response

dashboard/.eslintrc.cjs
Added no-console rule to eslint, any console.log() or console.warn() will be shown as a problem; console.error() can still be used.
Closes #322
=> fix(#322): add no-console lint rule

backend/kernelCI_app/views/treeDetailsSlowView.py, dashboard/src/components/Table/TestsTable.tsx, dashboard/src/types/database.ts, dashboard/src/types/tree/TreeDetails.tsx, dashboard/src/utils/constants/database.ts
Make tests display the correct items in the Details View
The test status table were displaying the wrong status
and some unknown weird behavior was reported due to the failing between
joins in the table
- Changed SQL query joins from LEFT JOIN to INNER JOIN for builds and tests
- Updated status handling in TestsTable component to use StatusTable constants
- Removed unused ErrorStatus type and related code
- Adjusted imports to use absolute paths
Closes #366
Database: `kcidb`
Go to the broken link in the staging and try to open some tests with the inconclusive and fail filter
https://staging.dashboard.kernelci.org:9000/tree/7aa21fec187b7bc2a55be4daad4585098e2f47df?tableFilter=%7B%22bootsTable%22%3A%22all%22%2C%22buildsTable%22%3A%22all%22%2C%22testsTable%22%3A%22failed%22%7D&origin=maestro& …
=> fix: tests displaying incorrect items

dashboard/src/components/Filter/CodeBlock.tsx, dashboard/src/locales/messages/index.ts
At any codeblock, used to show log excerpts, any _line_ containing fails or errors will be highlighted. Fail and error lines are counted separately, as well as other lines that contain fail or error information messages.
Closes #350 
Enter at a tree page, go to Tests tab, open a test details page. If it contains a log excerpt, any lines containing fails or errors will be highlighted with a different text color, the highlight count will only be shown if the log excerpt contains anything to be highlighted.
localhost example: http://localhost:5173/tree/58e2d28ed28e5bc8836f8c14df1f94c27c1f9e2f/test/maestro:6706466d7ef7358befbc7014?tableFilter=%7B%22buildsTable%22%3A%22all%22%2C%22bootsTable%22%3A%22all%22%2C%22testsTable%22%3A%22all%22%7D&origin=maestro&currentTreeDetailsTab=treeDetails.tests& …
=> feat(#350): Highlight errors and show error count in log excerpt

dashboard/src/pages/TreeDetails/TreeDetailsFilterList.tsx
Correct the filtering by clearing the option with more than two colons by pressing the “X” next to the name.
- Closes #376 
1. open the [dashboard](http://localhost:5173/tree/1d227fcc72223cbdd34d0ce13541cbaab5e0d72f?tableFilter={%22buildsTable%22%3A%22all%22%2C%22bootsTable%22%3A%22all%22%2C%22testsTable%22%3A%22all%22}&origin=maestro&currentTreeDetailsTab=treeDetails.builds&diffFilter={%22configs%22%3A{%22cros%3A%2F%2Fchromeos-6.6%2Fx86_64%2Fchromeos-intel-pineview.flavour.config%22%3Atrue%2C%22cros%3A%2F%2Fchromeos-6.6%2Fx86_64%2Fchromeos-amd-stoneyridge.flavour.config%22%3Atrue%2C%22x86_64_defconfig%22%3Atrue}}&treeInfo={%22gitBranch%22%3A%22master%22%2C%22gitUrl%22%3A%22https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Ftorvalds%2Flinux.git%22%2C%22treeName%22%3A%22mainl …
=> fix: removing filter with more than one colon

dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTab.tsx
Hide card "Fail" in boots and tests tab.
Maybe this card will be used again, so MemoizedErrorCountList component has not been deleted.
- Closes #385
=> feat: hide card fail in boots and tests

dashboard/src/components/Table/TestsTable.tsx, dashboard/src/types/general.ts
some test is returning an empty status and null was not handled by it
Go to the link that was pointed as problematic an test the test table:
https://kernelci.slack.com/archives/C067UJC404A/p1729264297780649
http://localhost:5173/tree/171aa289a6fe65faffeb92a1fda283c055435a62?tableFilter=%7B%22buildsTable%22%3A%22invalid%22%2C%22bootsTable%22%3A%22all%22%2C%22testsTable%22%3A%22all%22%7D&origin=maestro&currentTreeDetailsTab=treeDetails.tests&diffFilter=%7B%7D&treeInfo=%7B%22gitBranch%22%3A%22for-next%22%2C%22gitUrl%22%3A%22https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Famlogic%2Flinux.git%22%2C%22treeName%22%3A%22amlogic%22%2C%22commitName%22%3A%22v6.12-rc1-20-g171aa289a6fe%22%2C%22headCommitHash%22%3A%22171aa289a6fe65faffeb92a1fda283c055435a62%22%7D
=> fix(test-tables): fix null pointer in tests

backend/kernelCI/settings.py, backend/kernelCI_app/apps.py, backend/kernelCI_app/cache.py, backend/kernelCI_app/urls.py, backend/kernelCI_app/views/treeDetailsSlowView.py, backend/kernelCI_app/views/treeView.py, dashboard/src/api/Tree.tsx
Creates the basic logic for caching database queries, currently it will only be applied to the slowest query.
Test by going to a tree details page and filtering the tests or boots tabs, the first load should be normal but any other filtering by status should be faster.
Closes: #301
=> feat: add query level cache logic

dashboard/src/components/Table/TreeTable.tsx
- On TreeListingPage show tooltip with the complete value of `Commit/Tag` column on hover
Close #394 
| ![image](https://github.com/user-attachments/assets/7f9d4487-520c-4cac-9cd1-f75e486f8500) |![image](https://github.com/user-attachments/assets/6bad4178-1e65-43b6-bdd3-72c8777a8616) |
=> feat: show tooltip with the complete value of Commit/Tag column

dashboard/src/components/Table/tableUtils.ts, dashboard/src/pages/TreeDetails/TreeDetails.tsx
- Commit/Tag: show full tag; on hover show commit hash
- URL: truncate on 12 chars; on hover show full URL
Close #395 
| | Before | After | 
|---|--------|--------|
| Commit/tab | ![image](https://github.com/user-attachments/assets/ed25d942-def8-4e52-916a-7fedea83287b) | ![image](https://github.com/user-attachments/assets/1d8f2c2c-4f77-4a4c-8c79-8149f0ea4ccf)|
|URL | ![image](https://github.com/user-attachments/assets/b64d9925-fc4f-42c2-af9f-6c9dce0f325d)|![image](https://github.com/user-attachments/assets/3ec5bbf2-dfe3-4c5a-93cd-3816dea1013a)|
=> fix: make Tree Details Header show full tag and full url on hover

backend/kernelCI_app/views/treeDetailsSlowView.py, dashboard/src/api/TreeDetails.tsx, dashboard/src/components/ui/badge.tsx, dashboard/src/locales/messages/index.ts, dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/TreeDetails/Tabs/TestCards.tsx, dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/pages/TreeDetails/TreeDetails.tsx, dashboard/src/pages/TreeDetails/TreeDetailsFilter.tsx, dashboard/src/types/tree/TreeDetails.tsx
Adding Hardware Used table in Tree details header
The table data shouldn't change by adding filters
- closes #384
=> feat: show hardware used in tests in tree details header

backend/kernelCI_app/views/treeDetailsSlowView.py, dashboard/src/components/Status/Status.tsx, dashboard/src/pages/TreeDetails/Tabs/TestCards.tsx, dashboard/src/types/tree/TreeDetails.tsx, dashboard/src/utils/constants/database.ts, dashboard/src/utils/status.ts
Add status count in hardware tested
Before just show the amount of occorencies
- Closes #411
=> feat: add status count in hardware tested

backend/kernelCI_app/views/treeDetailsSlowView.py, dashboard/src/components/ColoredCircle/ColoredCircle.tsx, dashboard/src/components/Status/Status.tsx, dashboard/src/components/Tabs/Tabs.tsx, dashboard/src/pages/TreeDetails/Tabs/TestCards.tsx, dashboard/src/pages/TreeDetails/Tabs/TreeDetailsTab.tsx, dashboard/src/pages/TreeDetails/TreeDetails.tsx
Add count to tabs in tree details and also fix the tree detail endpoint null count for test status
Go to any tree details and you should see this
Closes #391
=> feat: add count to tabs in tree details

backend/kernelCI_app/views/treeCommitsHistory.py, dashboard/src/api/TreeDetails.tsx, dashboard/src/pages/TreeDetails/Tabs/CommitNavigationGraph.tsx
Change the Tree Commit History SQL to allow pass filters in history charts.
1. Select a tree of your choice.
2. Play with filters and see the changes in History Chart
Close #264
=> Fix Filter in History Charts

backend/kernelCI_app/utils.py, backend/kernelCI_app/views/treeDetailsSlowView.py, dashboard/src/api/TreeDetails.tsx, dashboard/src/locales/messages/index.ts, dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/TreeDetails/TreeDetailsFilter.tsx, dashboard/src/types/tree/TreeDetails.tsx, dashboard/src/utils/filters.ts
Add filter by hardware and fix filter errors
1. got to http://localhost:5173/tree/7678c1b2735a048774c98c2d3b6b4718762c8570?tableFilter=%7B%22buildsTable%22%3A%22all%22%2C%22bootsTable%22%3A%22all%22%2C%22testsTable%22%3A%22all%22%7D&origin=maestro&currentTreeDetailsTab=treeDetails.builds&diffFilter=%7B%7D&treeInfo=%7B%22gitBranch%22%3A%22for-kernelci%22%2C%22gitUrl%22%3A%22https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Farm64%2Flinux.git%22%2C%22treeName%22%3A%22arm64%22%2C%22commitName%22%3A%22v6.12-rc4-141-g7678c1b2735a%22%2C%22headCommitHash%22%3A%227678c1b2735a048774c98c2d3b6b4718762c8570%22%7D
2. try to apply some filters
3. got to http://localhost:5173/tree/e9001a382fa2c256229adc68d55212028b01d515?tableFilter=%7B%22buildsTable%22%3A%22all%22%2C%22bootsTable%22%3A%22 …
=> feat: add filter by hardware

backend/kernelCI_app/serializers.py, backend/kernelCI_app/views/buildTestsView.py, backend/requests/build-tests-get.sh, dashboard/src/api/buildTests.ts, dashboard/src/pages/BuildDetails/BuildDetailsTestSection.tsx, dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTable.tsx, dashboard/src/pages/TreeDetails/Tabs/Build/BuildsTable.tsx, dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTable.tsx, dashboard/src/routes/tree/$treeId/build/$buildId/index.tsx, dashboard/src/types/general.ts, dashboard/src/types/tree/TreeDetails.tsx
- make TestTable more flexible to reuse it on other pages
- use TestTable in BuildDetails page
Close: #386 
Check out the `Test Results` section of a BuildDetails Page
| ![image](https://github.com/user-attachments/assets/ef02e24f-007c-4355-9fa3-2077b422d6c1) | ![image](https://github.com/user-attachments/assets/c640416f-7bc6-4c88-97c0-851ac5996cd1) |
=> feat: on Build Details Page replace tests table by tests table from Tests tab

backend/kernelCI_app/views/treeCommitsHistory.py
hardware filters are not ready in commit graph so we remove them from the filter in the commit graph
=> fix: filter out hardware filter

dashboard/src/pages/TreeDetails/Tabs/Build/BuildsTable.tsx
Fixes the display of "buildTime" in the build details table.
Before: 
After:
Test URL: http://localhost:5173/tree/59cbd4eea48fdbc68fc17a29ad71188fea74b28b?tableFilter={%22buildsTable%22%3A%22all%22%2C%22bootsTable%22%3A%22all%22%2C%22testsTable%22%3A%22failed%22}&origin=redhat&currentTreeDetailsTab=treeDetails.builds&diffFilter={}&treeInfo={%22gitBranch%22%3A%22master%22%2C%22gitUrl%22%3A%22https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Fvirt%2Fkvm%2Fkvm.git%22%2C%22treeName%22%3A%22kvm%22%2C%22commitName%22%3A%22for-linus-1-g59cbd4eea48f%22%2C%22headCommitHash%22%3A%2259cbd4eea48fdbc68fc17a29ad71188fea74b28b%22}
Closes #455
=> fix: build time table cell display

backend/kernelCI_app/views/issuesView.py
Close: #452 
| ![image](https://github.com/user-attachments/assets/af6f0316-b6bf-4e25-989a-f5f194bdcfad) | ![image](https://github.com/user-attachments/assets/308f2fa2-743f-45af-bfb1-66f6dbb29257) |
=> fix: issue endpoints was missing incidentis_info field

backend/kernelCI_app/views/treeCommitsHistory.py, dashboard/src/pages/TreeDetails/Tabs/CommitNavigationGraph.tsx, dashboard/src/types/tree/TreeDetails.tsx
Add null tests count
Compare [localhost](http://localhost:5173/tree/1bf329c696cf80000f1098bcdc23534e6fe14fe2?tableFilter=%7B%22buildsTable%22%3A%22all%22%2C%22bootsTable%22%3A%22all%22%2C%22testsTable%22%3A%22all%22%7D&origin=maestro&currentTreeDetailsTab=treeDetails.tests&diffFilter=%7B%22testStatus%22%3A%7B%22NULL%22%3Atrue%7D%7D&treeInfo=%7B%22gitBranch%22%3A%22for-kernelci%22%2C%22gitUrl%22%3A%22https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Farm64%2Flinux.git%22%2C%22treeName%22%3A%22arm64%22%2C%22commitName%22%3A%22v6.12-rc5-145-g1bf329c696cf%22%2C%22headCommitHash%22%3A%221bf329c696cf80000f1098bcdc23534e6fe14fe2%22%7D)  with [dashboard](https://dashboard.kernelci.org/tree/1bf329c696cf80000f1098bcdc23534e6fe14fe2?tableFilter=%7B%22buildsTable%22%3A%2 …
=> Fix History Chart Filter

dashboard/package.json, dashboard/pnpm-lock.yaml, dashboard/src/components/Table/BaseTable.tsx, dashboard/src/components/Table/TableHeader.tsx, dashboard/src/pages/TreeDetails/Tabs/Tests/IndividualTestsTable.tsx, dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTable.tsx
Adds virtualization (rendering only visible items) on the tests table. The rows of the table will be incrementally added instead of loaded all at once.
Go to [localhost example](http://localhost:5173/tree/58e2d28ed28e5bc8836f8c14df1f94c27c1f9e2f?tableFilter=%7B%22buildsTable%22%3A%22all%22%2C%22bootsTable%22%3A%22all%22%2C%22testsTable%22%3A%22all%22%7D&origin=maestro&currentTreeDetailsTab=treeDetails.tests&diffFilter=%7B%7D&treeInfo=%7B%22gitBranch%22%3A%22for-next%22%2C%22gitUrl%22%3A%22https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Famlogic%2Flinux.git%22%2C%22treeName%22%3A%22amlogic%22%2C%22commitName%22%3A%22v6.12-rc1-18-g58e2d28ed28e5%22%2C%22headCommitHash%22%3A%2258e2d28ed28e5bc8836f8c14df1f94c27c1f9e2f%22%7D), scroll down to the tests table and open a CI with …
=> Feat(#371): add virtualization to tests table

backend/kernelCI_app/utils.py, backend/kernelCI_app/views/treeCommitsHistory.py, dashboard/src/api/TreeDetails.tsx
Go to Tree Details, in Boots or Tests tabs and apply hardwere filters.
Ex.: http://localhost:5173/tree/1bf329c696cf80000f1098bcdc23534e6fe14fe2?tableFilter=%7B%22buildsTable%22%3A%22all%22%2C%22bootsTable%22%3A%22all%22%2C%22testsTable%22%3A%22all%22%7D&origin=maestro&currentTreeDetailsTab=treeDetails.boots&diffFilter=%7B%7D&treeInfo=%7B%22gitBranch%22%3A%22for-kernelci%22%2C%22gitUrl%22%3A%22https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Farm64%2Flinux.git%22%2C%22treeName%22%3A%22arm64%22%2C%22commitName%22%3A%22v6.12-rc5-145-g1bf329c696cf%22%2C%22headCommitHash%22%3A%221bf329c696cf80000f1098bcdc23534e6fe14fe2%22%7D
Close #430
=> Add filter by hardware in History Chart

dashboard/src/pages/TreeDetails/Tabs/TestCards.tsx
Adds a FilterLink wrapper around hardware items in the hardware card for the boots and tests tab.
Test by going to any tree with boots or tests data (that have a hardware linked to any of them), see the "hardware tested" card and click on any item to filter the data by hardware. [Localhost example](http://localhost:5173/tree/1bf329c696cf80000f1098bcdc23534e6fe14fe2?tableFilter=%7B%22buildsTable%22%3A%22all%22%2C%22bootsTable%22%3A%22all%22%2C%22testsTable%22%3A%22all%22%7D&origin=maestro&currentTreeDetailsTab=treeDetails.boots&diffFilter=%7B%7D&treeInfo=%7B%22gitBranch%22%3A%22for-kernelci%22%2C%22gitUrl%22%3A%22https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Farm64%2Flinux.git%22%2C%22treeName%22%3A%22arm64%22%2C%22commitName%22%3A%22v6.12-rc5-145-g1bf329c696cf%22%2C%22he …
=> Feat: clickable hardware filter

backend/kernelCI_app/views/treeCommitsHistory.py, backend/kernelCI_app/views/treeDetailsSlowView.py, backend/kernelCI_app/views/treeDetailsView.py, dashboard/src/pages/TreeDetails/TreeDetailsFilter.tsx
Shows unknown hardware, configs, archs and compilers in the cards for tests and boots tab.
Go to http://localhost:5173/tree/1bf329c696cf80000f1098bcdc23534e6fe14fe2?tableFilter=%7B%22buildsTable%22%3A%22all%22%2C%22bootsTable%22%3A%22all%22%2C%22testsTable%22%3A%22all%22%7D&origin=maestro&currentTreeDetailsTab=treeDetails.tests&diffFilter=%7B%7D&treeInfo=%7B%22gitBranch%22%3A%22for-kernelci%22%2C%22gitUrl%22%3A%22https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Farm64%2Flinux.git%22%2C%22treeName%22%3A%22arm64%22%2C%22commitName%22%3A%22v6.12-rc5-145-g1bf329c696cf%22%2C%22headCommitHash%22%3A%221bf329c696cf80000f1098bcdc23534e6fe14fe2%22%7D
And see the listing of unknown configs, archs and hardwares, try clicking on the configs/archs for filtering or using the filters …
=> Feat: count unknown stats

dashboard/src/api/TreeDetails.tsx, dashboard/src/api/api.ts, dashboard/src/api/hardwareDetails.ts, dashboard/src/components/TreeListingPage/TreeTable.tsx, dashboard/src/pages/TreeDetails/TreeDetails.tsx, dashboard/src/pages/hardwareDetails/HardwareDetails.tsx, dashboard/src/pages/hardwareDetails/HardwareDetailsHeaderTable.tsx, dashboard/src/routes/hardware/$hardwareId/route.tsx, dashboard/src/routes/hardware/route.tsx, dashboard/src/types/hardware/hardwareDetails.ts
Enables filtering for trees in the Hardware Details page and selection for the header table.
Enable dev feature flag before running the front-end by running `export VITE_FEATURE_FLAG_SHOW_DEV=true`
Enter the hardware details page and try out the row selection, check the url to see how it is sent to the backend and you may try to change the selection manually by changing the url. 
PIGGYBACKING: fixes unnecessary and wrongfully passed search parameters when clicking on the breadcrumbs.
Closes #500 
Part of #446
=> Feat: hardware details tree filter

backend/kernelCI_app/views/hardwareDetailsView.py, dashboard/src/api/hardwareDetails.ts, dashboard/src/components/Filter/Drawer.tsx, dashboard/src/locales/messages/index.ts, dashboard/src/pages/TreeDetails/TreeDetailsFilter.tsx, dashboard/src/pages/TreeDetails/treeDetailsUtils.ts, dashboard/src/pages/hardwareDetails/HardwareDetails.tsx, dashboard/src/pages/hardwareDetails/HardwareDetailsFilter.tsx, dashboard/src/pages/hardwareDetails/HardwareDetailsFilterLink.tsx, dashboard/src/pages/hardwareDetails/HardwareDetailsFilterList.tsx, dashboard/src/pages/hardwareDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/hardwareDetails/Tabs/Build/BuildTab.tsx, dashboard/src/pages/hardwareDetails/Tabs/HardwareDetailsTabs.tsx, dashboard/src/pages/hardwareDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/pages/hardwareDetails/hardwareDetailsUtils.ts, dashboard/src/routes/hardware/$hardwareId/route.tsx, dashboard/src/types/hardware/hardwareDetails.ts
In this PR, I add the filters in hardware details in frontend and add counts in hardware tabs.
Close #572
=> Add hardware details filters

backend/kernelCI_app/utils.py, backend/kernelCI_app/views/treeCommitsHistory.py, backend/kernelCI_app/views/treeDetailsSlowView.py, dashboard/src/components/BootsTable/BootsTable.tsx, dashboard/src/components/Cards/HardwareUsed.tsx, dashboard/src/components/Tabs/Tabs.tsx, dashboard/src/components/TestsTable/TestsTable.tsx, dashboard/src/components/ui/tabs.tsx, dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/pages/TreeDetails/TreeDetails.tsx, dashboard/src/pages/TreeDetails/TreeDetailsFilter.tsx, dashboard/src/pages/TreeDetails/TreeDetailsFilterList.tsx, dashboard/src/pages/hardwareDetails/HardwareDetails.tsx, dashboard/src/pages/hardwareDetails/HardwareDetailsFilterList.tsx, dashboard/src/pages/hardwareDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/hardwareDetails/Tabs/Tests/HardwareDetailsTestsTable.tsx, dashboard/src/pages/hardwareDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/types/hardware/hardwareDetails.ts, dashboard/src/types/tree/TreeDetails.tsx, dashboard/src/utils/filters.ts
- Updates UI to make tab change and filter list sticky
- Updates UI to put path searchbox within the column
- Adds filtering by test path to treeDetails page
Go to tests or boots tab in any treeDetails page with boots or tests data,
Scroll down to see the sticky tab selection and filter listing,
Type something in the searchbox alongside the path column,
After a certain delay, the whole page will be filtered by passing a new diffFilter,
Check the filter listing and the diffFilter search param,
The returned data should be filtered by path, including individual tests under the external tests table.
Closes #524
=> Feat: add path filter to tree details

dashboard/src/components/BuildsTable/BuildsTable.tsx, dashboard/src/locales/messages/index.ts, dashboard/src/pages/TreeDetails/Tabs/Build/TreeDetailsBuildsTable.tsx, dashboard/src/pages/hardwareDetails/Tabs/Build/HardwareDetailsBuildsTable.tsx, dashboard/src/types/tree/TreeDetails.tsx, dashboard/src/utils/utils.ts
Adds an "arch" column to the build execution list aka buildsTable.
Added as the second column to follow the arch summary card, which shows the architecture before the compiler.
Go to a hardwareDetails page or TreeDetails page with build data, scroll down, check the arch column in the buildsTable.
Closes #590
=> Feat: add arch column on buildsTable

backend/kernelCI_app/utils.py, backend/kernelCI_app/views/hardwareDetailsView.py, backend/kernelCI_app/views/treeDetailsSlowView.py, dashboard/src/components/BootsTable/BootsTable.tsx, dashboard/src/components/BuildsTable/BuildsTable.tsx, dashboard/src/components/TestsTable/IndividualTestsTable.tsx, dashboard/src/components/TestsTable/TestsTable.tsx, dashboard/src/components/TreeListingPage/TreeTable.tsx, dashboard/src/pages/Hardware/HardwareTable.tsx, dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/pages/TreeDetails/TreeDetailsFilter.tsx, dashboard/src/pages/hardwareDetails/HardwareDetailsFilter.tsx, dashboard/src/pages/hardwareDetails/HardwareDetailsHeaderTable.tsx, dashboard/src/pages/hardwareDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/hardwareDetails/Tabs/Tests/HardwareDetailsTestsTable.tsx, dashboard/src/pages/hardwareDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/types/hardware/hardwareDetails.ts, dashboard/src/types/tree/TreeDetails.tsx, dashboard/src/utils/filters.ts
- Splits path filter between boots and tests, now one doesn't affect the other.
- Adds filtering to hardwareDetails page;
- Syncs filter listing and input field, after removing the path filter from the filter list the input field will also clear;
- Fixes boot commit history graph not using the path filter.
Also refactors the sorting exhaustive-deps useMemo dependency just so eslint can complain if a useMemo dependency is missing
Go to a tree details page with boot and/or test data, scroll down and use the searchbox alongside the path column. Check the filtering of the table and the commit history graph. Compare this with the previous version currently on staging.
Also go to a hardware details page with boot and/or test data and see the same behavior as in tree details (except for the …
=> Feat: HD path filter and patches

backend/kernelCI_app/views/hardwareDetailsView.py, backend/kernelCI_app/views/treeCommitsHistory.py, backend/requests/hardware-details-post.sh, dashboard/src/api/TreeDetails.tsx, dashboard/src/api/commitHistory.ts, dashboard/src/api/hardwareDetails.ts, dashboard/src/components/CommitNavigationGraph/CommitNavigationGraph.tsx, dashboard/src/pages/Hardware/HardwareListingPage.tsx, dashboard/src/pages/Hardware/HardwareTable.tsx, dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/TreeDetails/Tabs/Build/BuildTab.tsx, dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/pages/TreeDetails/Tabs/TreeCommitNavigationGraph.tsx, dashboard/src/pages/hardwareDetails/HardwareDetails.tsx, dashboard/src/pages/hardwareDetails/HardwareDetailsHeaderTable.tsx, dashboard/src/pages/hardwareDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/hardwareDetails/Tabs/Build/BuildTab.tsx, dashboard/src/pages/hardwareDetails/Tabs/HardwareCommitNavigationGraph.tsx, dashboard/src/pages/hardwareDetails/Tabs/HardwareDetailsTabs.tsx, dashboard/src/pages/hardwareDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/routes/hardware/$hardwareId/route.tsx, dashboard/src/types/hardware/hardwareDetails.ts, dashboard/src/utils/utils.ts
- refactor: make CommitNavigationGraph route-agnostic
- fix: commit history should be counted from the head backwards
- feat: add filter by commit hash in hardwareDetails endpoint
- feat: add CommitNavigationGraph to HardwareDetails tabs
- feat: increase tree selection debounce to 2s
- feat: the hardwareDetails endpoint only need a limit time
Close #477 
1. Go to any HardwareDetails page
2. Let just one three selected
3. Navigate to the commit history using the CommitNavigationGraph
> Note: the status count is not correct for the builds tab, this is because of the way that the endpoint commitHistory currently works. We have issue #601 to fix this, which will be resolved soon
=> feat(HardwareDetails page): add CommitNavigationGraph to all tabs

backend/kernelCI_app/views/hardwareDetailsView.py, backend/kernelCI_app/views/treeDetailsSlowView.py, backend/kernelCI_app/views/treeDetailsView.py, dashboard/src/components/Cards/IssuesList.tsx, dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/TreeDetails/Tabs/Build/BuildTab.tsx, dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/pages/TreeDetails/TreeDetails.tsx, dashboard/src/pages/hardwareDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/hardwareDetails/Tabs/Build/BuildTab.tsx, dashboard/src/pages/hardwareDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/types/hardware/hardwareDetails.ts, dashboard/src/types/tree/TreeDetails.tsx
Add a counter containing the number of failed tests with no linked issues. To do it, add an optional parameter to `IssuesList` that accept the number of total failed tests/builds/boots. If the parameter is not present the behaviour of the Issues List is equal as it was before, otherwise it adds a new line to the list containing the number of unknown issues.
Close #544
=> feat(IssuesList): add a counter for unknown issues

dashboard/src/api/TreeDetails.tsx, dashboard/src/api/hardwareDetails.ts, dashboard/src/components/FilterList/FilterList.tsx, dashboard/src/components/ui/loading-circle.tsx, dashboard/src/pages/TreeDetails/TreeDetails.tsx, dashboard/src/pages/TreeDetails/TreeDetailsFilterList.tsx, dashboard/src/pages/hardwareDetails/HardwareDetails.tsx, dashboard/src/pages/hardwareDetails/HardwareDetailsFilterList.tsx
Adds a loading circle and async loading for treeDetails and hardwareDetails filtering.
Go to treeDetails page or hardwareDetails page and add any filter, the page won't show the "Loading" screen anymore, instead it will show a loading circle in the filterListing and will only update the page after the data has been fetched.
This works not only for the test path filtering but also for any other filter, although with the path filter it's more noticeable.
Closes #585
=> Feat: async filters

dashboard/src/components/BootsTable/BootsTable.tsx, dashboard/src/components/BuildsTable/BuildsTable.tsx, dashboard/src/components/Filter/CodeBlock.tsx, dashboard/src/components/TestsTable/IndividualTestsTable.tsx, dashboard/src/components/ui/sheet.tsx, dashboard/src/pages/TreeDetails/Tabs/LogSheet.tsx
Increase the log sheet modal width and also improve the visibility of the log that's being shown by using a darker color to highlight the table row and by decreasing the opacity of the sheet overlay.
Closes #595
Before
After
=> change: widen the modal and improve visibility

dashboard/src/components/CommitNavigationGraph/CommitNavigationGraph.tsx
Change from showing 7 commit name characters for each point in the graph in the x-Axis to showing 8 commit hash characters for each point in the graph.
Closes #589 
Before
After
=> feat: show 8 commit hash chars in the Commit Graph

dashboard/src/components/BuildDetails/BuildDetails.tsx, dashboard/src/components/LinkWithIcon/LinkWithIcon.tsx, dashboard/src/components/Section/Section.tsx, dashboard/src/components/TestDetails/TestDetails.tsx, dashboard/src/components/TopBar/TopBar.tsx, dashboard/src/locales/messages/index.ts, dashboard/src/main.tsx, dashboard/src/pages/BuildDetails/BuildDetails.tsx, dashboard/src/pages/BuildDetails/index.tsx, dashboard/src/pages/HardwareBuildDetails/HardwareBuildDetails.tsx, dashboard/src/pages/HardwareTestDetails/HardwareTestDetails.tsx, dashboard/src/pages/TestDetails/TestDetails.tsx, dashboard/src/pages/TestDetails/index.tsx, dashboard/src/pages/TreeBuildDetails/TreeBuildDetails.tsx, dashboard/src/pages/TreeTestDetails/TreeTestDetails.tsx, dashboard/src/routeTree.gen.ts, dashboard/src/routes/build/$buildId/index.tsx, dashboard/src/routes/build/$buildId/route.tsx, dashboard/src/routes/hardware/$hardwareId/build/$buildId/index.tsx, dashboard/src/routes/hardware/$hardwareId/test/$testId/index.tsx, dashboard/src/routes/test/$testId/index.tsx, dashboard/src/routes/test/$testId/route.tsx, dashboard/src/routes/tree/$treeId/build/$buildId/index.tsx, dashboard/src/routes/tree/$treeId/test/$testId/index.tsx, dashboard/src/types/general.ts
Add two new routes /test/$testId and /build/$buildId, removing the need of accessing tests or builds through /hardware or /tree. Also, redirects the old routes to the new ones.
Closes #555
=> feat: add new routes for tests and builds

backend/kernelCI_app/views/treeCommitsHistory.py
Fix checkouts that has no commit hash, we don't want that, the whole point of a checkout is to have a commit hash
it was being spitted by the redhat origin
Closes #644
- Staging
https://staging.dashboard.kernelci.org:9000/tree/8c212fb0b0e1aa8e1a5cf84c17fced714df48c4b?tableFilter=%7B%22bootsTable%22%3A%22all%22%2C%22buildsTable%22%3A%22all%22%2C%22testsTable%22%3A%22all%22%7D&origin=redhat&currentPageTab=global.builds&diffFilter=%7B%7D&treeInfo=%7B%22gitUrl%22%3A%22https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Fstable%2Flinux-stable-rc.git%22%2C%22gitBranch%22%3A%22queue%2F6.11%22%2C%22treeName%22%3A%22upstream-stable-queue%22%2C%22commitName%22%3A%22v6.11.10-804-g8c212fb0b0e1%22%2C%22headCommitHash%22%3A%228c212fb0b0e1aa8e1a5cf84c17fced714df48c4b%22%7D&intervalInDays=7 …
=> fix: null pointer for checkout without commit hash

backend/kernelCI_app/views/treeCommitsHistory.py
Select distinct rows on git_commit_hash since there can exist multiple rows in checkouts with equal git commit hashes, tree and branch but with different checkouts IDs. This distinct git_commit_hash needs to be selected from a different CTE then the one used to count the builds/boots/tests status to keep the values correct in the graph
Closes #611
=> fix(treeCommitsHistory): fetch distinct hashes

backend/kernelCI_app/helpers/filters.py, backend/kernelCI_app/utils.py, backend/kernelCI_app/views/hardwareDetailsView.py, backend/kernelCI_app/views/treeDetailsView.py, dashboard/src/components/Tabs/Filters.tsx, dashboard/src/pages/hardwareDetails/HardwareDetailsFilter.tsx
- Fixes a bug where the boots and tests issues weren't being shown in the hardwareDetails page
- Adds the issue filter handling in the hardwareDetailsView endpoint
- Adds the issue filter sections in the hardwareDetails page frontend
- Hides checkbox filter sections if they are empty
Go to a hardwareDetails page with issues data, such as this [localhost example](http://localhost:5173/hardware/google,tomato-rev2?intervalInDays=1&origin=maestro&limitTimestampInSeconds=1733765557&currentPageTab=global.boots&tableFilter=%7B%22buildsTable%22%3A%22all%22%2C%22bootsTable%22%3A%22failed%22%2C%22testsTable%22%3A%22all%22%7D&diffFilter=%7B%7D&treeIndexes=%5B%5D) and try out the issue filter. Also compare it to the [equivalent page in staging](https://staging.dashboard.kernelci.org:9000/hardware/goog …
=> Feat (hardwareDetails): Issues Filter

dashboard/src/components/TreeListingPage/TreeTable.tsx, dashboard/src/pages/Hardware/HardwareTable.tsx, dashboard/src/types/table.ts
- Adds the correct tab direction to the hardwareListingTable by passing a custom property in the column meta
- Refactors the treeListingTable to use the same logic as the hardwareListingTable for tab direction
The tab direction was made by using the `meta` property for the column definition, which doesn't have explicit typing so I need to typecast it to a custom type. If I extended the `Column` or `ColumnDef` types, they got lost in the abstraction of the cell (I can define `columns` as a `CustomColumn` type, but `cell.column` will still be the original `Column` type, so I can't retrieve the custom property)
Another way to do this, which is told by [the documentation](https://tanstack.com/table/v8/docs/api/core/column-def#meta), is to extend the entire module of tanstack-table to define a …
=> Feat: hardware listing tab direction

dashboard/package.json, dashboard/pnpm-lock.yaml, dashboard/src/main.tsx, dashboard/src/utils/search.test.ts, dashboard/src/utils/search.ts
Uses query-string parse/stringify as the new serialization and deserialization methods ensuring a cleaner URL as stated in the URL proposal document.
Closes #657 
- Currently, I'm using the character '|' to flatten the elements, but it's a character that can be URI encoded, so maybe we should think of another one to avoid making the URL too 'messy'. The same goes for the comma that I'm using to separate array elements in the URL (treeIndexes up to now). 
- Check if the way the data is structured is good. Because of the object 'flattening', the URL has ended up being larger (since it repeats the name 'treeInfo' several times, for example). I decided to start with the 'query-string' library, and that's why this 'flattening' was necessary. Another solution would be to use jsurl2 or create …
=> feat: Change query params serialization

LICENSE
The KernelCI TSC has decided for the MIT license for the dashboard.
=> Create MIT LICENSE file

backend/kernelCI_app/helpers/misc.py, backend/kernelCI_app/utils.py, backend/kernelCI_app/views/hardwareDetailsView.py, backend/kernelCI_app/views/treeCommitsHistory.py, backend/kernelCI_app/views/treeDetailsView.py, dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/types/tree/TreeDetails.tsx
Add a new logic to the backend where `environment_misc.platform` will work as a fallback case for when the `environment_compatabile` field is null in the database. When `environment_misc.plaftorm` is null, we'll use `build.misc.platform`, but the logic of the Hardware filter will be kept the same, meaning that the builds returned will be first the build associated with the tests that have that hardware. This means that even if `build.misc.platform` is null but the build is associated with a test that have `environment_compatible` or `environment_misc.platform` not null, it will also be added when filtering for that hardware
This drastically lowers the number of Unknown hardware but they can still occur if both `environment_compatible` and `environment_misc.platform` and …
=> feat: consider env_misc.platform as hardware

backend/kernelCI_app/views/hardwareDetailsView.py, backend/kernelCI_app/views/hardwareView.py
-   Compare the counter [hardware google,juniper-sku16](https://staging.dashboard.kernelci.org:9000/hardware?hardwareSearch=google%2Cjuniper-sku) in hardware listing with the counter in hardware details.
-   Test the same hardware counter in [localhost](http://localhost:5173/hardware?hardwareSearch=google%2Cjuniper-sku)
Close of #687
=> Feat(hardware): Difference between hardware listing and hardware details tests counts

backend/kernelCI_app/views/treeCommitsHistory.py, dashboard/src/api/commitHistory.ts, dashboard/src/components/CommitNavigationGraph/CommitNavigationGraph.tsx, dashboard/src/pages/hardwareDetails/Tabs/HardwareCommitNavigationGraph.tsx
Add startTimestamp and endTimestamp in commit history charts.
Close #688 
**How to Test**
- Select any Hardware and fix one tree to see the commits history. Try to select another commit in chart.
- e.g. [hardware: google,juniper-sku16  tree: arbd/for-kernelci](http://localhost:5173/hardware/google%2Cjuniper-sku16?endTimestampInSeconds=1734714000&startTimestampInSeconds=1734454800&treeIndexes[]=0) 
- Select any Tree and see the same behavior as in staging
=> Fix: Navigation in Hardware Details by Commit History Chart

dashboard/src/components/SideMenu/NavLink.tsx, dashboard/src/components/SideMenu/SideMenu.tsx, dashboard/src/routes/__root.tsx
- Added `selected` prop to `NavLink` component to handle selected state
- Updated `SideMenuItem` to use `NavLink` with `selected` prop
- Removed redundant class names from `SideMenu` and `SideMenuItem`
- Added `overflow-x-auto` to main content div in `__root.tsx`
=> feat(improvements):  some minor improvements

backend/kernelCI_app/typeModels/databases.py, backend/kernelCI_app/typeModels/hardwareDetails.py, backend/kernelCI_app/views/hardwareDetailsView.py
After further research, apparently the problem only existed in the boots table in hardware details. The can be seem in this page [Tests table showing 'NULL' status correctly](https://staging.dashboard.kernelci.org:9000/tree/0d7aea765c41401c36c9d0a1d039a2cf30df430e?currentPageTab=global.tests&treeInfo%7CcommitName=v6.13-rc3-4-g0d7aea765c41&treeInfo%7CgitBranch=for-kernelci&treeInfo%7CgitUrl=https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Fardb%2Flinux.git&treeInfo%7CheadCommitHash=0d7aea765c41401c36c9d0a1d039a2cf30df430e&treeInfo%7CtreeName=ardb), this page [Boots table showing 'NULL' status correctly](https://staging.dashboard.kernelci.org:9000/tree/e43857dccff0b7f2e13a9edf394f1283c116a4df?currentPageTab=global.boots&tableFilter%7CbootsTable=inconclusive&tableFilter%7Cbuil …
=> fix: show 'NULL' instead of nothing in status col

backend/kernelCI_app/typeModels/issueDetails.py, backend/kernelCI_app/urls.py, backend/kernelCI_app/views/issueDetailsBuildsView.py, backend/kernelCI_app/views/issueDetailsTestsView.py, backend/kernelCI_app/views/issueDetailsView.py, backend/requests/issue-details-builds-get.sh, backend/requests/issue-details-tests-get.sh, dashboard/src/api/issueDetails.ts, dashboard/src/components/BuildDetails/BuildDetailsTestSection.tsx, dashboard/src/components/DetailsPages/SectionError.tsx, dashboard/src/components/IssueDetails/IssueDetails.tsx, dashboard/src/components/IssueDetails/IssueDetailsBuildSection.tsx, dashboard/src/components/IssueDetails/IssueDetailsTestSection.tsx, dashboard/src/pages/IssueDetails/IssueDetails.tsx, dashboard/src/types/general.ts, dashboard/src/utils/constants/tables.ts, dashboard/src/utils/utils.ts
Adds /issues/<issue_id>/version/<version>/tests endpoint to get all tests related to an issue
Adds /issues/<issue_id>/version/<version>/builds endpoint to get all builds related to an issue
Adds request for these endpoints from the frontend
Adds a SectionError component for when a table in a details page can't load and refactors its use in BuildDetailsTestSection
Adds a TestsTable to the IssueDetails page when the current issue is related to a test
Adds a BuildsTable to the IssueDetails page when the current issue is related to a test
The relation with tests and builds are intuitively mutually exclusive, but - since the database allows for both `test_status` and `build_valid` to be not null in a single issue - it is technically possible for an issue to be associated with tests and builds …
=> Feat: IssueDetails test and build info

dashboard/src/routes/__root.tsx
overflow-x-auto was being used to create a blocking formatting context
to contain everything inside the div as much as possible
but as unintended side effects it broke our position sticky
we have a ticket to properly create a mobile layout in #324, let's remove the
hack here and leave the ticket for that
Closes #726
=> fix: sticky not working on top bar

backend/kernelCI_app/typeModels/treeDetails.py, backend/kernelCI_app/urls.py, backend/kernelCI_app/views/treeLatest.py, backend/requests/tree-latest-get.sh, dashboard/src/api/tree.ts, dashboard/src/pages/TreeLatest.tsx, dashboard/src/routeTree.gen.ts, dashboard/src/routes/tree/$treeName/$branch/index.tsx, dashboard/src/routes/tree/$treeName/route.tsx, dashboard/src/types/tree/Tree.tsx
Add a new route `/<tree-name>/<branch>` that redirects to the TreeDetails for the latest checkout of the tree.
Closes #675 
- To go `localhost:5173/<tree-name>/<branch>` for a valid `<tree-name>` and `<branch>` and see if it correctly redirects to the TreeDetails page. For example: http://localhost:5173/tree/android/android-mainline
- To go `localhost:5173/<tree-name>/<branch>` for an invalid `<tree-name>` and/or `<branch>` and see if it correctly shows an error message. For example: http://localhost:5173/tree/android/invalid-branch
=> Add latest tree data in route /<tree_name>/<branch>

dashboard/src/components/TestDetails/TestDetails.tsx, dashboard/src/locales/messages/index.ts
Important: What is being called Job Id in the section corresponds to the test id everywhere else in the code
Closes #743
=> feat(TestDetails): add job id value

dashboard/src/routes/__root.tsx, dashboard/src/routes/build/$buildId/route.tsx, dashboard/src/routes/hardware/$hardwareId/route.tsx, dashboard/src/routes/hardware/route.tsx, dashboard/src/routes/index.tsx, dashboard/src/routes/issue/$issueId/version/$versionNumber/route.tsx, dashboard/src/routes/test/$testId/route.tsx, dashboard/src/routes/tree/$treeId/route.tsx, dashboard/src/routes/tree/route.tsx, dashboard/src/types/general.ts, dashboard/src/types/tree/TreeDetails.tsx, dashboard/src/utils/search.test.ts, dashboard/src/utils/search.ts
- Added the object `minifiedParams` to map all the params to their minified forms.
- Added the function `minifyParmas` that return a object with the params minified based on the object `minifiedParams`
- Added the object `groupedMinifiedParams` that divide the minified params in five groups based on the depth of the nested objects in searchParams: general, df (for DiffFilter nested object), ti (for TreeInfo nested object), tf (for TableFilter nested object) and value (for minified values instead of keys). This was required to identify different attributes that were minified to the same value (e.g. 't' for treeInfo.treeName, TableFilter.testsTable and diffFilter.trees)
- Added the function `unminifyParams` that return a object with the original param names based on the object …
=> feat: minify URL query parameters

dashboard/src/components/IssueDetails/IssueDetails.tsx, dashboard/src/components/IssueDetails/IssueDetailsBuildSection.tsx, dashboard/src/components/IssueDetails/IssueDetailsTestSection.tsx
Whenever an issue has its `build_valid` and `test_status` as null (I'm calling it an independent issue, but that's not an official name) it still may have incidents. So this PR makes it so that if an issue is independent it tries to get both tests and builds data (since it's not possible to tell to which one it is related to without another query anyway)
Example of an independent issue with build incidents: http://localhost:5173/issue/redhat%3Aissue_3332/version/1733923991
Example of an independent issue with test incidents: http://localhost:5173/issue/redhat%3Aissue_3137/version/1727863073
Example of an independent issue with no incidents: http://localhost:5173/issue/redhat:issue_2770/version/1725465507
Example of a tree with a build that has an incident of an independent issue: …
=> Feat: get independent issues incidents

backend/kernelCI_app/views/testDetailsView.py, dashboard/src/components/BuildDetails/BuildDetails.tsx, dashboard/src/components/TestDetails/TestDetails.tsx
Fixes test details pages that are related to unexistent builds using left joins and default values
Simple refactors to the build details page to make it tidier
The bug for the buildDetails page was fixed at https://github.com/kernelci/dashboard/pull/730/commits/95700d306f38499c7534620c3b9f9d2dd11d251f by the use of the left join - that build is related to an unexistent checkout
Go to http://localhost:5173/build/maestro%3A673f7646923416c0c98d2796 (build with unexistent checkout) and see that it still works, compare to https://dashboard.kernelci.org/build/maestro%3A673f7646923416c0c98d2796
Go to http://localhost:5173/test/maestro%3A674a3a4c069b6571df5af400 (test with unexistent build) and see that it still works, compare to https://staging.dashboard.kernelci.org:9000/test/maestro%3A674a3a4c0 …
=> Fix: builds and tests details related to unexistent build/checkout

backend/kernelCI_app/helpers/filters.py, backend/kernelCI_app/helpers/treeDetails.py, backend/kernelCI_app/typeModels/issueDetails.py, backend/kernelCI_app/unitTests/treeDetails.test.py, backend/kernelCI_app/views/hardwareDetailsView.py, backend/kernelCI_app/views/issuesView.py, backend/kernelCI_app/views/treeCommitsHistory.py, backend/kernelCI_app/views/treeDetailsView.py
- Fixes a behavior where some build issues were listed in the issues card of the tests tab and vice-versa.
- Makes testDetails and buildDetails show different entries for issues with different versions. This also fixes some issues that were being counted from the versions but which weren't present in the tests/builds
- Adds unit tests for the `should_filter_test_issue`
There were tests which were related to a build that had an issue, and since the test failed, there were the right conditions to think that the issue should be incremented in the test issue list. Failed or inconclusive builds with a test that had an issue were also considering that issue as if they were build issues.
For the tests tab, go to this [localhost example](http://localhost:5173/tree/3ea7cd6069be582be5569600fd5b9f540 …
=> Fix: issue card count

backend/kernelCI_app/helpers/treeDetails.py, backend/kernelCI_app/utils.py, backend/kernelCI_app/views/hardwareDetailsView.py, backend/kernelCI_app/views/treeCommitsHistory.py, dashboard/src/components/TestsTable/DefaultTestsColumns.tsx, dashboard/src/components/TestsTable/TestsTable.tsx
Some parts of code are ignoring tests with `null` path, while other parts are ignoring this tests.
To make consistent, the follow approach is implemented:
- treat `null` path as nonboot tests
- ignoring test id null
Close #741
=> Fix: Inconclusive test counts

backend/kernelCI_app/helpers/treeDetails.py, backend/kernelCI_app/typeModels/treeDetails.py
- add config, log_url, arch, compiler and misc platform in tests of Tree Details
Close #771 
Part of #770
=> Feat: Add invisible fiels in tree details tests

dashboard/src/hooks/useTreeDetailsLazyLoadQuery.ts, dashboard/src/pages/TreeDetails/TreeDetails.tsx
- Added `common` object to `TreeDetailsLazyLoaded` type with `isAllReady`
and `isAnyLoading` properties.
- Updated `useTreeDetailsLazyLoadQuery` hook to compute `isAllReady` and
`isAnyLoading` values.
- Imported `LoaderCircle` and `LoadingCircle` components in
`TreeDetails.tsx`.
- Display `TreeDetailsFilter` only when data is ready and not loading.
- Show `LoadingCircle` when data is not ready and loading.
=> feat: add loading state to TreeDetails component

backend/kernelCI_app/helpers/treeDetails.py
Closes #785
- Test with no cache (default behavior in development environment)
- Test with cache by changing the `settings.py` file to: 
```python
if DEBUG:
CORS_ALLOWED_ORIGIN_REGEXES = [
r"^http://localhost",  # dashboard dev server
]
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_SSL_REDIRECT = False
SECURE_HSTS_SECONDS = 3600
CACHE_TIMEOUT = 3600
```
=> fix(get-tree-details-data): fix return position

backend/kernelCI_app/helpers/treeDetails.py, backend/kernelCI_app/views/treeCommitsHistory.py, backend/kernelCI_app/views/treeDetailsSummaryView.py, dashboard/src/api/commitHistory.ts, dashboard/src/api/treeDetails.ts, dashboard/src/components/CommitNavigationGraph/CommitNavigationGraph.tsx
A tree in broonie origin have no git url/branch (null field).
In this PR, I remove de validation on frontend to allow the user send a empty git url and git branch to the tree details endpoint, that now returns a error if no data was found.
In the backend, add a logic to search this trees when this fields are null.
- go to any tree and check if the behavior is the same of the staging
- go to broonie origin and search for [mainline master tree](http://localhost:5173/tree?o=broonie&ts=mainline)
Close #729
=> Fix: tree details broonie

backend/kernelCI_app/helpers/treeDetails.py, backend/kernelCI_app/typeModels/treeDetails.py, backend/kernelCI_app/views/treeDetailsSummaryView.py, backend/kernelCI_app/views/treeDetailsView.py, backend/schema.yml, dashboard/src/components/Checkbox/Checkbox.tsx, dashboard/src/pages/TreeDetails/TreeDetails.tsx, dashboard/src/pages/TreeDetails/TreeDetailsFilter.tsx, dashboard/src/types/tree/TreeDetails.tsx
Closes #792 
Continuing from this PR: https://github.com/kernelci/dashboard/pull/826
=> Fix: remove filters extra query

backend/kernelCI_app/typeModels/commonDetails.py, backend/kernelCI_app/typeModels/treeDetails.py, backend/kernelCI_app/urls.py, backend/kernelCI_app/views/hardwareDetailsBootsView.py, backend/kernelCI_app/views/treeDetailsBootsView.py, backend/requests/hardware-details-boots-post.sh, backend/schema.yml
Adds `/hardware/<hardware_name>/boots` endpoint
This endpoint is not being used by the frontend, but you can compare the responses by opening the network tab on the dashboard website, going to a hardware details with boots data, checking the request body for the post to hardwareDetails endpoint and use that body in a request from the api view. Check if filters and tree selection work normally.
Example: go to localhost:8000/api/hardware/brcm,bcm2711/boots and send the body
```
{
"origin":"maestro",
"startTimestampInSeconds":1737487800,
"endTimestampInSeconds":1737574200,
"selectedCommits":{},
"filter":{}
}
```
in the POST request
Part of #751 
Closes #761
=> feat: add hardwareDetailsBoots endpoint

backend/kernelCI_app/helpers/hardwareDetails.py, backend/kernelCI_app/typeModels/hardwareDetails.py, backend/kernelCI_app/typeModels/treeDetails.py, backend/kernelCI_app/urls.py, backend/kernelCI_app/views/hardwareDetailsBuildsView.py, backend/kernelCI_app/views/treeDetailsBuildsView.py, backend/requests/hardware-details-builds-post.sh, backend/requests/tree-details-builds-get.sh, backend/schema.yml
- Added HardwareDetailsBuilds view
- Added '/api/hardware/<str:hardware_id>/builds/'
- Added the necessary types and changed the location of some types
- Changed the imports and names of some types for TreeDetailsBuilds
Closes #760
- Run the appropriate script in requests (since it's not implemented in the frontend yet) or try sending a request using `httpie`. The corresponding script for this endpoint is in `backend/requests/hardware-details-builds-post.sh`. Make sure to run it with bash or zsh (even though the file format is sh)
```sh
bash backend/requests/hardware-details-builds-post.sh
```
=> feat(api): add hardware details builds endpoint

dashboard/src/api/hardwareDetails.ts, dashboard/src/components/BootsTable/BootsTable.tsx, dashboard/src/components/DetailsPages/SectionError.tsx, dashboard/src/components/QuerySwitcher/QuerySwitcher.tsx, dashboard/src/components/TestsTable/TestsTable.tsx, dashboard/src/hooks/useHardwareDetailsLazyLoadQuery.ts, dashboard/src/pages/hardwareDetails/HardwareDetails.tsx, dashboard/src/pages/hardwareDetails/HardwareDetailsFilter.tsx, dashboard/src/pages/hardwareDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/hardwareDetails/Tabs/Build/BuildTab.tsx, dashboard/src/pages/hardwareDetails/Tabs/Build/HardwareDetailsBuildsTable.tsx, dashboard/src/pages/hardwareDetails/Tabs/HardwareDetailsTabs.tsx, dashboard/src/pages/hardwareDetails/Tabs/HardwareDetailsTabsQuerySwitcher.tsx, dashboard/src/pages/hardwareDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/types/hardware/hardwareDetails.ts
Adds a lazy load to hardwareDetails data, fetching the summary data first, and then the full data.
- Adds variants to `useHardwareDetails` and `fetchHardwareDetails`
- Adds the hook `useHardwareDetailsLazyLoaded`
- Adds HardwareDetailsTabsQuerySwitcher component to be reused between hardwareDetails tabs
- Refactors some of the tables to accept undefined data
- Changes HardwareDetailsFilters to use the response from the summary data instead of the full data
Go to a hardwareDetails page with the network dev tools tab open and see that it will fetch the summary data first, load it, and then fetch the full data and load that.
Closes #758
=> Feat: hardwareDetails lazy load

backend/kernelCI_app/helpers/hardwareDetails.py, backend/kernelCI_app/views/hardwareDetailsSummaryView.py, backend/kernelCI_app/views/hardwareDetailsView.py, dashboard/src/components/Cards/CompatibleHardware.tsx, dashboard/src/pages/hardwareDetails/HardwareDetails.tsx
- Add filter for compatibles card in hardware details
- Remove the hardware id of the page from compatibles card
Closes #712
From my experience, most of the hardwares have tests that share the same environment_compatible array. For that reason, is kind of hard to find a hardware detail where the filter has an effect. This is one of them: http://localhost:5173/hardware/amlogic%2Cg12b?et=1737981000&p=bt&st=1737549000. In this example, we have two different sets of tests, one where the environment_compatible includes `libretech,aml-a311d-cc` and the other where environment_compatible includes `khadas,vim3`. Testing in this page would go:
- Filter by `libretech,aml-a311d-cc`. Save the status values for later and verify that all the boots/tests have `libretech/aml-a311d-cc` in the hardware …
=> feat(hardware-details): add compatibles filter

dashboard/src/components/Cards/IssuesList.tsx, dashboard/src/components/Issue/IssueSection.tsx, dashboard/src/components/Issue/IssueTooltip.tsx, dashboard/src/locales/messages/index.ts
Adds a tooltip for issues for better explanation of what they are.
- Adds a IssueTooltip component
- Adds the tooltip on IssuesList and IssueSection
Go to a treeDetails or hardwareDetails page and see the tooltip on the "Issues" card (even when there are no issues the card is still shown)
Go to a buildDetails or testDetails page and see the tooltip on the "Issues" section (only shows if the section is shown, such as http://localhost:5173/test/redhat%3A1638594222-x86_64-kernel_upt_9 )
Closes #822
Closes #800
=> feat: add Issue tooltip

dashboard/src/api/hardwareDetails.ts, dashboard/src/pages/hardwareDetails/HardwareDetails.tsx, dashboard/src/pages/hardwareDetails/HardwareDetailsHeaderTable.tsx, dashboard/src/utils/utils.ts
Added a new state `treeIndexesLength` that keep track of the size of number of trees there are in the header table. This was necessary because the backend expects a object that maps each tree index to its respective selected commit, but it couldn't correctly get all the tree indexes from the query parameter since it defaults to an empty array when all trees are selected. This state is then used when the query param is an empty array to create this object
Closes #783 
This hardware is a good one for testing: [google,kingoftown](http://localhost:5173/hardware/google%2Ckingoftown?et=1738087200&st=1737655200), specially the `mainline/master` branch that has a lot of commits and different values between them. 
- Try to change the commits and see if the status in the header table change …
=> Fix: hardware commit selector

backend/kernelCI_app/helpers/commonDetails.py, backend/kernelCI_app/helpers/hardwareDetails.py, backend/kernelCI_app/helpers/treeDetails.py, backend/kernelCI_app/typeModels/commonDetails.py, backend/kernelCI_app/typeModels/hardwareDetails.py, backend/kernelCI_app/typeModels/treeDetails.py, backend/kernelCI_app/views/hardwareDetailsSummaryView.py, backend/kernelCI_app/views/hardwareDetailsView.py, backend/schema.yml, dashboard/src/api/hardwareDetails.ts, dashboard/src/hooks/useHardwareDetailsLazyLoadQuery.ts, dashboard/src/locales/messages/index.ts, dashboard/src/pages/hardwareDetails/HardwareDetails.tsx, dashboard/src/pages/hardwareDetails/HardwareDetailsFilter.tsx, dashboard/src/pages/hardwareDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/hardwareDetails/Tabs/Build/BuildTab.tsx, dashboard/src/pages/hardwareDetails/Tabs/HardwareCommitNavigationGraph.tsx, dashboard/src/pages/hardwareDetails/Tabs/HardwareDetailsTabs.tsx, dashboard/src/pages/hardwareDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/types/commonDetails.ts, dashboard/src/types/general.ts, dashboard/src/types/hardware/hardwareDetails.ts, dashboard/src/types/tree/TreeDetails.tsx
Splits the summary response to summary/filters/common
Adds platforms as another field for unfiltered filters
Adds compatibles to the filter modal
- Go to a hardwareDetails page that has more than one value of any property (more than one config or arch or compiler or platform, etc.), such as amlogic,a311d (2 boot platforms) or google,juniper (2 configs) or fsl,imx6q (2 boot platforms, 2 boot issues)
- Filter by one of those values
- See in the filter modal that the other value is still shown there
Closes #799
=> Feat: change summary response for hardwareDetails

backend/kernelCI_app/helpers/commonDetails.py, backend/kernelCI_app/helpers/filters.py, backend/kernelCI_app/helpers/hardwareDetails.py, backend/kernelCI_app/helpers/treeDetails.py, backend/kernelCI_app/typeModels/commonDetails.py, backend/kernelCI_app/typeModels/hardwareDetails.py, backend/kernelCI_app/unitTests/treeDetails.test.py, backend/kernelCI_app/views/treeCommitsHistory.py, dashboard/src/components/Cards/IssuesList.tsx, dashboard/src/components/Tabs/Filters.tsx, dashboard/src/pages/TreeDetails/TreeDetailsFilter.tsx, dashboard/src/pages/hardwareDetails/HardwareDetailsFilter.tsx, dashboard/src/types/commonDetails.ts, dashboard/src/utils/utils.ts
Use issue version to filter the builds/tests data from Tree and Hardware Details. Change the issue label to `issue_id v.issue_version` insteand only `issue_id`. Example: `maestro:1bad4fd734ada1f413164870f3d66961f9eccbfb v.1`
Close #739
Go to any Tree or Hardware and try apply the filter by issue. Observe if the behavior is the same for the staging. See the examples below:
- [android-mainline](http://localhost:5173/tree/5f191bee6f942c90bc33ed2ab9b9343761ed1149?df%7Cbi%7Cmaestro%3A1bad4fd734ada1f413164870f3d66961f9eccbfb%20v.1=true&ti%7Cc=ASB-2025-01-05_mainline-493-g5f191bee6f94&ti%7Cch=5f191bee6f942c90bc33ed2ab9b9343761ed1149&ti%7Cgb=android-mainline&ti%7Cgu=https%3A%2F%2Fandroid.googlesource.com%2Fkernel%2Fcommon&ti%7Ct=android)
- …
=> Feat: filter by issue version

dashboard/src/components/TestsTable/IndividualTestsTable.tsx, dashboard/src/components/TestsTable/TestsTable.tsx, dashboard/src/pages/TreeDetails/Tabs/WrapperTableWithLogSheet.tsx
- Removes memo with no dependencies from IndividualTestsTable, allowing it to update when the data updates and also makes it follow the pattern of other tables.
- Changes a slight style problem where the expanded rows from a TestsTable would have a small gap bellow them
- Adds [useful row ids](https://tanstack.com/table/latest/docs/guide/row-selection#useful-row-ids) to TestsTable, allowing the expanded state to be tied to the `path_group` instead of the row index
These fixes are applied to the base TestsTable and IndividualTestsTable, meaning it will be spread through any page that uses those tables (treeDetails tests tab, hardwareDetails tests tab, buildDetails and issueDetails). Since no other table is expandable anymore, other tables don't suffer from these problems.
For the filter …
=> Fix: filter expanded rows

backend/kernelCI_app/helpers/hardwareDetails.py, backend/kernelCI_app/helpers/treeDetails.py, backend/kernelCI_app/typeModels/buildDetails.py, backend/kernelCI_app/typeModels/commonDetails.py, backend/kernelCI_app/typeModels/databases.py, backend/kernelCI_app/typeModels/issueDetails.py, backend/kernelCI_app/views/buildTestsView.py, backend/kernelCI_app/views/issueDetailsTestsView.py, backend/requests/build-tests-get.sh, backend/requests/issue-details-tests-get.sh, backend/schema.yml, dashboard/src/components/BootsTable/BootsTable.tsx, dashboard/src/components/Table/TooltipHardware.tsx, dashboard/src/components/TestsTable/TestsTable.tsx, dashboard/src/types/general.ts, dashboard/src/utils/table.ts
- Show platform first and enviroment_compatible in the hover if it exists. Show only environment_compatible if platform is undefined
- Go to a tree details page and verify that the hardware priority is working correctly (to ensure that the tooltip is working you can filter for a hardware and check if the tooltip shows)
- Do the same in a build details page. In this case you can open one of the tests and check if the platform is the one showing in the table and if the tooltip is correctly showing the environment_compatible (field "hardware" in test details) ou showing nothing if hardware is "Unknown"
- Do the same in an issue details page. To quickly find an issue details page with tests you can go to a boots tab with issues and open one of the issues there.
Closes #864
=> feat: change hardware priority in tests table

dashboard/src/components/Table/PaginationInfo.tsx, dashboard/src/components/TreeListingPage/InputTime.tsx, dashboard/src/components/TreeListingPage/TreeTable.tsx, dashboard/src/hooks/usePaginationState.tsx, dashboard/src/pages/Hardware/HardwareTable.tsx, dashboard/src/pages/treeConstants.ts, dashboard/src/routes/(alternatives)/t/route.tsx, dashboard/src/routes/build/$buildId/route.tsx, dashboard/src/routes/hardware/route.tsx, dashboard/src/routes/index.tsx, dashboard/src/routes/issue/$issueId/route.tsx, dashboard/src/routes/test/$testId/route.tsx, dashboard/src/routes/tree/route.tsx, dashboard/src/types/general.ts, dashboard/src/utils/constants/general.ts, dashboard/src/utils/search.ts
Add `listingSize` parameter to tree and hardware listing. The alias to this param is `ls`.
1. Go to tree listing or hardware listing
2. On the URL, append the `ls` parameter
-  http://localhost:5173/tree?ls=13
-  http://localhost:5173/tree?ts=android&ls=13
3. See that the page number is the next decade. If you give `ls=13`, the page size will be 20. The max page size is 50.
Close #860
=> Feat: add size listing parameter

dashboard/src/components/TestsTable/TestsTable.tsx
Filter by the path of every individual test when `updatePathFilter` is undefined
Closes #875
- Ensure that the behavior of the tests table in Tree Details and Hardware Details are the same. Since they use `updatePathFilter` there shouldn't be any differences from the version on staging. However, they are still influenced by this implementation since all of the status counting is done in the filteredData `useMemo`.
- Check if the tests tables in other pages (issue details and build details) can correctly filter by path now. In maestro, issue details generally have only one test group (boot) so it's recommended to test on build details or test in an issue details from redhat, for example, http://localhost:5173/issue/redhat%3Aissue_3137
=> fix(tests-table): filter by individual table path

backend/kernelCI_app/typeModels/databases.py, backend/kernelCI_app/typeModels/issuesView.py, backend/kernelCI_app/typeModels/logDownloader.py, backend/kernelCI_app/typeModels/testDetails.py, backend/kernelCI_app/typeModels/treeCommits.py, backend/kernelCI_app/views/issuesView.py, backend/kernelCI_app/views/logDownloaderView.py, backend/kernelCI_app/views/testDetailsView.py, backend/kernelCI_app/views/treeCommitsHistory.py, backend/requests/test-details-get.sh, backend/schema.yml, dashboard/src/api/commitHistory.ts, dashboard/src/components/CommitNavigationGraph/CommitNavigationGraph.tsx, dashboard/src/types/tree/TreeDetails.tsx
- Added documentation and response validation
- Changed from raw query to django ORM
- Updated the requests file
- Updated endpoint response (87e409daa8f4dc13d4ea54a7163eab58a5b506cb)
- Added documentation and response validation (3351774380de5a4299a45fc4d668545c6853768c)
Part of #86
- Verify that the endpoint is showing correctly in the documentation (path params, query params, response, etc.)
- Verify that the validations added didn't break anything on the application
=> Feat: Add swagger docs to some endpoints

backend/kernelCI_app/helpers/date.py, backend/kernelCI_app/typeModels/hardwareListing.py, backend/kernelCI_app/views/hardwareView.py, backend/schema.yml, dashboard/src/locales/messages/index.ts, dashboard/src/pages/Hardware/HardwareListingPage.tsx, dashboard/src/pages/Hardware/HardwareTable.tsx, dashboard/src/types/hardware.ts
- List hardware that is not an environment_compatible but has platform
- Add platform column to the hardware listing 
- Add swagger documentation
Closes #867 #887
Go to the hardware listing page and try to enter in a hardware details page that has the same repeat the process.
=> feat(hardware-listing): add non compatibles platforms

backend/kernelCI_app/typeModels/hardwareDetails.py, backend/kernelCI_app/typeModels/issueDetails.py, backend/kernelCI_app/typeModels/treeDetails.py, backend/kernelCI_app/views/hardwareDetailsCommitHistoryView.py, backend/kernelCI_app/views/treeDetailsSummaryView.py, backend/requests/issue-details-tests-get.sh, backend/schema.yml
- Added documentation to /hardware/{hardware_id}/commit-history
- Did some small fixes in other endpoints documentations
Part of #86
Closes #888
=> feat(api): add hardware commit history docs

backend/kernelCI_app/helpers/issueExtras.py, backend/kernelCI_app/typeModels/issues.py, backend/kernelCI_app/urls.py, backend/kernelCI_app/utils.py, backend/kernelCI_app/views/issueDetailsView.py, backend/kernelCI_app/views/issueExtrasView.py, backend/requests/issue-extras-post.sh, backend/schema.yml
- Adds a new endpoint to get the detailed information of a list of issues (id and version)
- Adds query to get the timestamp of the first incident of an issue
- Adds query to get the trees where that issue_id and issue_version have had incidents
- The list of trees is also used to add specific tags to the issues
Acquire a list of issues that you want to get more details from, then go to `http://localhost:5173/issues/extras/` and in the swagger UI you can place a body for the request, such as:
```
{
"issues": [
["maestro:e602fca280d85d8e603f7c0aff68363bb0cd7993", 1],
["maestro:da694c56147298d223ee432ad8d6a8ee311b773a", 1]
]
}
```
You can verify if the trees are coming correctly for an issue by running the following query (change the issue id and version at the end):
```
SELECT DISTINCT
ON …
```
=> Feat: add treeIssues endpoint and detailed issues info

backend/kernelCI_app/typeModels/treeCommits.py, backend/kernelCI_app/views/treeCommitsHistory.py, dashboard/src/components/CommitNavigationGraph/CommitNavigationGraph.tsx, dashboard/src/components/Tooltip/CommitTagTooltip.tsx, dashboard/src/types/tree/TreeDetails.tsx
=> Feat: show tag in history chart x axis

dashboard/src/api/issueDetails.ts, dashboard/src/components/IssueDetails/IssueDetailsBuildSection.tsx, dashboard/src/components/IssueDetails/IssueDetailsTestSection.tsx
If a issue has no builds or tests data (xor), hidden the card section in issue details
Close #897
=> feat(dashbord): hidden issue details sections

backend/kernelCI_app/views/treeView.py, dashboard/src/components/TreeListingPage/TreeTable.tsx
Tree listing was receiving wrong null counts for its trees, this fix
it and by consequence fix the cache invalidation
Keep alternating between tree listing and tree details and see that there are no extra queries
Closes #886
=> fix:extra queries

dashboard/src/components/BuildDetails/BuildDetails.tsx, dashboard/src/components/Icons/StatusIcons.tsx, dashboard/src/components/Section/LogspecSection.tsx, dashboard/src/components/Section/Section.tsx, dashboard/src/components/Section/SectionGroup.tsx, dashboard/src/components/TestDetails/TestDetails.tsx, dashboard/src/types/tree/TestDetails.tsx
Closes #895
Pass
http://localhost:5173/test/maestro%3A67aa5897b27a1f56cc36ee53?ls=10&p=t&ti%7Cc=v6.9-12136-gf5d74f9f7c3b&ti%7Cch=f5d74f9f7c3b2495596b43c01f5747b66c8ef70d&ti%7Cgb=nvme-rx-offload-v25&ti%7Cgu=https%3A%2F%2Fgithub.com%2Faaptel%2Flinux.git&ti%7Ct=aaptel
Fail
http://localhost:5173/test/maestro%3A67a861e8661a7bc874947206?et=1739214000&iv=1&p=bt&st=1738782000&tf%7Cb=a&tf%7Cbt=f&tf%7Ct=a
Inconclusive
http://localhost:5173/test/maestro%3A67aa5acdb27a1f56cc36f15b?p=t&tf%7Cb=a&tf%7Cbt=a&tf%7Ct=i&ti%7Cc=v6.9-12136-gf5d74f9f7c3b&ti%7Cch=f5d74f9f7c3b2495596b43c01f5747b66c8ef70d&ti%7Cgb=nvme-rx-offload-v25&ti%7Cgu=https%3A%2F%2Fgithub.com%2Faaptel%2Flinux.git&ti%7Ct=aaptel
=> feat: add status icon to details header

backend/kernelCI_app/constants/general.py, backend/kernelCI_app/helpers/commonDetails.py, backend/kernelCI_app/helpers/filters.py, backend/kernelCI_app/helpers/hardwareDetails.py, backend/kernelCI_app/helpers/treeDetails.py, backend/kernelCI_app/typeModels/commonDetails.py, backend/kernelCI_app/unitTests/treeDetails.test.py, backend/kernelCI_app/utils.py, backend/kernelCI_app/views/hardwareDetailsBootsView.py, backend/kernelCI_app/views/hardwareDetailsSummaryView.py, backend/kernelCI_app/views/hardwareDetailsTestsView.py, backend/kernelCI_app/views/hardwareDetailsView.py, backend/kernelCI_app/views/hardwareView.py, backend/kernelCI_app/views/treeCommitsHistory.py, dashboard/src/components/Cards/IssuesList.tsx, dashboard/src/utils/utils.ts
- Renames processed_issues to issue_dicts
- Separates processed_tests from decide_test_in_filter
- Update getIssueFilterLabel to check explicitly for undefined
- Update key prop from IssuesList div to include issue version
Closes #872 
You can verify that filtering by issues in [this localhost page](http://localhost:5173/hardware/google%2Ctomato-rev2?et=1738602000&hs=tomato-rev2&p=bt&st=1738170000) is working properly, while [staging page](https://staging.dashboard.kernelci.org:9000/hardware/google%2Ctomato-rev2?et=1738602000&hs=tomato-rev2&p=bt&st=1738170000) is showing the problems cited in the issue (issues list not showing all issues, filtering by the unlisted issues through the modal causing errors, etc.) 
While testing this I found out a seemingly unrelated problem with this task, …
=> Fix: issuesList counting

dashboard/src/api/buildDetails.ts, dashboard/src/api/issueDetails.ts, dashboard/src/api/issueExtras.ts, dashboard/src/api/testDetails.ts, dashboard/src/components/Cards/IssuesList.tsx, dashboard/src/components/Issue/IssueSection.tsx, dashboard/src/components/IssueDetails/IssueDetails.tsx, dashboard/src/components/ListingItem/ListingItem.tsx, dashboard/src/components/Sheet/LogOrJsonSheetContent.tsx, dashboard/src/components/TooltipDateTime/TooltipDateTime.tsx, dashboard/src/components/ui/badge.tsx, dashboard/src/hooks/useTreeDetailsLazyLoadQuery.ts, dashboard/src/index.css, dashboard/src/locales/messages/index.ts, dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/TreeDetails/Tabs/Build/BuildTab.tsx, dashboard/src/pages/TreeDetails/Tabs/TestCards.tsx, dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/pages/TreeDetails/Tabs/WrapperTableWithLogSheet.tsx, dashboard/src/types/commonDetails.ts, dashboard/src/types/general.ts, dashboard/src/types/issueDetails.ts, dashboard/src/types/issueExtras.ts, dashboard/src/types/issues.ts
- Adds functions to fetch extra issue details
- Use these functions in treeDetailsLazyLoaded (requires summaryData for the request)
- Changes Issue List to occupy 2 columns and changes how it's truncated
- Adds text for first_seen and badges for the tags
Go to any treeDetails that have issues; all of them should have at least the first_seen information, the tags are optional and depend on each issue in particular.
Examples are [sashal-next/linus-next](http://localhost:5173/tree/133cb6f592c89e07f15c93d41f1c410e0bfb93d1?p=bt&ti%7Cc=v6.14-rc2-76-g133cb6f592c8&ti%7Cch=133cb6f592c89e07f15c93d41f1c410e0bfb93d1&ti%7Cgb=linus-next&ti%7Cgu=https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Fsashal%2Flinus-next.git&ti%7Ct=sashal-next), …
=> Feat: show issueExtraDetails data on treeDetails

backend/kernelCI_app/helpers/issueExtras.py, backend/kernelCI_app/typeModels/commonDetails.py, backend/kernelCI_app/typeModels/databases.py, backend/kernelCI_app/typeModels/issues.py, backend/schema.yml, dashboard/src/api/issueExtras.ts, dashboard/src/components/Cards/IssuesList.tsx, dashboard/src/components/ui/badge.tsx, dashboard/src/index.css, dashboard/src/locales/messages/index.ts, dashboard/src/types/issueExtras.ts
- Changed the issuesExtra response to include more info about the first incident of each issue, including commit hash, git branch and git url
- Added the pill to the issue list if the commit hash of the first incident is the same commit hash of the tree details page
Closes #571
You can verify if an issue is really new if when you open its issue details there's only one test/build
http://localhost:5173/tree/f5d74f9f7c3b2495596b43c01f5747b66c8ef70d?ti%7Cc=v6.9-12136-gf5d74f9f7c3b&ti%7Cch=f5d74f9f7c3b2495596b43c01f5747b66c8ef70d&ti%7Cgb=nvme-rx-offload-v25&ti%7Cgu=https%3A%2F%2Fgithub.com%2Faaptel%2Flinux.git&ti%7Ct=aaptel
http://localhost:5173/tree/4dc1d1bec89864d8076e5ab314f86f46442bfb02?iv=1&p=bt&ti%7Cc=v6.14-rc2-41-g4dc1d1bec8986&ti%7Cch=4dc1d1bec89864d8076e5ab314f86f46442bfb02&ti%7Cgb=ma …
=> feat(issues-list): add tag 'new'

dashboard/src/components/TreeListingPage/TreeListingPage.tsx, dashboard/src/lib/string.ts, dashboard/src/locales/messages/index.ts, dashboard/src/pages/Hardware/HardwareListingPage.tsx
- Updated TreeListingPage to use matchesRegexOrIncludes for filtering.
- Updated HardwareListingPage to use matchesRegexOrIncludes and
includesInAnStringOrStringArray for filtering.
functions to string utility library.
Closes #913
Just use a regex on the search bars or click on the link below
http://localhost:5173/tree?ls=50&ts=android%7Cbroonie%7Cmainline
=> feat: add regex support to tree and hardware filters

backend/kernelCI_app/constants/general.py, backend/kernelCI_app/helpers/commonDetails.py, backend/kernelCI_app/helpers/filters.py, backend/kernelCI_app/helpers/hardwareDetails.py, backend/kernelCI_app/helpers/treeDetails.py, backend/kernelCI_app/typeModels/commonDetails.py, backend/kernelCI_app/views/hardwareDetailsSummaryView.py, backend/kernelCI_app/views/hardwareDetailsView.py, backend/kernelCI_app/views/treeCommitsHistory.py, backend/kernelCI_app/views/treeDetailsSummaryView.py, backend/kernelCI_app/views/treeDetailsView.py, backend/schema.yml, dashboard/src/components/Cards/IssuesList.tsx, dashboard/src/components/Tabs/Filters.tsx, dashboard/src/locales/messages/index.ts, dashboard/src/pages/TreeDetails/TreeDetailsFilter.tsx, dashboard/src/pages/hardwareDetails/HardwareDetailsFilter.tsx, dashboard/src/types/commonDetails.ts, dashboard/src/utils/constants/backend.ts
- Renames Unknown issues to Uncategorized issues
- Changes the behavior of the filters to return a flag for if it has uncategorized issues, instead of considering them as a normal issue
- Refactors TreeDetailsView and TreeDetailsSummaryView to use pydantic models directly
Go to a tree or hardware details page where there are builds/boots/tests with uncategorized issues
Filter them through the issues list and through the filter modal
Check if everything is being filtered as intended
Closes #910
=> Refactor: Change issues from unknown to uncategorized

backend/kernelCI/settings.py
The current API is not 1.0 yet, so it gives the users wrong impression
Closes #945
=> fix: swagger version

dashboard/src/pages/hardwareDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/hardwareDetails/Tabs/Build/BuildTab.tsx, dashboard/src/pages/hardwareDetails/Tabs/Tests/TestsTab.tsx
Moves the order of the issue list card so that it can occupy 2 columns on hardwareDetails, following the changes for the treeDetails
[Before](https://staging.dashboard.kernelci.org:9000/hardware/aaeon-UPN-EHLX4RE-A10-0864?et=1739556000&p=bt&st=1739124000):
[After](http://localhost:5173/hardware/aaeon-UPN-EHLX4RE-A10-0864?et=1739556000&p=bt&st=1739124000):
Closes #944
=> Fix: issue list size on hardware details

dashboard/src/components/BootsTable/BootsTable.tsx, dashboard/src/components/BuildDetails/BuildDetails.tsx, dashboard/src/components/BuildDetails/BuildDetailsTestSection.tsx, dashboard/src/components/BuildsTable/BuildsTable.tsx, dashboard/src/components/BuildsTable/DefaultBuildsColumns.tsx, dashboard/src/components/IssueDetails/IssueDetails.tsx, dashboard/src/components/IssueDetails/IssueDetailsBuildSection.tsx, dashboard/src/components/IssueDetails/IssueDetailsTestSection.tsx, dashboard/src/components/Table/TableStatusFilter.tsx, dashboard/src/components/TestsTable/TestsTable.tsx, dashboard/src/components/TreeListingPage/TreeTable.tsx, dashboard/src/pages/BuildDetails/BuildDetails.tsx, dashboard/src/pages/HardwareBuildDetails/HardwareBuildDetails.tsx, dashboard/src/pages/IssueDetails/IssueDetails.tsx, dashboard/src/pages/TreeBuildDetails/TreeBuildDetails.tsx, dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/TreeDetails/Tabs/Build/TreeDetailsBuildsTable.tsx, dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/pages/hardwareDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/hardwareDetails/Tabs/Boots/HardwareDetailsBootsTable.tsx, dashboard/src/pages/hardwareDetails/Tabs/Build/HardwareDetailsBuildsTable.tsx, dashboard/src/pages/hardwareDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/types/tree/TreeDetails.tsx, dashboard/src/utils/search.ts, dashboard/src/utils/status.ts, dashboard/src/utils/utils.ts
This change is only for the status display in the builds table and build details, the variables are still called valid since that is how it is called in the backend.
The name in the diffFilter was left unchanged, but the table filter was unified with the way it is being done in the other tables
Go to a buildDetails page and check the change in the "status" field.
Go to a page with a build table (such as treeDetails, hardwareDetails or issueDetails) and check the table to see if it is behaving correctly, also check the status filters.
Try to filter by build status and check if it is behaving correctly, also check the url to see if it is called by the correct name.
Closes #922
=> Refactor: rename build valid/invalid to pass/fail

dashboard/src/components/ColoredCircle/ColoredCircle.tsx, dashboard/src/components/Status/Status.tsx
Colored circles should have a lower opacity when the count is 0, even for successful circles.
This makes it easier to see when there are many 0s in a page while also knowing that there are 0s in that page
Before:
After:
Closes #954
=> Fix: colored circle opacity

backend/kernelCI_app/helpers/hardwareDetails.py, backend/kernelCI_app/helpers/treeDetails.py, dashboard/src/components/Cards/IssuesList.tsx
Sort the issues list card by the first_seen value of each issue in descending order, in other words, the newest versions (that have the "greatest" timestamp) will appear first in the list
Closes #940
[localhost](http://localhost:5173/tree/0ad2507d5d93f39619fc42372c347d6006b64319?p=bt&ti%7Cc=v6.14-rc3&ti%7Cch=0ad2507d5d93f39619fc42372c347d6006b64319&ti%7Cgb=master&ti%7Cgu=https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Ftorvalds%2Flinux.git&ti%7Ct=mainline)
[staging](https://staging.dashboard.kernelci.org:9000/tree/0ad2507d5d93f39619fc42372c347d6006b64319?p=bt&ti%7Cc=v6.14-rc3&ti%7Cch=0ad2507d5d93f39619fc42372c347d6006b64319&ti%7Cgb=master&ti%7Cgu=https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Ftorvalds%2Flinux.git&ti%7Ct=mainline) …
=> feat(issues-list): sort by first_seen

backend/kernelCI_app/helpers/database.py, backend/kernelCI_app/typeModels/hardwareListing.py, backend/kernelCI_app/views/hardwareView.py
Refactor the hardware view to use raw SQL queries for fetching test
data, replacing the ORM-based approach. This change improves
performance by reducing the number of database queries and leveraging
SQL's capabilities for complex data aggregation.
- Add `dict_fetchall` helper function to convert cursor results to dict
- Update `HardwareItem` and `HardwareResponse` models to use Pydantic
- Remove unused imports and functions from `hardwareView.py`
- Run the project
- Go to http://localhost:5173/hardware
- And see if the data is the same that is in https://staging.dashboard.kernelci.org:9000/hardware
- Also, check the loading tab in the network tab and see how it doesn't take more than 5 seconds now (sometimes even less than 3)
Closes #937
=> feat: new hardware listing query

dashboard/src/components/BuildDetails/BuildDetails.tsx, dashboard/src/components/TestDetails/TestDetails.tsx, dashboard/src/routes/build/$buildId/route.tsx, dashboard/src/routes/test/$testId/route.tsx, dashboard/src/types/commonDetails.ts, dashboard/src/types/general.ts, dashboard/src/utils/search.ts
Add a boolean query parameter `logOpen` to both `/build/$buildId` and `/test/$testId` that saves the open state of the log viewer in those pages and open it automatically when the link is open with the parameter set to true
Closes #994 
- Check if the query parameter is correctly set when the log viewer is opened/closed
- Check if the log viewer automatically opens when opening a link with the query parameter set to true
- Check that any non-boolean value will just make the query parameter defaults to `false`
- Check if the alternative routes are working correctly with the new query parameter
=> Feat: log viewer query param

backend/README.md, backend/conftest.py, backend/kernelCI_app/helpers/filters.py, backend/kernelCI_app/unitTests/treeDetailsSummary_test.py, backend/kernelCI_app/unitTests/utils/baseClient.py, backend/kernelCI_app/unitTests/utils/commonTreeAsserts.py, backend/kernelCI_app/unitTests/utils/fields/tree.py, backend/kernelCI_app/unitTests/utils/treeClient.py
Added support for filters to the clients
This is a list of every filter in the application, with everyone implemented or explained why it was left behind: 
```
"boot.status"        -- OK
"boot.duration"      -- Does not apply to tree summary (only tree/hardware details)
"test.status"        -- OK
"test.duration"      -- Does not apply to tree summary (only tree/hardware details)
"duration"           -- Does not apply to tree summary (only tree/hardware details)
"config_name"        -- OK
"compiler"           -- OK
"architecture"       -- OK
"valid"              -- OK
"test.hardware"      -- OK
"test.path"          -- Does not apply to tree summary (only tree/hardware details)
"boot.path"          -- Does not apply to tree summary (only tree/hardware details)
"build.issue"        -- In …
```
=> Test: tree details summary

backend/kernelCI_app/typeModels/commonDetails.py
Fixes a bug that buildDetails wasn't fetching the misc field because of a type validator
=> Fix: allow dict misc field

backend/kernelCI_app/apps.py, backend/kernelCI_app/cache.py
Closes #999 
Closes #1025
I think that currently the best way to test is to run our `generate-schema.sh` script and check that it exits correctly. Another option would be to create a new admin command (for example https://github.com/padovan/dashboard/commits/dev/), run it and check it's exiting correctly
=> fix: remove unused cache functions

backend/kernelCI_app/queries/test.py, backend/kernelCI_app/typeModels/testDetails.py, backend/kernelCI_app/unitTests/issues_test.py, backend/kernelCI_app/unitTests/utils/fields/tests.py, backend/kernelCI_app/views/testDetailsView.py, backend/requests/tree-details-get.sh, backend/schema.yml, dashboard/src/components/Icons/TooltipIcon.tsx, dashboard/src/components/Issue/IssueTooltip.tsx, dashboard/src/components/Section/Section.tsx, dashboard/src/components/Table/TableHeader.tsx, dashboard/src/components/TestDetails/StatusHistoryItem.tsx, dashboard/src/components/TestDetails/TestDetails.tsx, dashboard/src/locales/messages/index.ts, dashboard/src/types/tree/TestDetails.tsx
Adds a new query to get the history of a test
Adds a method to tell if a given test is a regression, is fixed, or is unstable
Fetch test endpoints with `http 'localhost:8000/api/test/<test_id>` and check if the history is getting fetched and the classification is correct. You can also check the network tab when going to a test details page to check the response.
For the frontend, go to any testDetails page and check the Status History section, some examples:
[Test with 1 pass](http://localhost:5173/test/maestro%3A67c173ff3218f15c74bc5c79)
[Test with 1 fail](http://localhost:5173/test/maestro%3A67c074b57d9799de2b4ce46d)
[Test with 1 inconclusive](http://localhost:5173/test/maestro%3A67c17c8b3218f15c74bc68bd)
[Unstable test](http://localhost:5173/test/maestro%3A678ee7b046f65f378a18d33e) …
=> Feat: add test status history to test details

dashboard/src/components/Section/Section.tsx
Fixes a border between the subsections of the buildDetails while keeping the spacing between sections, especially sections without items like the test status history in testDetails
Compare the localhost and staging of build details and test details. Examples:
buildDetails [localhost](http://localhost:5173/build/maestro%3A67c8a97d18018371956cfde3) and [staging](https://staging.dashboard.kernelci.org:9000/build/maestro%3A67c8a97d18018371956cfde3)
testDetails [localhost](http://localhost:5173/test/maestro%3A67c186b93218f15c74bcbf43) and [staging](https://staging.dashboard.kernelci.org:9000/test/maestro%3A67c186b93218f15c74bcbf43)
issueDetails [localhost](http://localhost:5173/issue/maestro%3A2ff8fe94f6d53f39321d4a37fe15801cedc93573?iv=1) and …
=> Fix: buildDetails section style

backend/kernelCI_app/queries/test.py, backend/kernelCI_app/views/testDetailsView.py
Fixes test details pages where there is no environment misc to extract the platform, which were crashing because of the status history filter
Example: http://localhost:5173/test/redhat%3A1575003976-x86_64-kernel_upt_1
Compare it with the same page on staging: https://staging.dashboard.kernelci.org:9000/test/redhat%3A1575003976-x86_64-kernel_upt_1
=> Fix: test details without env misc

backend/README.md, backend/kernelCI_app/helpers/discordWebhook.py, backend/kernelCI_app/helpers/logger.py, backend/kernelCI_app/views/buildTestsView.py, docker-compose.yml
Adds helper functions to send messages using a discord webhook
Get a discord webhook url, by going to discord server settings, creating or viewing a webhook and copying its URL
Set the environment variable `DISCORD_WEBHOOK_URL` with the url of your webhook (should look something like `https://discord.com/api/webhooks/<id>/<webhook_id>`)
Currently there is only a notification for failed builds that had tests, such as this [localhost buildDetails](http://localhost:5173/build/maestro:67c8a01118018371956c8c4b)
Closes #1027
=> Feat: add discord webhook helpers

backend/data/trees-name.yaml, backend/kernelCI/settings.py, backend/kernelCI_app/management/commands/treeproof.py
- create admin command to make a file with trees of all origin (focus in maestro trees)
- create a initial file with the trees
Close #1015
- Drop `kernelCI_app/management/commands/data/tree-proof.yml` file
- Run the command `poetry run python3 manage.py treeproof`
- See that it's generate a new `tree-proof.yml`
=> Chore: logic to construct tree proof file

backend/kernelCI_app/queries/test.py, backend/kernelCI_app/typeModels/testDetails.py, backend/kernelCI_app/unitTests/testStatusHistory_test.py, backend/kernelCI_app/unitTests/utils/fields/tests.py, backend/kernelCI_app/views/testStatusHistoryView.py, backend/requests/test-details-get.sh, backend/requests/test-status-history-get.sh, backend/schema.yml, dashboard/src/components/TestDetails/StatusHistoryItem.tsx, dashboard/src/components/TestDetails/TestDetails.tsx, dashboard/src/locales/messages/index.ts, dashboard/src/types/tree/TestDetails.tsx
Changes backend query to also consider the build config as a part of a test definition; also uses `start_time` instead of `_timestamp` for filtering and ordering.
Changes frontend to be more visible and clearer in the informations - increased icon size, current test indicator, explicit regression type tooltip.
Changes the way the reverse status history icons are calculated, fixing a bug where it was reverting the already reversed array.
Go to any test details pages and compare with staging.
Localhost examples:
[Regression test](http://localhost:5173/test/maestro:67ce445218018371957db690)
[Fixed test](http://localhost:5173/test/maestro%3A67c8eddd18018371956edb3d)
[Unstable test](http://localhost:5173/test/maestro:67cf61dec5336ecbf369c77e) - This one also has a "crossed" timestamp x start …
=> Feat: status history improvements

dashboard/src/components/BuildDetails/BuildDetails.tsx, dashboard/src/components/Cards/IssuesList.tsx, dashboard/src/components/Issue/IssueSection.tsx, dashboard/src/components/IssueTable/IssueTable.tsx, dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/TreeDetails/Tabs/Build/TreeDetailsBuildsTable.tsx, dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/pages/hardwareDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/hardwareDetails/Tabs/Build/HardwareDetailsBuildsTable.tsx, dashboard/src/pages/hardwareDetails/Tabs/Tests/HardwareDetailsTestsTable.tsx, dashboard/src/routes/_main/issue/$issueId/route.tsx
After removing some of the search params from the details pages one essential search param `origin` was removed as well. This commit fixes this problem, sending again the `origin` param to build/test/issue details
Closes #1043
Please check that every link to an issue/test/build details correctly passes the `origin` param. I've tested it myself but I might have missed something
=> fix: pass origin to build/test/issue details

backend/kernelCI/settings.py, backend/kernelCI_app/middleware/logServerErrorMiddleware.py, backend/kernelCI_app/views/hardwareDetailsBootsView.py, backend/kernelCI_app/views/hardwareDetailsBuildsView.py, backend/kernelCI_app/views/hardwareDetailsSummaryView.py, backend/kernelCI_app/views/hardwareDetailsTestsView.py, backend/kernelCI_app/views/hardwareDetailsView.py, backend/kernelCI_app/views/treeDetailsBootsView.py, backend/kernelCI_app/views/treeDetailsBuildsView.py, backend/kernelCI_app/views/treeDetailsSummaryView.py, backend/kernelCI_app/views/treeDetailsTestsView.py, backend/kernelCI_app/views/treeLatest.py, backend/kernelCI_app/views/treeView.py, backend/kernelCI_app/views/treeViewFast.py
Closes #1050
Some examples of this happening
- Set `DISCORD_WEBHOOK_URL` to the private server channel
- Force a server error (500-599). You can do it just returning a Response with HTTPStatus.INTERNAL_SERVER_ERROR in any view you'd like and check the server to see the error message showing there
=> feat: send notification when server errors happen

backend/kernelCI_app/queries/issues.py, backend/kernelCI_app/queries/test.py, backend/kernelCI_app/typeModels/issueDetails.py, backend/kernelCI_app/typeModels/testDetails.py, backend/kernelCI_app/utils.py, backend/kernelCI_app/views/issueDetailsTestsView.py, backend/kernelCI_app/views/testDetailsView.py, backend/schema.yml, dashboard/src/components/IssueTable/IssueTable.tsx
- Replaces django queryset with raw query to perform a left join on checkouts (and also left join on builds from issue tests);
- Adds issue version search parameters to issue details when navigating from issue listing to avoid unnecessary processing in the backend to get the latest issue version
Check that issues such as this [localhost redhat issue](http://localhost:5173/issue/redhat%3A61ff6ef41135804ad96bc8107bc29426caefa1dc?iv=1) returns the builds correctly, and compare it to the [staging equivalent](https://staging.dashboard.kernelci.org:9000/issue/redhat%3A61ff6ef41135804ad96bc8107bc29426caefa1dc?iv=1)
Other examples:
[localhost maestro issue](http://localhost:5173/issue/maestro:1bad4fd734ada1f413164870f3d66961f9eccbfb?iv=0) where the related checkout from a build doesn't exist …
=> Fix: left join checkouts for issue incidents

dashboard/src/api/commonRequest.ts, dashboard/src/components/BuildDetails/BuildDetailsTestSection.tsx, dashboard/src/components/Cards/IssuesList.tsx, dashboard/src/components/DetailsPages/SectionError.tsx, dashboard/src/components/Issue/IssueSection.tsx, dashboard/src/components/IssueDetails/IssueDetailsBuildSection.tsx, dashboard/src/components/IssueDetails/IssueDetailsTestSection.tsx, dashboard/src/components/TreeListingPage/TreeListingPage.tsx, dashboard/src/locales/messages/index.ts, dashboard/src/pages/Hardware/HardwareListingPage.tsx, dashboard/src/pages/IssueListing/IssueListingPage.tsx, dashboard/src/pages/TreeDetails/Tabs/TestCards.tsx
Closes #1079
- Open these pages listed in the issue and check that they are showing the correct error messages
- http://localhost:5173/hardware?o=tuxsuite
- http://localhost:5173/tree/8b83b87af0bfcaa972ca160170bae3e716ae4a24?p=bt&ti%7Cc=ASB-2025-03-05_13-5.15-3-g8b83b87af0bfc&ti%7Cch=8b83b87af0bfcaa972ca160170bae3e716ae4a24&ti%7Cgb=android13-5.15&ti%7Cgu=https%3A%2F%2Fandroid.googlesource.com%2Fkernel%2Fcommon&ti%7Ct=android
- http://localhost:5173/build/maestro%3A67d374faf378f0c5986c8bbe
- http://localhost:5173/test/maestro%3A67d40b04f378f0c5986dc939
=> fix: remove wrong error messages

backend/kernelCI_app/queries/issues.py, backend/kernelCI_app/typeModels/issueListing.py, backend/kernelCI_app/unitTests/issues_test.py, backend/kernelCI_app/unitTests/utils/client/issueClient.py, backend/kernelCI_app/views/issueView.py, backend/requests/issue-listing-get.sh, dashboard/src/api/issue.ts, dashboard/src/components/IssueTable/IssueTable.tsx, dashboard/src/components/TopBar/TopBar.tsx, dashboard/src/locales/messages/index.ts, dashboard/src/pages/Hardware/HardwareTable.tsx, dashboard/src/routes/_main/hardware/route.tsx, dashboard/src/routes/_main/issues/route.tsx, dashboard/src/types/general.ts, dashboard/src/types/issueListing.ts, dashboard/src/utils/constants/general.ts, dashboard/src/utils/constants/hardware.ts, dashboard/src/utils/search.ts
Close #1075 
- Navigate to issue listing page and see that origin select isn't in the header
- Navigate through the other pages to see that origin select isn't hidden in that
- Run tests
=> Feat: drop origin from issue listing

backend/kernelCI/envconfig/schema-version.yaml, backend/kernelCI_app/constants/general.py, backend/kernelCI_app/helpers/build.py, backend/kernelCI_app/helpers/environment.py, backend/kernelCI_app/helpers/errorHandling.py, backend/kernelCI_app/queries/build.py, backend/kernelCI_app/queries/hardware.py, backend/kernelCI_app/queries/issues.py, backend/kernelCI_app/queries/tree.py, backend/kernelCI_app/views/buildDetailsView.py, backend/kernelCI_app/views/buildTestsView.py, backend/kernelCI_app/views/hardwareDetailsBootsView.py, backend/kernelCI_app/views/hardwareDetailsBuildsView.py, backend/kernelCI_app/views/hardwareDetailsSummaryView.py, backend/kernelCI_app/views/hardwareDetailsTestsView.py, backend/kernelCI_app/views/hardwareDetailsView.py, backend/kernelCI_app/views/issueDetailsBuildsView.py, backend/kernelCI_app/views/treeCommitsHistory.py, backend/kernelCI_app/views/treeDetailsBootsView.py, backend/kernelCI_app/views/treeDetailsBuildsView.py, backend/kernelCI_app/views/treeDetailsSummaryView.py, backend/kernelCI_app/views/treeDetailsTestsView.py, backend/kernelCI_app/views/treeDetailsView.py
- Adds schema-version file instead of environment variable, so it can be shared between processes in the production docker instance
- Makes queries with db schema version 4 update schema and return correct data instead of just returning an error
- Refactors queries with build valid/status versions to be a single function
- Updates default db schema version to 5 and removes temporary error messages
- Also updates some endpoints to only return a `Response`, removing the need for `create_error_response`
To test the update from db schema version 4 to 5, change the file "schema-version.yaml" to set the variable as '4' and check endpoints which can change the db schema
Also test running on docker
Check if the updated queries are still returning correct data
Closes #1109
=> Feat: solidify schema change

dashboard/src/api/buildDetails.ts, dashboard/src/api/buildTests.ts, dashboard/src/api/hardware.ts, dashboard/src/api/hardwareDetails.ts, dashboard/src/api/issueDetails.ts, dashboard/src/api/testDetails.ts, dashboard/src/api/treeDetails.ts, dashboard/src/types/api.ts
Disabled refetch on window focus for the queries where this was a problem:
- useBuildTests
- useBuildIssues
- useTestIssues
Closes #1066
Open the a build or test details, wait until the issue section and test results section (for build details) are loaded, change tabs and go back to the details page. The section should not start loading again like it does on prod. You can test the same thing for the issue section in builds/boots/tests tables on any page (tree details, for example)
=> fix: disable refetch on windows focus

dashboard/src/api/commonRequest.ts, dashboard/src/components/BuildDetails/BuildDetails.tsx, dashboard/src/components/IssueDetails/IssueDetails.tsx, dashboard/src/components/TestDetails/TestDetails.tsx, dashboard/src/locales/messages/index.ts, dashboard/src/pages/TreeDetails/TreeDetails.tsx, dashboard/src/pages/hardwareDetails/HardwareDetails.tsx
Closes #1119
**NOTE:** I did not change `CommitNavigationGraph` and `TestStatusHistory` messages because if the page is loaded them they should also return with no errors (since they should return at least the data for the current page)
=> fix: update error messages for empty data

backend/kernelCI_app/cache.py, backend/kernelCI_app/constants/general.py, backend/kernelCI_app/helpers/discordWebhook.py, backend/kernelCI_app/helpers/logger.py, backend/kernelCI_app/helpers/system.py, docker-compose.yml
- Adds hardcoded staging and production urls to the notification to be differentiated when running in the wild;
- Adds timezone to access time;
- Adds a cooldown to the messages with the already existing cache system.
Trigger a discord notification, for example with this failed [build with tests](http://localhost:8000/api/build/maestro:67dadf0028b1441c0820bacc/tests)
Trigger the same notification again in a 10 minute interval
Check the backend process, it should trigger a log with "This message was already sent in the last 600 seconds"
Closes #1096
=> Feat: discord message improvements

backend/kernelCI_app/typeModels/hardwareListing.py, backend/kernelCI_app/unitTests/hardware_test.py, backend/kernelCI_app/views/hardwareView.py, backend/requests/hardware-listing.sh, backend/schema.yml, dashboard/src/api/hardware.ts
From endTimeStampInSeconds to endTimestampInSeconds
Closes #1122
- Run the unit tests in `hardware_test.py`
- Run `backend/requests/hardware-listing.sh`
- Open Hardware Listing Page and check it's working properly
- Open some Hardware Details Page and check it's working properly
=> fix: hardware parameter typo

dashboard/src/components/Filter/CodeBlock.tsx, dashboard/src/locales/messages/index.ts
I couldn't find a log greater then 4 million characters. I also did some testing but to be sure I decided to go for this constraint of 6 million characters.
Closes #1059
- Open logs in redhat origin and verify that every log does not take to much time to load and, in some cases, highlighted
[(localhost) example of a log with 14 million characters](http://localhost:5173/log-viewer?itemId=redhat%3A1729170198-x86_64-kernel-automotive&o=redhat&type=build&url=https%3A%2F%2Fs3.amazonaws.com%2Farr-cki-prod-trusted-artifacts%2Ftrusted-artifacts%2F1729170198%2Fbuild_x86_64%2F9489093468%2Fartifacts%2Fbuild.log)
=> fix: disable highlight on log viewer by file size

dashboard/src/components/TestDetails/TestDetails.tsx
Closes #1042
- Check a test with status null on [dashboard](https://dashboard.kernelci.org/test/maestro%3A67c834d818018371956b4350) and on [localhost](http://localhost:5173/test/maestro%3A67c834d818018371956b4350)
=> fix: show 'NULL' instead of '-' in status field

backend/Dockerfile, backend/kernelCI_app/typeModels/commonDetails.py, backend/kernelCI_app/views/treeDetailsView.py, dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/TreeDetails/Tabs/Build/BuildTab.tsx, dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTab.tsx
- Adds a timeout to the dockerfile so that the default (30, as described by [gunicorn's documentation](https://docs.gunicorn.org/en/stable/settings.html#timeout)) is overwritten by a larger value (120) to allow endpoints to be loading for longer, such as this [staging test](https://staging.dashboard.kernelci.org:9000/test/maestro:67ce429218018371957d9e59) that takes about 40s to load the status history, or this [staging tree](https://staging.dashboard.kernelci.org:9000/tree/bddc6e9322072ac3aa15bd972c5bcbf9f447d246?o=tuxsuite&p=t&ti%7Cc=v6.6.83-167-gbddc6e932207&ti%7Cch=bddc6e9322072ac3aa15bd972c5bcbf9f447d246&ti%7Cgb=&ti%7Cgu=https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Fstable%2Flinux-stable-rc.git) that takes about 80s to get the full data.
- Piggybacking is a small …
=> Feat: docker performance improvements

dashboard/src/components/TestDetails/TestDetails.tsx, dashboard/src/lib/string.ts
Build has no direct relation with hardware so that's why I didn't add any link to it as well. Even 'platform' that's inside the `misc` field in the `builds` table has no direct relation with the available hardware details pages, since we only consider platform and compatibles of tests in this case
Closes #960
- Enter a page with environment compatible: http://localhost:5173/test/maestro%3A67ea51dc67593f2aa0417959
- Enter a page with platform and no environment compatible: http://localhost:5173/test/maestro%3A67e9d6b667593f2aa0405adb
- Enter a page with none: http://localhost:5173/test/redhat%3A1739009469-aarch64-kernel-automotive_upt_aws_5?o=redhat
=> feat(test-details): add link to hardware details

backend/kernelCI_app/queries/test.py, backend/kernelCI_app/typeModels/databases.py, backend/kernelCI_app/typeModels/testDetails.py, backend/kernelCI_app/views/testStatusHistoryView.py, dashboard/src/components/TestDetails/TestDetails.tsx, dashboard/src/types/tree/TestDetails.tsx
Fixes a bug for tests with start_time null
Django takes care of None values by default only if the comparison is exact, but start_time uses an lower than equal comparison.
Go to test details pages for tests with start_time null and compare with the staging counterpart. Examples:
- [localhost redhat api](http://localhost:8000/api/test/status-history?path=boot&origin=redhat&git_repository_url=https:%2F%2Fgitlab.com%2Fredhat%2Fcentos-stream%2Fsrc%2Fkernel%2Fcentos-stream-9.git&git_repository_branch=main-automotive&config_name=rpm:+%2Flib%2Fmodules%2F5.14.0-575.524.test.gcov.el9iv.aarch64%2Fconfig) - [staging redhat api](https://staging.dashboard.kernelci.org:9000/api/test/status-history?path=boot&origin=redhat&git_repository_url=https:%2F%2Fgitlab.com%2Fredhat%2Fcentos-stream%2Fsrc%2Fkernel%2 …
=> Fix: start_time None in test status history

backend/kernelCI_app/cache.py, backend/kernelCI_app/queries/checkout.py, backend/kernelCI_app/queries/hardware.py, backend/kernelCI_app/queries/tree.py, backend/kernelCI_app/urls.py, backend/kernelCI_app/views/originsView.py, backend/requests/origins-get.sh, backend/schema.yml, dashboard/src/api/hardware.ts, dashboard/src/api/hardwareDetails.ts, dashboard/src/api/origin.ts, dashboard/src/api/tree.ts, dashboard/src/components/TopBar/TopBar.tsx, dashboard/src/components/TreeListingPage/TreeTable.tsx, dashboard/src/types/general.ts, dashboard/src/utils/date.ts
- Adds origins endpoint to retrieve all origins from checkouts;
- Uses that endpoint in the frontend instead of having the origins hardcoded;
- The origin search parameter is now a simple string, and not an enum anymore; however, there is no way to change it from the dashboard unless the user changes it in the url and the fields that are an enum in the backend (all status fields) are also just a simple string in the frontend search parameters
Go to the tree listing and see that the origin selector now loads for a second, getting the origins from the backend
All endpoints that require origins should run normally
Closes #1149
Closes #1144
=> feat: define origins dynamically

backend/kernelCI_app/queries/tree.py, backend/kernelCI_app/typeModels/treeCommits.py, backend/kernelCI_app/views/treeCommitsHistory.py, backend/schema.yml
Fixes a problem specially on broonie where checkouts fetched for the commit history graph were not the same as the checkout for tree details. On treeDetails the data was gotten by a combination of origin, hash, branch, url, while on the commitHistory it was gotten virtually only by checkout id.
Refactors the endpoint a bit to use pydantic validation and fixes a start_timestamp search parameter that wasn't being used correctly
Adds an intermediate query to get all `checkout_id`s from the commitHistory - the final query is still the same and therefore the rest of the functions and data is processed the same way
Go to tree details and check if the counting from the commit history graph is the same as the counting from the treeDetails page, comparing with the staging equivalent.
The graph for …
=> Fix: commit history counting

backend/kernelCI_app/helpers/hardwareDetails.py, backend/kernelCI_app/helpers/issueExtras.py, backend/kernelCI_app/helpers/trees.py, backend/kernelCI_app/queries/issues.py, backend/kernelCI_app/queries/tree.py, backend/kernelCI_app/typeModels/treeDetails.py, backend/kernelCI_app/views/buildDetailsView.py, backend/kernelCI_app/views/hardwareDetailsBootsView.py, backend/kernelCI_app/views/hardwareDetailsBuildsView.py, backend/kernelCI_app/views/hardwareDetailsCommitHistoryView.py, backend/kernelCI_app/views/hardwareDetailsSummaryView.py, backend/kernelCI_app/views/hardwareDetailsTestsView.py, backend/kernelCI_app/views/hardwareDetailsView.py, backend/kernelCI_app/views/issueDetailsBuildsView.py, backend/kernelCI_app/views/issueDetailsTestsView.py, backend/kernelCI_app/views/testDetailsView.py, backend/kernelCI_app/views/treeLatest.py, backend/kernelCI_app/views/treeView.py, backend/kernelCI_app/views/treeViewFast.py, dashboard/src/pages/TreeLatest.tsx, dashboard/src/types/tree/Tree.tsx
Overrides the tree_name on all endpoints that return tree_name to use the tree_name on the trees-name.yaml file, which is retrieved by the git_repository_url
Special notes to the treeLatest endpoint (or the shortcut to a tree):
First, it will now retry the query in case the kcidb tree name is null but is not null on the file, allowing to search for a tree that doesn't have tree_name on kcidb (such as /tree/mainline/master?o=arm)
Secondly, it will also return the name from the file even if it exists on kcidb but is different. For example: if a tree has name A on kcidb but name B on trees-name.yaml, I can fetch /tree/A/branch and it will return me the treeDetails page but with tree name B; a breaking scenario could be if a tree _has_ the B name on kcidb when it shouldn't, in which case the …
=> Feat: use tree names file

backend/kernelCI_app/helpers/detailsIssues.py, backend/kernelCI_app/helpers/filters.py, backend/kernelCI_app/helpers/hardwareDetails.py, backend/kernelCI_app/helpers/treeDetails.py, backend/kernelCI_app/tests/unitTests/filters_test.py, backend/kernelCI_app/typeModels/common.py, backend/kernelCI_app/typeModels/commonDetails.py, backend/kernelCI_app/typeModels/hardwareDetails.py, backend/kernelCI_app/typeModels/hardwareListing.py, backend/kernelCI_app/typeModels/issues.py, backend/kernelCI_app/typeModels/treeCommits.py, backend/kernelCI_app/typeModels/treeListing.py, backend/kernelCI_app/utils.py, backend/kernelCI_app/views/buildIssuesView.py, backend/kernelCI_app/views/testIssuesView.py, backend/kernelCI_app/views/treeDetailsBootsView.py, backend/kernelCI_app/views/treeDetailsSummaryView.py, backend/kernelCI_app/views/treeDetailsTestsView.py, backend/kernelCI_app/views/treeDetailsView.py, backend/kernelCI_app/views/treeView.py, dashboard/src/components/Cards/IssuesList.tsx, dashboard/src/components/Issue/IssueSection.tsx, dashboard/src/components/ListingItem/ListingItem.tsx, dashboard/src/types/issues.ts
Changes the issue counting from a simple int to a status based dict, allowing for better distinction in the frontend
Makes the issue card group issues by status
Also refactors some functions to have stricter, correct typing
Go to treeDetails and hardwareDetails pages that have issues and check the new layout
Pages that show a list of issues should all still work correctly, and when they showed a count the number should still be correct
Issue filters should also still work
Before
After
[hardware details with boot issues](http://localhost:5173/hardware/acer-cp514-2h-1130g7-volteer?et=1744396200&p=bt&st=1743964200&tf%7Cb=a&tf%7Cbt=i&tf%7Ct=a)
[maestro tree details with boot issues and failed builds](http://localhost:5173/tree/660bd24947f57692061f1dd7011ae4c66aa0e79a?p=bt&ti%7Cc=amlogic-arm64- …
=> Feat: improve issue counting

backend/data/trees-name.yaml, backend/kernelCI/settings.py, backend/kernelCI_app/management/commands/treeproof.py
Some trees had the tree name present in the file but had a different url, that made them not be added to the file since their name was already in the list, which in turn meant that they weren't being added to the file but also that their url wasn't being considered. This was solved by first knowing that the url wasn't in the file, then, if the tree_name from kcidb is already in the file, get it from the url, then either if the tree_name was retrieved from kcidb or from the url, **adds a suffix to the tree_name as "-n" where n is an int** such that it's possible to add that url with a unique tree_name. This suffix is only incremented if it is already present.
- Adds a suffix to existing tree_name but unexisting git_url in the file;
- Fixes a condition that made the file not update;
- …
=> Fix: missing tree names in file

backend/kernelCI_app/helpers/detailsIssues.py, backend/kernelCI_app/helpers/issueExtras.py, backend/kernelCI_app/helpers/trees.py, backend/kernelCI_app/queries/hardware.py, backend/kernelCI_app/queries/issues.py, backend/kernelCI_app/queries/tree.py, backend/kernelCI_app/views/buildIssuesView.py, backend/kernelCI_app/views/hardwareDetailsBootsView.py, backend/kernelCI_app/views/hardwareDetailsCommitHistoryView.py, backend/kernelCI_app/views/hardwareDetailsSummaryView.py, backend/kernelCI_app/views/hardwareDetailsView.py, backend/kernelCI_app/views/testIssuesView.py, backend/kernelCI_app/views/treeLatest.py, backend/schema.yml
Moves all the remaining queries from other files to the queries folder
This is a refactor PR, so there are no additions. All the modified endpoints should still work the same as before.
Closes #1169
=> Refactor: move queries to its folder

dashboard/src/components/TreeListingPage/TreeTable.tsx, dashboard/src/utils/constants/tables.ts, dashboard/src/utils/trees.ts
- Adds a list to specify priority trees;
- Uses that list to order the treelisting data, putting the prioritized trees first.
This means that when there is _no sorting_, those trees will appear at the top. In the case of any sorting, the sorting will override the ordering, but it is possible to reset the sorting by clicking at the header (sorting goes as "unsorted" -> "sort ascending" -> "sort descending" -> "unsorted")
The priority trees are defined by a regex that describes the tree/branch key of a tree (the git_repository_url was not used since the tree_name is now retrieved by the trees_name file which is unique for each url already). Being a regex it allows for a tree with any branch name.
The current priority trees are mainline/master, next/master, and stable trees with any branch. …
=> Feat: order treeListing with pinned trees first

backend/kernelCI_app/typeModels/common.py, backend/kernelCI_app/typeModels/treeListing.py, backend/kernelCI_app/views/treeView.py, dashboard/src/components/IssueTable/IssueTable.tsx, dashboard/src/components/TreeListingPage/TreeTable.tsx
Fixes a bug where some trees were repeated in the treeListing.
This was caused because some trees have the same branch and url but different tree_name in kcidb, which meant that they were grouped separately but shown as the same tree_name (because of the same url).
The proposed solution groups those trees in a single element, adding up the counts and combining the commit tags.
- Changes the set for adding checkouts for the treeView response;
- Adds helper methods for addition of status;
- (extra) fixes the sorting for status in the treeTable
- (extra) fixes a redirection from the issueListing table with different origins
Go to a tree listing in which the above situation occurred (such as in origin redhat) and compare the [localhost](http://localhost:5173/tree?o=redhat) to …
=> Fix: repeated trees

backend/kernelCI_app/queries/tree.py, backend/kernelCI_app/typeModels/treeDetails.py, backend/kernelCI_app/views/treeLatest.py, backend/schema.yml, dashboard/src/api/tree.ts, dashboard/src/locales/messages/index.ts, dashboard/src/pages/TreeLatest/ShortTreeLatest.tsx, dashboard/src/pages/TreeLatest/TreeLatest.tsx, dashboard/src/routeTree.gen.ts, dashboard/src/routes/_main/(alternatives)/c/$treeName/$branch/index.tsx, dashboard/src/routes/_main/(alternatives)/c/$treeName/$branch/route.tsx, dashboard/src/routes/_main/tree/$treeName/$branch/index.tsx, dashboard/src/routes/_main/tree/$treeName/$branch/route.tsx, dashboard/src/types/general.ts, dashboard/src/utils/search.ts
- Adds a shortening to the shortcut `/tree/<tree_name>/<tree_branch>` as `/c/<tree_name>/<tree_branch>` (resembling checkout);
- Adds an optional `gitCommitHash` parameter to those shortcuts to go to a specific git commit hash of that tree, with a short name of `gch` (`ch` as short for 'commit hash' was already being used for 'culprit harness');
- Changes backend query slightly to query for a specific hash.
The shortcut `/tree/<tree_name>/<tree_branch>` was kept since there was no real harm on keeping it and it will maintain the compatibility with old links for now.
Go to a tree and then reach it with the shortcuts.
Check the commit history graph and use the shortcut with git commit hash to go directly to that specific commit.
The treeListing and older shortcuts should still be working …
=> Feat: add alternative to /tree shortcut and optional gitCommitHash param

backend/kernelCI_app/helpers/hardwareDetails.py, backend/kernelCI_app/helpers/issueExtras.py, backend/kernelCI_app/helpers/trees.py, backend/kernelCI_app/queries/tree.py, backend/kernelCI_app/tests/integrationTests/treeLatest_test.py, backend/kernelCI_app/views/buildDetailsView.py, backend/kernelCI_app/views/hardwareDetailsBootsView.py, backend/kernelCI_app/views/hardwareDetailsBuildsView.py, backend/kernelCI_app/views/hardwareDetailsCommitHistoryView.py, backend/kernelCI_app/views/hardwareDetailsSummaryView.py, backend/kernelCI_app/views/hardwareDetailsTestsView.py, backend/kernelCI_app/views/hardwareDetailsView.py, backend/kernelCI_app/views/issueDetailsBuildsView.py, backend/kernelCI_app/views/issueDetailsTestsView.py, backend/kernelCI_app/views/testDetailsView.py, backend/kernelCI_app/views/treeLatest.py, backend/kernelCI_app/views/treeView.py, backend/kernelCI_app/views/treeViewFast.py
Rolls back the substitution of tree names with the file, as well as the use of the file for the treeLatest endpoint, removing the use of the url for the query
The tree names should be the same as the names in the production dashboard, as they were unchanged there. All endpoints should be working normally.
Closes #1189
=> Fix: revert tree name file use

backend/kernelCI_app/queries/hardware.py, backend/kernelCI_app/tests/utils/fields/hardware.py, backend/kernelCI_app/typeModels/hardwareListing.py, backend/kernelCI_app/views/hardwareView.py, backend/requests/hardware-listing.sh, dashboard/src/components/Checkbox/Checkbox.tsx, dashboard/src/locales/messages/index.ts, dashboard/src/pages/Hardware/HardwareListingPage.tsx, dashboard/src/pages/Hardware/HardwareTable.tsx, dashboard/src/pages/hardwareDetails/HardwareDetailsFilter.tsx, dashboard/src/pages/hardwareDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/hardwareDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/types/general.ts, dashboard/src/types/hardware.ts, dashboard/src/utils/search.ts, dashboard/src/utils/utils.ts
- Reformats and refactors hardware listing query to group by platform first and not unnest hardware;
- Changes typing accordingly to consider hardware as optional and platform as single string;
- Adds compatibles to frontend table as badges;
- Removes unnecessary filters and card from boots/tests tab for hardware/platform details.
Note: the change in the query for the hardware listing data was made such that the hardware are not unnested now, and from business requirements a platform should always be associated with the same array of compatibles, and in that way it is possible to group by platform and hardware without having more than one row repeating a platform.
Go to the hardware listing page and see the listing based on platforms now.
- Check the search and sorting of the hardware …
=> Feat: change hardware listing to be platform based

dashboard/src/components/Filter/CodeBlock.tsx, dashboard/src/components/Filter/highlightedCode.test.ts
Improves regex to be sensitive to corner cases while still getting other cases right
Added **unit tests** for the highlighter function in order to make it easier to test
To run the unit tests, go to the frontend folder (/dashboard/dashboard) and run `pnpm test src/components/Filter/highlightedCode.test.ts`
Run the unit tests, you can add some other cases too;
Check the pages linked from the issue 774 (for the corner cases "Ignore error" and "pass:n fail:0";
Check other pages with logs and see if the highlight makes sense.
Closes #774
=> Feat: improve log highlight

backend/kernelCI_app/helpers/trees.py, backend/kernelCI_app/management/commands/notifications.py, backend/kernelCI_app/management/commands/templates/summary.txt.j2, backend/kernelCI_app/queries/notifications.py, backend/kernelCI_app/queries/tree.py, backend/kernelCI_app/typeModels/common.py, backend/kernelCI_app/typeModels/treeListing.py, backend/kernelCI_app/utils.py, backend/kernelCI_app/views/treeView.py, backend/kernelCI_app/views/treeViewFast.py
In the current state, there are two queries for every tree in the checkout summary notification. This PR changes it such that there is a single query to get the basic checkout information of all trees at once, and then get the specific test data for each tree as before.
The query that replaces the current one for the checkout information is closely related to the tree listing query, which means that it will get the status count for all selected trees, and this is then added to the checkout summary email notification.
- Replaces "latest checkout" query in the email notifications with a query similar to tree listing to get status count for all the trees in the yaml file;
- Changes the jinja template such that all fields from "checkout" are fields from kcidb, and also adds the counting for a …
=> Feat: add status counts to checkout summary email notification

backend/kernelCI/settings.py, backend/kernelCI_cache/queries/issues.py, docker-compose.yml
When adding a type validation to the query, the return became `[IssueKeyTuple(str, int)]` instead of a simple list of tuples, so when comparing a tuple with the result, it was comparing a tuple with an IssueKeyTuple object, which was always false and therefore new issues were skipping the stored issues.
This PR also has a small change to fix the default gmail api file, such that we have a default fallback if we don't explicitly pass it to run the notification command.
Check your local sqlite database, then erase the data to make it simpler to compare
Run the new issues command,
```
poetry run ./manage.py notifications --ignore-recipients --update-storage --send --action="new_issues"
```
Check the database and see that the issues are stored there as unsent
Run the new issues command again. …
=> Fix: new issues ignoring stored issues

dashboard/src/components/Button/CopyButton.tsx, dashboard/src/components/Dialog/CustomDialog.tsx, dashboard/src/components/Icons/ExternalLink.tsx, dashboard/src/components/SideMenu/NavLink.tsx, dashboard/src/components/SideMenu/SendFeedback.tsx, dashboard/src/components/SideMenu/SideMenu.tsx, dashboard/src/components/TopBar/TopBar.tsx, dashboard/src/components/ui/dialog.tsx, dashboard/src/locales/messages/index.ts
- Adds another entry to the sidebar to link to other community dashboards: kdevops, netdev-CI, and Grafana.
- Adds icons to the sidemenu dialog buttons
- Updates Dialog from shadcn to include DialogFooter and DialogDescription
- Adds a CustomDialog component to make it easily reusable
- Substitutes use of AlertDialog for Dialog in sidebar, so that a user can close the dialog by clicking outside of it
- Removes unnecessary use of AlertDialog in CopyButton for a more correct use of Button
Go to any page in the dashboard that has the sidemenu, click on "Community Dashboards" and check the component and its links
Other sidemenu items should still work normally
Other dialogs should still work normally
Send us feedback Before / After
Sidebar
|--------|---------|
| …
=> Feat: add community dashboards

backend/kernelCI/settings.py, backend/kernelCI_app/helpers/filters.py, backend/kernelCI_app/queries/issues.py, backend/kernelCI_app/tests/integrationTests/issues_test.py, backend/kernelCI_app/tests/utils/client/baseClient.py, backend/kernelCI_app/tests/utils/client/issueClient.py, backend/kernelCI_app/typeModels/issues.py, backend/kernelCI_app/views/issueView.py, backend/requests/issue-listing-get.sh, backend/schema.yml, dashboard/src/api/hardwareDetails.ts, dashboard/src/api/issue.ts, dashboard/src/components/IssueTable/IssueTable.tsx, dashboard/src/components/Tabs/Filters.tsx, dashboard/src/components/Tabs/tabsUtils.ts, dashboard/src/pages/IssueListing/IssueListingPage.tsx, dashboard/src/routes/_main/issues/route.tsx, dashboard/src/types/general.ts, dashboard/src/utils/search.ts, dashboard/src/utils/utils.ts
Refactors issue listing to remove the old culprit system and allow for a more expansive approach with `diffFilter`, allowing future changes to add more filters.
The issue culprits are separate fields in the database, but since they are about the same idea, they can be grouped inside of diffFilter, which sends groups of filters to the backend.
- Swaps django query constructor for SQL raw query in issueListing endpoint
- Changes filtering from query layer to python layer
- Changes frontend query parameter structure from individual culprit fields to `diffFilter`
- (piggybacking) fixing a one-line problem that the cache database was always being created as an unstaged file in the backend root directory when running locally
The default hardcoded filter by culprit code is still being applied, …
=> Refactor: allow more filters for issue listing

dashboard/src/components/BuildDetails/BuildDetails.tsx, dashboard/src/components/BuildDetails/BuildDetailsTestSection.tsx, dashboard/src/components/Issue/IssueSection.tsx
- Rearranges the sections to put the test table right after the general information section, misc data right after, and then issue data, leaving the artifacts at the bottom;
- Makes it so that the issue section is not shown if a build has no issues;
- Also slightly changes the spacing to standardize it through the page.
Go to a build details page and check the section rearrangement, comparing it to staging.
Old ([staging link](https://staging.dashboard.kernelci.org:9000/build/maestro%3A68342ef5fb37369f44a86dc9?iv=1))
New ([localhost link](http://localhost:5173/build/maestro%3A68342ef5fb37369f44a86dc9?iv=1))
Closes #1245
=> Refactor: move build tests up in the page

dashboard/src/components/Cards/HardwareTested.tsx, dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/TreeDetails/Tabs/TestCards.tsx, dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/pages/TreeDetails/TreeDetails.tsx
- Removes the HardwareUsed card that was at the top of treeDetails page
- Removed duplicate HardwareTested component
Go to treeDetails page and check that the hardwareUsed at the top is no longer there. All tabs and other pages should still behave normally.
Closes #1244
=> Refactor: remove hardware used box

dashboard/src/components/TestsTable/IndividualTestsTable.tsx
The individual tests table was opening the wrong log when scrolled down to virtualized items.
The idx of the virtual rows was being used instead of the index of all the rows, causing the sheet to show wrong logs once the visible rows were no longer the first ones.
Being more specific, the TableRowMemoized component receives the `openLogSheet` function and the `index` property, and after passing it down what it actually does is trigger the `setLog` setter to mark which `index` of the data the log belongs to. The problem was that it was using the index of the mapping from virtual rows, which are only the rows that are visible, so the index was always in a small range from 0 to around 15. The fix was to use the `virtualRows.index` instead, which holds the real index of each virtualized row …
=> Fix: wrong test sheet opening

backend/kernelCI_app/helpers/hardwareDetails.py, backend/kernelCI_app/helpers/treeDetails.py, backend/kernelCI_app/queries/hardware.py, backend/kernelCI_app/queries/tree.py, backend/kernelCI_app/tests/integrationTests/hardwareDetailsSummary_test.py, backend/kernelCI_app/tests/integrationTests/treeDetailsSummary_test.py, backend/kernelCI_app/typeModels/commonDetails.py, backend/kernelCI_app/viewCommon.py, backend/kernelCI_app/views/hardwareDetailsSummaryView.py, backend/kernelCI_app/views/hardwareDetailsView.py, backend/kernelCI_app/views/treeDetailsBootsView.py, backend/kernelCI_app/views/treeDetailsSummaryView.py, backend/kernelCI_app/views/treeDetailsTestsView.py, backend/kernelCI_app/views/treeDetailsView.py, backend/schema.yml
In some cases a checkout with origin A will have builds with origin B, and a build with origin B might have tests with origin C.
- Alters tree details query to allow tests and builds with origins different from the checkout origin;
- Returns build and tests origins from tree and hardware endpoints
For most trees, check that the return in the items, `summary` and `filters` fields now include their origin
In more specific cases, check that this [localhost stable-rc tree](http://localhost:5173/tree/stable-rc/linux-6.6.y/18952a1fc4ac790deb4faa116f18310d7010a9fb) includes tests from riscv (check the summary response in the network tab), and this [localhost next master tree](http://localhost:5173/tree/next/master/2a628f951ed54c30a232230b5b58349d2a8dbb11) includes boots from ti.
Also check if …
=> Feat: show tests from all origins in treeDetails

backend/kernelCI_app/queries/checkout.py, backend/kernelCI_app/typeModels/origins.py, backend/kernelCI_app/views/originsView.py, backend/requests/origins-get.sh, backend/schema.yml, dashboard/src/api/origin.ts, dashboard/src/components/TopBar/TopBar.tsx, dashboard/src/types/origins.ts
This new structure allows adding other origins in the future and also better follows the structure we are using in other endpoints
- Replaces origins query for a raw sql query
- Alters the response/request structure from a simple array to a dict of fields where each field shows the origins per table (currently only checkouts)
This is only a refactor of the current behavior, no additions are made, and the endpoint should be working like before.
Part of #1242
=> Refactor: change origin endpoint structure

backend/kernelCI_app/tests/integrationTests/origins_test.py, backend/kernelCI_app/tests/utils/client/originClient.py, backend/kernelCI_app/tests/utils/fields/origins.py, backend/kernelCI_app/typeModels/origins.py, backend/kernelCI_app/views/originsView.py, backend/requests/origins-get.sh, backend/schema.yml, dashboard/src/components/TopBar/TopBar.tsx, dashboard/src/types/origins.ts
- Adds a `TEST_ORIGINS` const variable to be returned in the origins endpoint. This is hardcoded because the query for them (selecting distinct origins from tests) was taking too long to finish, requiring a whole cache system in order to be usable. Not only that, but the origins aren't changed frequently, so for now it was discussed that the test origins could be added manually.
- Uses the test origins only in the hardware listing and hardware details origin selector, in the tree details the origins shown will still be the dynamic checkout origins.
- Added integration tests for the origins endpoint.
- Go to hardware listing or hardware details and check the origin selector, the difference to the checkout origins should be the "riscv" and "ti" origins.
- The use of the origin selector …
=> Feat: add test origins manually

backend/kernelCI_app/helpers/treeDetails.py, backend/kernelCI_app/queries/tree.py, backend/kernelCI_app/urls.py, backend/kernelCI_app/views/treeCommitsHistory.py, backend/kernelCI_app/views/treeDetailsBootsView.py, backend/kernelCI_app/views/treeDetailsBuildsView.py, backend/kernelCI_app/views/treeDetailsSummaryView.py, backend/kernelCI_app/views/treeDetailsTestsView.py, backend/kernelCI_app/views/treeDetailsView.py, backend/schema.yml, dashboard/src/api/commitHistory.ts, dashboard/src/api/treeDetails.ts, dashboard/src/components/CommitNavigationGraph/CommitNavigationGraph.tsx, dashboard/src/components/TreeListingPage/TreeTable.tsx, dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/TreeDetails/Tabs/Build/BuildTab.tsx, dashboard/src/pages/TreeDetails/Tabs/Build/TreeDetailsBuildsTable.tsx, dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/pages/TreeDetails/Tabs/TreeCommitNavigationGraph.tsx, dashboard/src/pages/TreeDetails/Tabs/TreeDetailsTab.tsx, dashboard/src/pages/TreeDetails/TreeDetails.tsx, dashboard/src/routeTree.gen.ts, dashboard/src/routes/_main/tree/$treeId/index.tsx, dashboard/src/routes/_main/tree/$treeId/route.tsx, dashboard/src/routes/_main/tree/$treeName/$branch/$hash/index.tsx, dashboard/src/routes/_main/tree/$treeName/$branch/$hash/route.tsx, dashboard/src/types/tree/TreeDetails.tsx, dashboard/src/utils/treeDetails.ts, dashboard/src/utils/utils.ts
This PR changes the way that the data is used in order to get the treeDetails page. Instead of relying on the `git_url` of a tree, we now only need the `tree_name`, `git_repository_branch`, and `git_commit_hash`. When all of them are available, the url for the treeDetails page should be `/tree/<tree_name>/<branch>/<hash>`.
This has implications of changing how the backend uses those variables to query the database, and implications on the frontend subcomponents that get information from the url and navigate between pages. The frontend page can now be accessed through both urls (no redirecting, just using the same component), and the tree listing page will send the user to the new url for treeDetails. The backend views can also be accessed through both endpoints.
One issue with accessing …
=> Feat: short tree details url

backend/kernelCI_app/tests/integrationTests/treeListing_test.py, dashboard/src/components/BuildDetails/BuildDetails.tsx, dashboard/src/components/Footer/KcidevFooter.tsx, dashboard/src/components/Icons/TooltipIcon.tsx, dashboard/src/components/IssueDetails/IssueDetails.tsx, dashboard/src/components/TestDetails/TestDetails.tsx, dashboard/src/components/TreeListingPage/TreeListingPage.tsx, dashboard/src/locales/messages/index.ts, dashboard/src/pages/Hardware/HardwareListingPage.tsx, dashboard/src/pages/IssueListing/IssueListingPage.tsx, dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/TreeDetails/Tabs/Build/BuildTab.tsx, dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/pages/TreeDetails/Tabs/TreeCommitNavigationGraph.tsx, dashboard/src/pages/hardwareDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/hardwareDetails/Tabs/Build/BuildTab.tsx, dashboard/src/pages/hardwareDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/utils/test.ts, dashboard/src/utils/treeDetails.ts
- Adds a component that can be used as a footer to show a CTA for kci-dev, as well as a tooltip with the equivalent tooltip for that specific page
- Uses that component in all pages, showing the command for the pages that have an equivalent command for them
- This includes the specific "builds/boots/tests" for treeDetails and hardwareDetails
- It does not show any command for treeDetails without git_url
- It does not show any command for issueListing and issueDetails pages since there are no commands for it there
- All commands are subcommands of `kci-dev results`
- In order to use that component, the `sanitizeTreeInfo` was also used in the treeDetails tabs to get the required data and unify the processing.
Go to any page and check the footer at the bottom of the page
Check the different …
=> Feat: Add kci-dev information

backend/kernelCI_app/queries/notifications.py, docs/notifications.md
The major bottleneck in the summary command is the tests_results query, which was improved to be simpler and more direct.
The summary command will get the data from the submission files, add the kcidb data on it, then query the history of tests for that tree.
The query for test history will gather all checkouts for that tree between the latest checkouts and 30 days ago, then partition the tests by path+platform+config, and assign them a row_number from latest to oldest, then only return the tests where the latest item is in the searched checkout hash, limited to 5 tests.
This query performs a row_number() operation over many rows, causing it to be very slow specially on the mainline/master tree, where there is no path filter as well. This PR addresses the performance by improving the …
=> Feat: improve summary notification performance

.github/workflows/staging-db.yaml
As we might develop breaking features, we have separate database, dashboard and kcidb-ng instance running on staging server. We need also suitable way to deploy dashboard there using github workflows.
=> workflows: Add separate staging deployment (manual)

backend/kernelCI_app/constants/localization.py, backend/kernelCI_app/management/commands/notifications.py, backend/kernelCI_app/queries/notifications.py, backend/kernelCI_app/typeModels/kciSummary.py, backend/kernelCI_app/urls.py, backend/kernelCI_app/views/kciSummaryView.py, backend/requests/kci-summary-get.sh, backend/schema.yml
The endpoint is meant to return the same data as the checkout summary notification command. However, this endpoint returns the data for a single tree.
- Added new endpoint that queries the same data as the notification would query.
This endpoint is backend-only, meaning that it is not called by the frontend of the dashboard. To test it, you can use the swagger UI or send requests directly to the url.
Test with some trees (branch + url), as well as different paths and origins.
A tree that currently returns inconclusive tests is branch `for-kernelci` url `https://git.kernel.org/pub/scm/linux/kernel/git/arm64/linux.git`. An example of the response can be seen in the requests folder.
Closes #1321
=> Feat: add checkout summary endpoint

backend/kernelCI/settings.py, backend/kernelCI_app/routers/databaseRouter.py, backend/kernelCI_app/routers/disableMigrateRouter.py, backend/kernelCI_cache/migrations/0011_copy_data_from_cache_if_exists.py, backend/kernelCI_cache/queries/issues.py, backend/kernelCI_cache/queries/notifications.py, backend/migrate-cache-db.sh
This PR separates the SQLite databases used by the backend to better reflect the purpose and lifecycle of different types of data.
It also implements the automatic migration of notifications data from the cache database to the new notification database, as part of the multi-database separation process.
1. Run the migration `migrate-cache-db.sh` in different scenarios:
1.1. Legacy schema: cache DB exists with notifications data, and the notification DB does not exist.
1.2. Partial schema: cache DB exists but is empty, and the notification DB does not exist.
1.3. Fresh setup: neither cache nor notification tables exist.
1. Verify that `volume_data/cache.sqlite3` and `volume_data/notifications.sqlite3` databases is created
1. Start the backend server and perform a quick sanity check:
Closes …
=> feat(database): separate SQLite databases

backend/data/notifications/example-subscription.yaml, backend/data/notifications/subscriptions/media-committers.yaml, backend/data/notifications/subscriptions/stable-rt.yaml, backend/kernelCI_app/constants/localization.py, backend/kernelCI_app/management/commands/notifications.py, backend/kernelCI_app/queries/notifications.py, backend/kernelCI_app/typeModels/kciSummary.py, backend/schema.yml
The approach used for querying for different like clauses was using `LIKE ANY (ARRAY[])`, I'm open to other approaches.
- Changes the use of paths from a single string to an array of strings, allowing for multiple paths to be used _in a single report_
- Changed the path parameter of kciSummary endpoint to receive an array of paths as well
For the notification command, change some tree file to use an array of paths (isolating the file is ideal for debugging) and run the notification command. Be aware of the intervals in the queries as well.
Also check the kciSummary endpoint, passing a tree and multiple paths and checking the return.
Closes #1217
=> Feat: multiple path report

dashboard/src/components/Tabs/Tests/ErrorsSummary.tsx
Fixes a visual bug where the architecture summary card wasn't updating in the tests tab. The bug was caused by a memoization problem where rows with the same key wouldn't leave the screen.
This can be seen in the tests tab (which doesn't group the arch/compilers like the build tab does) that had more than one compiler per architecture. Since the key of the rows was only the arch name, it ended up creating rows with the same key.
In those trees, if you filter by some arch, the arch that you selected would be shown, as well as at least one of each repeated arch. Removing the filter would also create duplicates of those items.
Example:
In [production stable/linux-5.15.y](https://dashboard.kernelci.org/tree/stable/linux-5.15.y/3dea0e7f549ee8ce3ce9d058d6d5c494d9ad02dc?i=9&p=t), there are 4 …
=> Fix: arch card not updating

backend/kernelCI_app/views/kciSummaryView.py
The `.get` method gets list values from conventional dicts, _but with django GET request_ the `.get` method only returns the last item in a list. For list parameters, it is necessary to use the `.getlist` method, as seen in an age old question [here](https://code.djangoproject.com/ticket/1130).
Also, the `.get` on `request.GET` will return a single value, hence why even with a single element it is still crashing the endpoint (a string is not a list).
- Used getlist instead of get for the path parameter
- Give some tries to the endpoint, and check with the staging equivalent
Closes #1329
=> Fix: getlist param in kciSummaryView

backend/kernelCI_app/management/commands/notifications.py, backend/kernelCI_app/queries/notifications.py, backend/kernelCI_app/views/kciSummaryView.py
The kcidb_execute_query allows for a sys.exit since it was only used in a command context. Since it is now used in the full backend context, it should be avoided in order to allow for an error 500 instead of exiting the backend
- Replaced `kcidb_execute_query` with the usual cursor and dictfetchall
- Go to the kciSummary endpoint and compare queries on staging and locally, they should both still work
- Also compare the notifications command before and after the change
Closes #1328
=> Fix: avoid backend exit

backend/kernelCI_app/management/commands/templates/issue_boot.txt.j2, backend/kernelCI_app/management/commands/templates/issue_build.txt.j2, backend/kernelCI_app/queries/notifications.py
Readers benefit from seeing the git tag as well in the reports so we are adding these from now on.
=> backend: notifications: Add git tags to issue reports

dashboard/src/components/Breadcrumb/TreeBreadcrumb.tsx, dashboard/src/components/Log/LogViewerCard.tsx, dashboard/src/components/TestDetails/TestDetails.tsx, dashboard/src/components/TreeListingPage/TreeTable.tsx, dashboard/src/main.tsx, dashboard/src/pages/BuildDetails/BuildDetails.tsx, dashboard/src/pages/LogViewer.tsx, dashboard/src/pages/TreeBuildDetails/TreeBuildDetails.tsx, dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx, dashboard/src/pages/TreeDetails/Tabs/Build/TreeDetailsBuildsTable.tsx, dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTab.tsx, dashboard/src/routes/_main/tree/$treeId/build/$buildId/index.tsx, dashboard/src/routes/_main/tree/$treeId/test/$testId/index.tsx
This PR fixes the breadcrumb links for the BuildDetails, TestDetails and LogViewer pages to accommodate the updated URL structure.
Previously, breadcrumbs were not resolving correctly due to changes in the route parameters.
With this fix, the breadcrumb now accurately reflects the current path
1. Navigate to a TreeDetails page via TreeListing or directly via URL
1. From there, open related pages such as LogViewer, BuildDetails and TestDetails
1. Verify that the breadcrumb displays correctly in each case and accurately reflects the full path back to the TreeDetails
1. Ensure no breadcrumb segment is broken or missing
Closes #1314
=> fix(breadcrumbs): adjust LogViewer, Build Details and Test Details breadcrumb for new URL structure

backend/kernelCI_app/constants/localization.py, backend/kernelCI_app/typeModels/treeReport.py, backend/kernelCI_app/urls.py, backend/kernelCI_app/views/treeReportView.py, backend/requests/tree-report-get.sh, backend/schema.yml
This PR renames the kci-summary endpoint to tree-report.
It includes changes to the endpoint route, view name, type model identifiers, and schema definitions where the previous name was used.
1. Run the backend server and open the Swagger UI at /api/schema/swagger-ui/
1. Locate the renamed endpoint and confirm it is listed with the new name and correct description
1. Send a request to the endpoint and verify the response remains unchanged in structure and correctness
1. Check that there are no remaining references to the old kci-summary name in the codebase
Closes #1344
=> refactor(api): rename kci-summary endpoint to tree-report

dashboard/src/api/logViewer.ts, dashboard/src/components/Sheet/LogOrJsonSheetContent.tsx, dashboard/src/locales/messages/index.ts, dashboard/src/utils/constants/log_excerpt_allowed_domain.ts
This PR updates the behavior of the logexcerpt field to support both inline string content and remote file URLs.
In the new schema, the logexcerpt field may be either a string (with content to display directly) or a URL pointing to the file.
This update ensures the UI handles both cases properly by conditionally parsing the value based on its format.
1. Navigate to a tree details page where the logExcerpt field is present
1. Click on any build, boot or test details
1. Confirm that if the logexcerpt is a raw string, it displays as expected
The current production data does not include a logexcerpt as a URL
To test URL handling:
1. Go to `src/components/Sheet/LogOrJsonSheetContent.tsx`
1. Simulate a logexcerpt as a URL by changing the variable `const logExcerpt = logData?.log_excerpt ?? '';` …
=> fix(logviewer): handle logexcerpt as direct content or URL

backend/kernelCI/settings.py, backend/kernelCI_app/queries/checkout.py, backend/kernelCI_app/typeModels/origins.py, backend/kernelCI_app/views/originsView.py
This PR adds a time-based filter to the origin endpoint to ensure only active origins are returned.
Previously, the endpoint returned all origins ever seen in the database, including legacy ones no longer in use.
To address this, a new query parameter interval_in_days was introduced, defaulting to DEFAULT_ORIGIN_LISTING_INTERVAL_IN_DAYS=30, to filter out inactive origins based on recent checkout activity. This default can be modified by a environment variable with the same name.
1. Run the backend and access the /origin endpoint
1. Verify that only origins with recent checkout activity (within the last 30 days) are returned
1. Override the default by passing a custom interval (e.g., ?interval_in_days=1). Test with negative and with no interval_in_days.
1. Confirm that legacy or inactive …
=> feat(api): Add time-based filtering to origin endpoint

README.md, backend/kernelCI/settings.py, backend/kernelCI_app/management/commands/update_db.py, docker-compose.yml
- Adds an environment variable to quick switch between using kcidb and using the new dashboard_db
- Updates de `update_db` management command to make use of this new variable
- Adds a 0-results fallback in the select methods of `update_db` so that they don't try to make the query when they don't need to
If you are running in docker, simply start the dashboard without the `USE_NEW_DB` env var set, check that it is using kcidb, then set it to True in the .env and restart the dashboard; it should now use the local database.
If you are running locally, set the `DASH_DB_` variables as they appear in the backend service of the docker compose, then also try out the `USE_NEW_DB` variable.
Also check if the `update_db` command still works on both scenarios
=> Feat: Add env var to switch to new db

backend/kernelCI_app/management/commands/notifications.py, backend/kernelCI_app/management/commands/templates/test_report.txt.j2
Add status history display to test regression reports using emoji symbols. The history shows the last 10 test results for the same test path, platform, and configuration, displayed as: ✅ → ✅ → ✅ → ✅ → ✅ → ✅ → ✅ → ✅ → ✅ → ❌
=> backend: notifications: Add test status history to test reports

backend/kernelCI_app/constants/localization.py, backend/kernelCI_app/helpers/issueExtras.py, backend/kernelCI_app/queries/issues.py, backend/kernelCI_app/typeModels/issues.py, backend/kernelCI_app/views/issueExtrasView.py, backend/kernelCI_app/views/issueView.py, backend/schema.yml
- Adds issue version to the `first_incident` field
- Fixes problem where adding two issue versions with the same issue id would only return the data for the first one
- Altered the response of the endpoint, if an issue version exists but has no incidents, it will return an object with 0 trees; if it doesn't exist, it will return as null. More comments were added in the code.
Fetch some data from the issue_extras endpoint (I recommend using the [localhost swagger ui](http://localhost:8000/api/schema/swagger-ui/#/issue/issue_extras_create)) and test with issues that exist, that don't exist, that have 0 and more incidents, and other cases.
Also test the dashboard for the issue listing and issue details pages, everything should still be working as before.
Closes #1335
=> Refactor: correct issue extras response

README.md, backend/kernelCI/settings.py
Make CORS_ALLOWED_ORIGINS configurable via environment variable to allow for setting up instances of the dashboard for different domains.
CORS_ALLOW_ALL_ORIGINS is now also configurable via an environment variable, defaulting to 'False'.
Updated README.md with instructions on how to use the new env var.
=> feat(settings): add CORS_ALLOWED_ORIGINS as env var

backend/kernelCI_app/management/commands/helpers/summary.py, backend/kernelCI_app/management/commands/notifications.py, backend/kernelCI_app/routers/databaseRouter.py, backend/kernelCI_cache/migrations/0012_add_checkout_report_identification_fields.py, backend/kernelCI_cache/models.py, backend/kernelCI_cache/queries/notifications.py
Previously we were just saving when a notification was sent, its message id and checkout id. Those fields don't define a report, so we weren't able to discern if a specific report had been sent or not. This knowledge is useful in order to be able to not query for all reports all the time, allowing us to skip heavy reports and only re-send them after some time.
- Added more fields to the NotificationCheckouts table in order to identify a unique report
- Updates old entries with a specific `RunPython` migration piece
- Added check to see which reports where sent in the last 12 hours (possible to change with a global variable)
- Added ability to skip reports that were already sent in that interval, defaulted to true
- Run the migration with `poetry run python3 manage.py migrate …
=> Feat: save sent checkout reports and skip recently sent reports

dashboard/package.json, dashboard/pnpm-lock.yaml
Add new dependency to be able to use the coverage script:
`pnpm coverage`
=> chore: add coverage-v8

backend/kernelCI_app/constants/localization.py, backend/kernelCI_app/typeModels/treeReport.py
When the tree-report query returns a test group that only has 1 test in it, then that means the test can't be classified as neither "regression", "fixed", nor "unstable", so it is discarded. If we allowed test groups of 1 to be returned and group them just by their status, this would allow returning mainline/master's 16k tests at once, not to mention linaro's 100k trees.
Pruning small test groups is the best move for now.
- Increased the param limitation from greater than 0 to greater than 1
- Added better hinting in the param description
- Go to the swagger UI, see the new hint,  and test the tree-report endpoint with a group_size of 1 and more
Closes #1405
=> Fix: tree report group size hint

backend/kernelCI_app/constants/localization.py, backend/kernelCI_app/management/commands/helpers/summary.py, backend/kernelCI_app/typeModels/treeReport.py, backend/kernelCI_app/views/treeReportView.py, backend/schema.yml
- Update tree report response to use `Annotated`
- Include build issues in the tree report
- Closes #1449
=> feat: ensure tree report includes build issues

dashboard/src/components/DebounceInput/DebounceInput.tsx, dashboard/src/components/Table/ConditionalTableCell.tsx, dashboard/src/components/TreeListingPage/TreeTable.tsx, dashboard/src/pages/Hardware/HardwareTable.tsx
- Updated checkout delay to 0.5s.
- Added a new condition to verify the last searched value.
- This ensures that the search bar no longer freezes when searching for trees, issues, or hardware.
- Removed TableCellWithLink for cases where the content already had a link (e.g., boot, build, and test statuses).
- The issue was happening in both hardware and tree views.
- This avoids nested <a> tags that caused hydration errors:
```
table.tsx:117 <a> cannot contain a nested <a>
Status.tsx:98 In HTML, <a> cannot be a descendant of <a>
```
- Closes #1466
- Closes #1470
=> fix: ensure search bar does not freeze 

backend/kernelCI_app/management/commands/notifications.py, backend/kernelCI_app/management/commands/templates/summary.txt.j2, backend/kernelCI_app/queries/notifications.py, backend/kernelCI_app/typeModels/treeReport.py
- Update `kcidb_test_results` to fetch architecture and compiler information for tests
- Take architecture and compiler into account while grouping tests in `evaluate_test_results`
=> Update KCIDB tests grouping

dashboard/src/api/hardwareDetails.ts, dashboard/src/components/Checkbox/IndeterminateCheckbox.tsx, dashboard/src/locales/messages/index.ts, dashboard/src/pages/hardwareDetails/HardwareDetails.tsx, dashboard/src/pages/hardwareDetails/HardwareDetailsFilter.tsx, dashboard/src/pages/hardwareDetails/HardwareDetailsHeaderTable.tsx, dashboard/src/pages/hardwareDetails/Tabs/HardwareDetailsTabs.tsx, dashboard/src/routes/_main/hardware/$hardwareId/route.tsx
Users must deselect all hardware details trees at once.
When no trees are selected, a message is displayed to inform the user that no tree has been selected.
- Closes #614 
https://github.com/user-attachments/assets/04871913-37f1-4fa7-a1ab-f93ccb3c28e6
Go to hardware section and choose once to see the details, deselect all trees
=> feat: ensure all hardware details trees can be deslected

.env.backend.example, backend/kernelCI/settings.py, backend/kernelCI_app/helpers/system.py, backend/kernelCI_app/management/commands/notifications.py
- Refactored notification conditions so that it only runs on production or dev environments instead of only on staging;
- Removed now unecessary is_production_instance function;
- Refactored getting email env vars in settings and added them to the example env;
- Slightly increased the default timeout for both databases.
The changes are mostly code-only, but you can test them by running the notifications command.
=> Feat: improve notifications code
