README.md
backend/README.md
backend/kernelCI/settings.py
backend/poetry.lock
backend/pyproject.toml
dashboard/.env
dashboard/.env.example
dashboard/.gitignore
dashboard/README.md

- configure cors for local development
-  remove `.env` file and add `.env.example`
- update README

Fix: configure cors for local development

---

dashboard/src/components/TreeListingPage/TreeListingPage.tsx
dashboard/src/lib/utils/vite.ts
dashboard/src/main.tsx

this uses session storage for dev which is a little more friendly and also add error handling for the tree listing

fix: use session storage for dev

---

backend/docs/database-logic.md

- update database-logic.md doc
close #64

feat: update database-logic.md doc

---

dashboard/src/components/Tabs/Boots/BootsTab.tsx
dashboard/src/locales/messages/index.ts

- change the success label that was wrong

Fix: error chart label

---

.github/workflows/ci.yaml

This patch adds a new job triggered by push events to branch "main".
It is currently set to run after all other checks completed successfully. Its dependency list might need to be extended if there are new checks introduced.
Closes: #82

cicd: Update staging after each merged PR

---

.gitignore
backend/kernelCI_app/views/treeDetailsView.py
dashboard/src/components/Summary/Summary.tsx
dashboard/src/pages/TreeDetails/TreeDetailsFilter.tsx

- fix: double tbody was breaking the Summary UI 
- fix: typos
- feat: update .gitignore with .vscode

fix: general issues

---

dashboard/src/components/Accordion/Accordion.tsx
dashboard/src/components/Accordion/BuildAccordionContent.tsx
dashboard/src/components/Tabs/Tabs.tsx

- closes #21 
- add a background color to accordion content
- fix the position of show more button in accordion content
- remove blue background of the tabs

Fix: add background color to accordion content

---

dashboard/src/locales/messages/index.ts
dashboard/src/pages/BuildDetails/BuildDetails.tsx
dashboard/src/pages/TreeDetails/TreeDetails.tsx

fix(#110): change tree to revisions in breadcrumb

---

dashboard/src/components/ListingItem/ListingItem.tsx
dashboard/src/pages/TreeDetails/Tabs/TestCards.tsx

fix(#111): remove quantity from platforms failing at boot

---

dashboard/src/hooks/usePagination.tsx
dashboard/src/locales/messages/index.ts
dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx
dashboard/src/pages/TreeDetails/Tabs/Build/BuildTab.tsx
dashboard/src/pages/TreeDetails/TreeDetails.tsx
dashboard/src/pages/TreeDetails/TreeDetailsFilter.tsx

fix: remove branch and revision from filter drawer

---

dashboard/src/components/Table/TreeTable.tsx
dashboard/src/components/Table/tableUtils.ts
dashboard/src/components/TreeListingPage/TreeListingPage.tsx
dashboard/src/pages/TreeDetails/TreeDetails.tsx
dashboard/src/routes/~tree/~$treeId/~index.tsx
dashboard/src/types/tree/Tree.tsx
dashboard/src/types/tree/TreeDetails.tsx

- add trees information in the url
- get those information to fill the tree header with real data

Feat: complete header with real data

---

backend/kernelCI_app/views/testsByTreeAndCommitHashView.py
dashboard/src/components/Table/TestsTable.tsx
dashboard/src/types/tree/TreeDetails.tsx

- closes #148 
- add start time and duration to tests table
- add right chevron
- sort by path

Feat: adjust test table rows

---

.gitignore
backend/kernelCI_app/views/treeView.py
dashboard/src/components/Table/TreeTable.tsx
dashboard/src/locales/messages/index.ts

Changing SQL and frontend in order to concatenate commit hash and tag.
Closes #167

feat(dashboard): adding tag to commit hash

---

backend/kernelCI_app/urls.py
backend/kernelCI_app/views/testsByCommitHashView.py
backend/kernelCI_app/views/testsByTreeAndCommitHashView.py
backend/requests/test-details-get.sh
dashboard/src/api/TestDetails.tsx
dashboard/src/api/TreeDetails.tsx
dashboard/src/components/Table/TestsTable.tsx
dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx
dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTab.tsx

- closes #145 
- update query to get information from boots and without boots] 
- add boots details table in boots tab

Feat: add boots table

---

dashboard/src/types/tree/Tree.tsx

kernelci origin removed from list at Tree.tsx
Closes #119

fix(dashboard): remove kernelci origin

---

backend/kernelCI_app/serializers.py
backend/kernelCI_app/views/treeView.py
dashboard/src/components/SideMenu/SideMenu.tsx
dashboard/src/components/Table/TreeTable.tsx
dashboard/src/pages/TreeDetails/TreeDetails.tsx

there was an error on implementation that was breaking links to tree details.
Closes #167

fix(dashboard): fixing implementation of feat #167

---

dashboard/src/locales/messages/index.ts
dashboard/src/pages/TreeDetails/TreeDetailsFilter.tsx
dashboard/src/types/tree/TreeDetails.tsx

- It was removed before, but was brought back in a rebase/conflict resolution

fix: remove branch filter

---

backend/kernelCI_app/views/testsByTreeAndCommitHashView.py
dashboard/src/components/Table/TestsTable.tsx
dashboard/src/types/tree/TreeDetails.tsx

- closes #148 
- add: start time and duration
- remove id, compiler and arch

Feat: adjust test table columns

---

backend/kernelCI_app/views/testDetailsView.py
backend/requests/test-details-get.sh
dashboard/src/pages/TestDetails/TestDetails.tsx
dashboard/src/pages/TestDetails/TestDetailsTable.tsx
dashboard/src/types/tree/TestDetails.tsx

- fix: request/test-details-get.sh was using a wrong path
- fix: remove TestDetails chart
- feat: remove commented code
Close #143

Fix: remove chat from testDetails page

---

backend/kernelCI_app/views/testsByTreeAndCommitHashView.py
dashboard/src/types/tree/TreeDetails.tsx

- also fix the TestByCommitHash type
Close #189

fix: undefined TreeId when navigation to TestDetailsPage

---

dashboard/src/components/ListingContent/ListingContent.tsx
dashboard/src/components/ListingItem/ListingItem.tsx
dashboard/src/components/Summary/Summary.tsx
dashboard/src/pages/TreeDetails/TreeDetails.tsx
dashboard/src/types/tree/TreeDetails.tsx

- also fix TreeDetails types
Close #141

fix: add unknown status on build status cards

---

dashboard/src/components/Skeleton/Skeleton.tsx
dashboard/src/components/Skeleton/index.tsx
dashboard/src/components/Table/TreeTable.tsx
dashboard/src/components/TreeListingPage/TreeListingPage.tsx
dashboard/src/pages/TestDetails/TestDetails.tsx
dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx
dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTab.tsx
dashboard/src/pages/TreeDetails/TreeDetails.tsx
dashboard/src/pages/TreeDetails/TreeDetailsFilter.tsx

feat(dashboard): loading message for tree listing and builds tab

---

dashboard/src/components/Table/TestsTable.tsx
dashboard/src/pages/TreeDetails/Tabs/Build/BuildTab.tsx
dashboard/src/types/tree/TreeDetails.tsx

Feat: filter status (unknown and test)

---

dashboard/src/components/Skeleton/Skeleton.tsx
dashboard/src/components/TreeListingPage/TreeListingPage.tsx
dashboard/src/index.css
dashboard/src/locales/messages/index.ts

feat(dashboard): empty state for tree listing

---

dashboard/src/components/Table/TestsTable.tsx

showing "Loading..." message for tests statistics at the bottom of Tests tab.
Added a loading placeholder.
Closes #211

fix(dashboard): showing "Loading..." message for tests

---

backend/kernelCI_app/views/treeTestsView.py

fix: wrong parameters passed to test and boot query

---

dashboard/src/pages/TreeDetails/Tabs/Build/BuildTab.tsx

Removing duplication on Configs section at tree details.
Closes #210

fix(dashboard): fixing Configs on tree details

---

dashboard/src/components/Accordion/Accordion.tsx
dashboard/src/components/Skeleton/Skeleton.tsx
dashboard/src/index.css

Implements component ChevronRightAnimate, that detects click. 
Piggybacking: putting Skeleton css class inside its folder.
Closes #208

feat(dashboard): accordion chevron turning when clicked

---

dashboard/src/components/ColoredCircle/ColoredCircle.tsx

- Adjusted the padding and text size for better alignment
- Removed redundant span element around quantity

feat(ui): update ColoredCircle styles for better alignment

---

dashboard/src/components/Button/ButtonWithIcon.tsx
dashboard/src/components/Checkbox/Checkbox.tsx
dashboard/src/components/Filter/Drawer.tsx
dashboard/src/pages/TreeDetails/TreeDetails.tsx

- make the filter button match the design
-  fix Drawer error "DialogContent requires a DialogTitle" 
-  fix warning "Missing Description or aria-describedby={undefined}"
- fix error indicating that a form input requires an onChange handler

Fix: Some issues related to filter button and drawer

---

backend/kernelCI_app/views/treeCommitsHistory.py

Optimize commit graph with a lot of CTEs
Go to the broonie sound and see how long it takes to load:
http://localhost:5173/tree/77212f300bfd6fb3edaabd1daf863cabb521854a?tableFilter=%7B%22buildsTable%22%3A%22all%22%2C%22bootsTable%22%3A%22all%22%2C%22testsTable%22%3A%22all%22%7D&origin=maestro&currentTreeDetailsTab=treeDetails.builds&diffFilter=%7B%7D&treeInfo=%7B%22gitBranch%22%3A%22for-linus%22%2C%22gitUrl%22%3A%22https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Fbroonie%2Fsound.git%22%2C%22treeName%22%3A%22broonie-sound%22%2C%22commitName%22%3A%22asoc-fix-v6.11-rc3-15-g77212f300bfd6%22%2C%22headCommitHash%22%3A%2277212f300bfd6fb3edaabd1daf863cabb521854a%22%7D

feat(commit-graph): optimize query

---

dashboard/src/components/SideMenu/SideMenu.tsx
dashboard/src/components/UnderDevelopment/UnderDevelopment.tsx
dashboard/src/components/UnderDevelopment/index.tsx
dashboard/src/locales/messages/index.ts
dashboard/src/routeTree.gen.ts
dashboard/src/routes/devices.tsx
dashboard/src/routes/labs.tsx

- shows "Under Development" message when "Devices" and "Labs" labels
are clicked
- labels change when clicked
Closes https://github.com/kernelci/dashboard/issues/223

feat(dashboard): "Under Development" message

---

dashboard/src/components/SideMenu/SideMenu.tsx
dashboard/src/routes/index.tsx

- fix: SideMenuItem selected style when navigate child routes

fix: selected route

---

dashboard/src/pages/TreeDetails/Tabs/Build/BuildTab.tsx
dashboard/src/pages/TreeDetails/Tabs/TestCards.tsx

Configs card on Builds, Boots and Tests now showing Success, Failed and Inconclusive statuses.
Closes #252

feat(dashboard): fixing Configs card on 3 Tabs

---

dashboard/src/components/Accordion/Accordion.tsx
dashboard/src/components/Table/TestsTable.tsx
dashboard/src/types/general.ts

- Use the right key for the accordion

fix(accordion-test-content): use the right key

---

backend/kernelCI_app/utils.py
backend/kernelCI_app/views/groupedTestsView.py
backend/kernelCI_app/views/treeDetailsView.py
backend/utils/validation.py
dashboard/src/api/TreeDetails.tsx

- Added origin, git_url, and git_branch parameters to TreeDetails API.
- Updated TreeDetails view to validate the presence of these parameters.
- Modified TreeDetails.tsx to include these parameters in the API request.
- Added utility functions to handle search parameters and assertions.
Closes: https://github.com/kernelci/dashboard/issues/271

feat: add query parameters to TreeDetails API

---

dashboard/src/components/Table/TreeTable.tsx

Fixing date format at main table and tooltip
Closes #293

fix(dashboard): use Date class on main table

---

dashboard/src/components/Filter/CodeBlock.tsx
dashboard/src/locales/messages/index.ts

Removed tooltip on codeblock because it was conflicting with slider

Fix: highlight tooltip

---

dashboard/src/components/Accordion/Accordion.tsx
dashboard/src/components/SideMenu/NavLink.tsx
dashboard/src/components/SideMenu/SendFeedback.tsx
dashboard/src/components/SideMenu/SideMenu.tsx
dashboard/src/components/Summary/Summary.tsx
dashboard/src/components/Table/BaseTable.tsx
dashboard/src/components/Table/BootsTable.tsx
dashboard/src/components/Table/TreeTable.tsx
dashboard/src/components/ui/table.tsx
dashboard/src/pages/TreeDetails/Tabs/Build/BuildTab.tsx
dashboard/src/pages/TreeDetails/Tabs/TestCards.tsx
dashboard/src/pages/TreeDetails/TreeDetailsFilterLink.tsx
dashboard/src/pages/TreeDetails/treeDetailsUtils.ts

Creating a new component to allow opening a new tab.
Test on the /tree route

create a new component HandleLink and use with TableCell

---

dashboard/src/components/SideMenu/SideMenu.tsx
dashboard/src/routeTree.gen.ts
dashboard/src/routes/labs.tsx

- remove Labs entry on SideMenu and /labs path
Close #399 
| ![image](https://github.com/user-attachments/assets/3271a5bf-0bc5-4bee-b925-183d0345ab86) | ![image](https://github.com/user-attachments/assets/27a6b7f6-d22a-4c9f-b3a0-547f1818df04) |

feat: remove Labs entry on SideMenu and /labs path

---

dashboard/src/components/Table/TestsTable.tsx

fix: TestsTable was not counting null tests

---

dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTable.tsx
dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTable.tsx

| Before | ![image](https://github.com/user-attachments/assets/db381a5b-a043-4d92-a784-5db19035c715) |
| After | ![image](https://github.com/user-attachments/assets/f7ecf444-1c61-443c-b541-7f465c235ec8) |

fix: TableFilter alignment

---

backend/kernelCI_app/views/treeDetailsSlowView.py
dashboard/src/locales/messages/index.ts
dashboard/src/pages/TreeDetails/Tabs/Tests/IndividualTestsTable.tsx
dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTable.tsx
dashboard/src/types/general.ts
dashboard/src/types/tree/TreeDetails.tsx

add hardware column in tests table
- Closes #408

feat: add hardware column in tests table

---

dashboard/src/components/SideMenu/SideMenu.tsx
dashboard/src/locales/messages/index.ts
dashboard/src/routeTree.gen.ts
dashboard/src/routes/hardware.tsx

| ![image](https://github.com/user-attachments/assets/9689c180-7e4c-421e-ab10-24acf4922ecd) | ![image](https://github.com/user-attachments/assets/b2ec0073-74c8-423b-b45b-455a18cbf435) |

feat: rename Devices side menu entry to Hardware

---

backend/kernelCI_app/models.py
backend/kernelCI_app/views/buildTestsView.py
backend/requests/build-tests-get.sh

Show hardware list in test table on BuildDetails page
Close #449 
| Before | ![image](https://github.com/user-attachments/assets/075405d4-e994-493d-9985-aaaed3ae4498) |
| After |  ![image](https://github.com/user-attachments/assets/13a371a7-e1c8-4489-8461-dd90b6713bf4) |

feat: return hardware listing on buildTests endpoint

---

backend/kernelCI_app/views/treeView.py

| Old | New |
| ----- | ------ |
| ![Screenshot from 2024-10-29 11-36-57](https://github.com/user-attachments/assets/dadf1e94-8eb0-4f6b-8244-656903a7c292) | ![Screenshot from 2024-10-29 11-37-58](https://github.com/user-attachments/assets/695ee2a8-a17f-4742-86e4-028f080fe083) |
Close #469

Fix count of tests in TreeListing Page

---

dashboard/src/hooks/useToast.tsx
dashboard/src/pages/TreeDetails/Tabs/CommitNavigationGraph.tsx
dashboard/src/routeTree.gen.ts
dashboard/src/routes/hardware.tsx
dashboard/src/routes/hardware/$hardwareId/boot/$bootId/index.tsx
dashboard/src/routes/hardware/$hardwareId/boot/index.tsx
dashboard/src/routes/hardware/$hardwareId/boot/route.tsx
dashboard/src/routes/hardware/$hardwareId/build/$buildId/index.tsx
dashboard/src/routes/hardware/$hardwareId/build/index.tsx
dashboard/src/routes/hardware/$hardwareId/build/route.tsx
dashboard/src/routes/hardware/$hardwareId/index.tsx
dashboard/src/routes/hardware/$hardwareId/route.tsx
dashboard/src/routes/hardware/$hardwareId/test/$testId/index.tsx
dashboard/src/routes/hardware/$hardwareId/test/index.tsx
dashboard/src/routes/hardware/$hardwareId/test/route.tsx
dashboard/src/routes/hardware/index.tsx
dashboard/src/routes/hardware/route.tsx

I generate this routes:
- /hardware
- /hardware/$hardware
- /hardware/$hardware/boot
- /hardware/$hardware/boot/$bootId
- /hardware/$hardware/build
- /hardware/$hardware/build/$buildId
- /hardware/$hardware/test
- /hardware/$hardware/test/$testId

Create hardware routes in frontend

---

dashboard/src/components/BootsTable/BootsTable.tsx
dashboard/src/components/BuildDetails/BuildDetails.tsx
dashboard/src/components/BuildDetails/BuildDetailsTestSection.tsx
dashboard/src/components/BuildsTable/BuildsTable.tsx
dashboard/src/components/TestsTable/IndividualTestsTable.tsx
dashboard/src/components/TestsTable/TestsTable.tsx
dashboard/src/pages/HardwareBuildDetails/HardwareBuildDetails.tsx
dashboard/src/pages/TreeBuildDetails/TreeBuildDetails.tsx
dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx
dashboard/src/pages/TreeDetails/Tabs/Build/BuildAccordionContent.tsx
dashboard/src/pages/TreeDetails/Tabs/Build/TreeDetailsBuildsTable.tsx
dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTab.tsx
dashboard/src/pages/hardwareDetails/HardwareDetails.tsx
dashboard/src/pages/hardwareDetails/Tabs/Boots/BootsTab.tsx
dashboard/src/pages/hardwareDetails/Tabs/Build/BuildTab.tsx
dashboard/src/pages/hardwareDetails/Tabs/Build/HardwareDetailsBuildsTable.tsx
dashboard/src/pages/hardwareDetails/Tabs/HardwareDetailsTabs.tsx
dashboard/src/pages/hardwareDetails/Tabs/Tests/HardwareDetailsTestsTable.tsx
dashboard/src/pages/hardwareDetails/Tabs/Tests/TestsTab.tsx
dashboard/src/routes/hardware/$hardwareId/build/$buildId/index.tsx
dashboard/src/routes/hardware/route.tsx
dashboard/src/types/tree/TreeDetails.tsx

Close #517 #521 
from HardwareDetails page try navigate to BuildDetails and TestsDetails page

fix: hardwareDetails navigation

---

dashboard/src/components/BootsTable/BootsTable.tsx
dashboard/src/components/BuildsTable/BuildsTable.tsx
dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx
dashboard/src/pages/TreeDetails/Tabs/Build/TreeDetailsBuildsTable.tsx
dashboard/src/pages/hardwareDetails/Tabs/Boots/BootsTab.tsx
dashboard/src/pages/hardwareDetails/Tabs/Build/HardwareDetailsBuildsTable.tsx
dashboard/src/pages/hardwareDetails/Tabs/Tests/TestsTab.tsx
dashboard/src/routes/hardware/$hardwareId/route.tsx

- remove filters and onClickFilter logic from Boots/Builds/Tests Table
- put this logic in corresponding Tab Page
- update Tree Details Tab with this same logic
Close #518

Fix Datatable Filters on Hardware Details.

---

dashboard/src/api/Hardware.tsx
dashboard/src/components/SideMenu/SideMenu.tsx
dashboard/src/pages/Hardware/InputTime.tsx
dashboard/src/pages/hardwareDetails/HardwareDetails.tsx
dashboard/src/routes/hardware/$hardwareId/route.tsx
dashboard/src/routes/hardware/route.tsx
dashboard/src/types/tree/TreeDetails.tsx

reset query parameters on side menu link

fix: uncollide rest parameters on sidebar

---

dashboard/src/components/BuildsTable/BuildsTable.tsx
dashboard/src/components/Filter/CodeBlock.tsx
dashboard/src/components/LinkGroup/LinkGroup.tsx
dashboard/src/components/LinkWithIcon/LinkWithIcon.tsx
dashboard/src/components/ui/dialog.tsx
dashboard/src/locales/messages/index.ts
dashboard/src/pages/TreeDetails/Tabs/Build/BuildAccordionContent.tsx
dashboard/src/pages/TreeDetails/Tabs/LogSheet.tsx

- Part of #444
These changes include:
- increase height
- add log in full screen
- improve navigation
- fix error quantity
To put the code block in full screen, I just added a dialog and a trigger button on top left. With these changes, I also increased the height.

Refactor: log viewer

---

backend/kernelCI_app/constants/general.py
backend/kernelCI_app/views/hardwareView.py
backend/requests/hardware-listing-fast.sh
backend/requests/hardware-listing-slow.sh
dashboard/src/api/Hardware.tsx
dashboard/src/components/TopBar/TopBar.tsx
dashboard/src/components/TreeListingPage/TreeTable.tsx
dashboard/src/routes/__root.tsx
dashboard/src/routes/tree/$treeId/route.tsx
dashboard/src/routes/tree/route.tsx
dashboard/src/types/general.ts
dashboard/src/types/tree/Tree.tsx

Add origin to hardware listing page
Go to hardware listing and change origins, double check the query to see if it is a where parameter
Closes #528

feat:hardware listing origin limit

---

backend/kernelCI_app/views/hardwareDetailsView.py
dashboard/src/api/hardwareDetails.ts
dashboard/src/pages/hardwareDetails/HardwareDetails.tsx

- feat: add filter by origin to hardwareDetail endpoint 
- feat: add query cache to hardwareDetails endpoint 
- refactor: create tree obj only when needed
Close #531 #535

feat: add filter by origin to HardwareDetails

---

backend/kernelCI_app/views/hardwareDetailsView.py
dashboard/src/api/hardwareDetails.ts
dashboard/src/pages/hardwareDetails/HardwareDetails.tsx

- feat: add startTimestamp and endTimestamp filters to hardwareDetails
Close #532

feat: add time filter to hardwareDetails endpoint

---

dashboard/src/components/Cards/IssuesList.tsx
dashboard/src/components/Issue/IssueSection.tsx
dashboard/src/components/ListingItem/ListingItem.tsx
dashboard/src/pages/TreeDetails/Tabs/TestCards.tsx

Add tooltip in issues list to show full text.
Close #547

Show full text in issues

---

dashboard/src/components/BootsTable/BootsTable.tsx
dashboard/src/components/BuildsTable/BuildsTable.tsx
dashboard/src/components/Table/PaginationInfo.tsx
dashboard/src/components/TestsTable/TestsTable.tsx
dashboard/src/components/TreeListingPage/TreeTable.tsx
dashboard/src/pages/Hardware/HardwareTable.tsx
dashboard/src/pages/TreeDetails/Tabs/Build/TreeDetailsBuildsTable.tsx
dashboard/src/pages/hardwareDetails/HardwareDetailsHeaderTable.tsx
dashboard/src/pages/hardwareDetails/Tabs/Build/HardwareDetailsBuildsTable.tsx

- make filters affect counts in datatables header
Close #466

Fix counts datatables

---

dashboard/src/components/BootsTable/BootsTable.tsx
dashboard/src/components/BuildsTable/BuildsTable.tsx
dashboard/src/components/Filter/CodeBlock.tsx
dashboard/src/components/TestsTable/IndividualTestsTable.tsx

- increase fullscreen button margin left
- add a highlight in select item show in log viewer
Close #540

Log Viewer Improvements

---

backend/kernelCI_app/views/hardwareDetailsView.py

feat: make hardwareDetails endpoint use only the tree heads

---

backend/kernelCI_app/views/hardwareDetailsView.py

The way the unknown issues counter was implemented, it could update tests_or_boots when it was out of scope, causing the backend to throw and exception. This implementation solves.

fix: tests_or_boots out of scope

---

backend/kernelCI_app/views/hardwareDetailsView.py
dashboard/src/components/Filter/Drawer.tsx
dashboard/src/components/ListingItem/ListingItem.tsx
dashboard/src/components/Tabs/Builds/BuildCards.tsx
dashboard/src/components/Tabs/Builds/ConfigsCard.tsx
dashboard/src/components/Tabs/FilterLink.tsx
dashboard/src/components/Tabs/Summary.tsx
dashboard/src/components/Tabs/Tests/ConfigsList.tsx
dashboard/src/components/Tabs/Tests/ErrorsSummary.tsx
dashboard/src/pages/hardwareDetails/HardwareDetailsFilter.tsx
dashboard/src/pages/hardwareDetails/Tabs/Boots/BootsTab.tsx
dashboard/src/pages/hardwareDetails/Tabs/Build/BuildTab.tsx
dashboard/src/pages/hardwareDetails/Tabs/Tests/TestsTab.tsx
dashboard/src/types/hardware/hardwareDetails.ts

Add, in hardware details, filters by:
- compilers
- archs
- configs
Select a hardware and go to hardware details. Open the filters modal and try apply filters.

Feat: add filters in hardware details

---

backend/kernelCI_app/views/treeView.py

Change the SQL query in the TreeView. Before It was considering only the latest checkout when counting the status por builds, boots and tests that was causing some status to be incorrect. This new query groups the rows by the commit hash instead of the checkout ID so multiple checkouts that correspond to the same tree now are used when counting the status, returning the correct value
Closes #605
Before
After

fix(treeView): fix sql query to get correct status

---

dashboard/src/components/Filter/CheckboxSection.tsx
dashboard/src/components/Tabs/Filters.tsx
dashboard/src/locales/messages/index.ts
dashboard/src/pages/hardwareDetails/HardwareDetails.tsx
dashboard/src/pages/hardwareDetails/HardwareDetailsFilter.tsx
dashboard/src/pages/hardwareDetails/HardwareDetailsHeaderTable.tsx

- create tree section filter
- use treeIndexes query params to filter hardware
Close #447

Feat: add tree filter in modal hardware

---

dashboard/package.json
dashboard/pnpm-lock.yaml
dashboard/src/components/Breadcrumb/Breadcrumb.stories.tsx
dashboard/src/components/Breadcrumb/Breadcrumb.tsx
dashboard/src/routes/hardware/$hardwareId/build/$buildId/index.tsx
dashboard/src/routes/hardware/$hardwareId/test/$testId/index.tsx
dashboard/src/routes/index.tsx
dashboard/src/routes/tree/$treeId/build/$buildId/index.tsx
dashboard/src/routes/tree/$treeId/test/$testId/index.tsx

Closes #658
Navigate the pages of the dashboard and add, remove filters and any other actions that change the URL to verify that the behaviour and URL is the same as it was before.

feat: update tanstack/react-router to v1.87.1

---

backend/docs/caveats.md
backend/kernelCI_app/helpers/trees.py
backend/kernelCI_app/views/hardwareDetailsView.py
backend/kernelCI_app/views/hardwareView.py
dashboard/src/api/hardwareDetails.ts
dashboard/src/locales/messages/index.ts
dashboard/src/pages/Hardware/HardwareListingPage.tsx
dashboard/src/pages/Hardware/HardwareTable.tsx
dashboard/src/pages/hardwareDetails/HardwareDetails.tsx
dashboard/src/routes/hardware/$hardwareId/route.tsx
dashboard/src/utils/date.ts

Reduce the difference between listing and hardware details
Part of #577

feat(tree-listing): reduce difference between listing and hardware

---

.github/workflows/ci.yaml

Changed the ci.yaml file to run the frontend unit tests before building it
Part of #375

feat: update CI actions to run unit tests

---

backend/kernelCI_app/views/hardwareDetailsView.py
dashboard/src/components/Cards/CompatibleHardware.tsx
dashboard/src/locales/messages/index.ts
dashboard/src/pages/hardwareDetails/HardwareDetails.tsx
dashboard/src/types/hardware/hardwareDetails.ts

feat(HardwareDetails): add card with compatibles

---

docs/filters.md

Just some rules explaining how the filters should work

docs: add filter rules

---

backend/kernelCI_app/views/treeCommitsHistory.py

Filter by issues affect the history commit chart
Close #677 
Go to a tree with issues and try filter by that. Try navigate by the chart

Filter commit history chart by issues

---

dashboard/src/components/BuildDetails/BuildDetails.tsx
dashboard/src/locales/messages/index.ts

feat(BuildDetails): add build id value

---

backend/kernelCI_app/urls.py
backend/requests/test-details-get.sh
dashboard/src/api/testDetails.ts

Refactor: Rename double routes

---

backend/kernelCI_app/models.py
backend/kernelCI_app/serializers.py
backend/kernelCI_app/typeModels/hardwareDetails.py
backend/kernelCI_app/views/buildDetailsView.py
backend/kernelCI_app/views/hardwareDetailsCommitHistoryView.py
backend/kernelCI_app/views/hardwareDetailsView.py
backend/kernelCI_app/views/testDetailsView.py
backend/kernelCI_app/views/treeDetailsView.py
backend/kernelCI_app/views/treeView.py
backend/kernelCI_app/views/treeViewFast.py
dashboard/src/components/BuildDetails/BuildDetails.tsx
dashboard/src/components/TestDetails/TestDetails.tsx
dashboard/src/components/Tooltip/CommitTagTooltip.tsx
dashboard/src/components/TreeListingPage/TreeListingPage.tsx
dashboard/src/components/TreeListingPage/TreeTable.tsx
dashboard/src/locales/messages/index.ts
dashboard/src/pages/TreeDetails/TreeDetails.tsx
dashboard/src/pages/hardwareDetails/HardwareDetailsHeaderTable.tsx
dashboard/src/types/hardware/hardwareDetails.ts
dashboard/src/types/tree/BuildDetails.tsx
dashboard/src/types/tree/TestDetails.tsx
dashboard/src/types/tree/Tree.tsx
dashboard/src/types/tree/TreeDetails.tsx

Closes #697 
- Check if the commit tags are following the logic described in #697. 
Example page (Tree Details): http://localhost:5173/tree/f4592015c1a994f1a92fa984bd008924e88f6c3a?treeInfo%7CcommitName=renesas-devel-2025-01-06-v6.13-rc6&treeInfo%7CgitBranch=master&treeInfo%7CgitUrl=https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Fgeert%2Frenesas-devel.git&treeInfo%7CheadCommitHash=f4592015c1a994f1a92fa984bd008924e88f6c3a&treeInfo%7CtreeName=renesas
Example page (Hardware Details): http://localhost:5173/hardware/radxa%2Crock-5b?et=1736541000&hs=radxa&st=1736109000
Tree Listing Page
Tree Details
Hardware Details
Build Details
Test Details

Add priority logic to commit tag

---

backend/kernelCI_app/views/buildDetailsView.py
backend/kernelCI_app/views/buildTestsView.py
backend/kernelCI_app/views/hardwareDetailsCommitHistoryView.py
backend/kernelCI_app/views/hardwareDetailsView.py
backend/kernelCI_app/views/hardwareView.py
backend/kernelCI_app/views/issueDetailsBuildsView.py
backend/kernelCI_app/views/issueDetailsTestsView.py
backend/kernelCI_app/views/issueDetailsView.py
backend/kernelCI_app/views/issuesView.py
backend/kernelCI_app/views/logDownloaderView.py
backend/kernelCI_app/views/testDetailsView.py
backend/kernelCI_app/views/treeCommitsHistory.py
backend/kernelCI_app/views/treeDetailsView.py
backend/kernelCI_app/views/treeView.py
backend/kernelCI_app/views/treeViewFast.py
backend/test.patch
dashboard/src/api/issueDetails.ts
dashboard/src/components/BuildDetails/BuildDetails.tsx
dashboard/src/components/CommitNavigationGraph/CommitNavigationGraph.tsx
dashboard/src/components/Issue/IssueSection.tsx
dashboard/src/components/IssueDetails/IssueDetails.tsx
dashboard/src/components/IssueDetails/IssueDetailsBuildSection.tsx
dashboard/src/components/IssueDetails/IssueDetailsTestSection.tsx
dashboard/src/components/TestDetails/TestDetails.tsx
dashboard/src/components/TreeListingPage/TreeListingPage.tsx
dashboard/src/pages/Hardware/HardwareListingPage.tsx
dashboard/src/pages/TreeDetails/TreeDetails.tsx
dashboard/src/pages/hardwareDetails/HardwareDetails.tsx
dashboard/src/types/issueDetails.ts

- return status code 404 when no data was found
- tree/hardware/test/builds details
- tree/hardware listing
- commit history charts
- use SectionError component to catch the error message
Close #695

Status report when no data is found

---

dashboard/src/pages/hardwareDetails/HardwareDetailsHeaderTable.tsx
dashboard/src/pages/hardwareDetails/Tabs/HardwareCommitNavigationGraph.tsx

From this discussion on discord: https://discord.com/channels/1245820301053530313/1328777374296440923
Closes #757

fix(hardware-details): update treeCommits source

---

backend/kernelCI_app/helpers/hardwareDetails.py
backend/kernelCI_app/typeModels/commonDetails.py

Feat: Add invisible fields in hardware tests

---

dashboard/src/components/Filter/CodeBlock.tsx

Fix: Increase fullscreen mode height

---

backend/kernelCI_app/helpers/treeDetails.py

fix staging crash by importing the right variable

fix: staging crash

---

dashboard/src/components/ListingItem/ListingItem.tsx

Fix: truncate long issue id

---

.github/workflows/ci.yaml

Force version `9.15.2` for `pnpm`

fix: pnpm version

---

backend/kernelCI_app/views/testDetailsView.py
dashboard/src/components/BuildsTable/BuildsTable.tsx
dashboard/src/components/Status/Status.tsx
dashboard/src/components/Table/TableStatusFilter.tsx
dashboard/src/components/TestDetails/TestDetails.tsx
dashboard/src/components/TreeListingPage/TreeTable.tsx
dashboard/src/locales/messages/index.ts
dashboard/src/pages/Hardware/HardwareTable.tsx
dashboard/src/types/tree/TestDetails.tsx

This PR solves these sub-issues from Kevin's feedback:
#820

Feat: address most of kevin feedback

---

dashboard/src/components/BuildDetails/BuildDetails.tsx
dashboard/src/components/Cards/IssuesList.tsx
dashboard/src/components/Icons/Link.tsx
dashboard/src/components/Icons/LogView.tsx
dashboard/src/components/LinkWithIcon/LinkWithIcon.tsx
dashboard/src/components/Section/Section.tsx
dashboard/src/components/TestDetails/TestDetails.tsx
dashboard/src/locales/messages/index.ts

- Remove icons from fields that aren't clickable
- Change logs icon to a different one, made it larger and added a tooltip to the icon
- Added underline and hover text colors to all clickable fields
Closes #806
Before
After

Fix: Update Icons and Log Visibility

---

backend/kernelCI_app/helpers/hardwareDetails.py
backend/kernelCI_app/typeModels/databases.py
backend/kernelCI_app/typeModels/hardwareDetails.py
backend/kernelCI_app/typeModels/issueDetails.py
backend/kernelCI_app/views/hardwareDetailsBootsView.py
backend/kernelCI_app/views/hardwareDetailsTestsView.py
backend/kernelCI_app/views/hardwareDetailsView.py
backend/kernelCI_app/views/issueDetailsBuildsView.py
backend/kernelCI_app/views/issueDetailsTestsView.py
backend/requests/hardware-details-boots-post.sh
backend/requests/hardware-details-tests-post.sh
backend/requests/issue-details-builds-get.sh
backend/requests/issue-details-tests-get.sh
backend/schema.yml
dashboard/src/components/BootsTable/BootsTable.tsx
dashboard/src/components/IssueDetails/IssueDetailsBuildSection.tsx
dashboard/src/components/IssueDetails/IssueDetailsTestSection.tsx
dashboard/src/components/TestsTable/TestsTable.tsx
dashboard/src/pages/hardwareDetails/Tabs/Boots/HardwareDetailsBootsTable.tsx
dashboard/src/pages/hardwareDetails/Tabs/Tests/HardwareDetailsTestsTable.tsx
dashboard/src/types/general.ts
dashboard/src/types/tree/TreeDetails.tsx
dashboard/src/utils/table.ts
dashboard/src/utils/utils.ts

- Added tree/branch column to tests/boots tables in hardware details
- Added tree/branch column to builds/tests tables in issue details
- Although there's a tests table in build details, since each build can only be associated with one tree/branch the column was not added there
Closes #852

Feat: add tree to tests table

---

dashboard/tsconfig.json

Closes #323
- Check if `pnpm build` runs correctly
- Navigate through the application and check that nothing is broken

chore: add noUncheckedIndexedAccess to tsconfig

---

dashboard/src/components/TestDetails/TestDetails.tsx
dashboard/src/components/ui/dialog.tsx
dashboard/src/components/ui/sheet.tsx
dashboard/src/components/ui/toast.tsx

Tailwind migration didn't go as smooth as possible, this fixes by using
some utility functions that is covered by our css file
Closes #923

fix(animations): animation across the app

---

dashboard/src/components/Cards/IssuesList.tsx
dashboard/src/index.css
dashboard/src/locales/messages/index.ts

Closes #941 
Based on this generated code: https://css-generators.com/starburst-shape/
**Important:** This solution uses [clip-path](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path) if there's any need to support older browsers, than the implementation might need to change

fix: update new issue icon

---

backend/kernelCI_app/typeModels/issueDetails.py
backend/kernelCI_app/views/issueDetailsBuildsView.py
backend/kernelCI_app/views/issueDetailsTestsView.py
backend/kernelCI_app/views/issueDetailsView.py
backend/schema.yml
dashboard/src/components/Badge/BranchBadge.tsx
dashboard/src/components/Cards/IssuesList.tsx
dashboard/src/components/IssueDetails/IssueDetails.tsx
dashboard/src/components/Section/Section.tsx
dashboard/src/components/Section/SectionGroup.tsx

- Updated issue details view
- Created the BranchBadge component
- Added subtitle to the Section component
- Added tags in the issue details page as a subtitle to the general section
Other extra data is already present in the 'First Incident Data' or indirectly in the Builds/Tests tables
Closes #915
http://localhost:5173/issue/maestro%3Ada694c56147298d223ee432ad8d6a8ee311b773a?iv=1&ls=10&p=bt&ti%7Cc=v6.14-rc3-27-gb92c76cc17f9&ti%7Cch=b92c76cc17f9780732ed9a145f4e24fc4439bd11&ti%7Cgb=for-next&ti%7Cgu=https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Fbroonie%2Fspi.git&ti%7Ct=broonie-spi

feat(issue-details): add remaining extra data

---

dashboard/src/components/TreeListingPage/TreeTable.tsx

Close #939
[Before](https://staging.dashboard.kernelci.org:9000/tree)
[After](http://localhost:5173/tree)

feat: show relative date in tree listing

---

backend/kernelCI_app/unitTests/buildDetails_test.py
backend/kernelCI_app/unitTests/issues_test.py
backend/kernelCI_app/unitTests/testDetails_test.py
backend/kernelCI_app/unitTests/utils/asserts.py
backend/kernelCI_app/unitTests/utils/baseClient.py
backend/kernelCI_app/unitTests/utils/fields/builds.py
backend/kernelCI_app/unitTests/utils/fields/issues.py
backend/kernelCI_app/unitTests/utils/fields/tests.py
backend/kernelCI_app/unitTests/utils/issueClient.py
backend/kernelCI_app/unitTests/utils/testClient.py

- refactor default tests asserts
- create test details tests
- create issue view, issue details, issue test, issue build tests
Close #973, #974

Test: test details and issues endpoints

---

dashboard/package.json
dashboard/pnpm-lock.yaml
dashboard/src/components/Cards/IssuesList.tsx
dashboard/src/components/Issue/IssueSection.tsx
dashboard/src/hooks/store/useSearchStore.tsx
dashboard/src/main.tsx
dashboard/src/pages/HardwareBuildDetails/HardwareBuildDetails.tsx
dashboard/src/pages/HardwareTestDetails/HardwareTestDetails.tsx
dashboard/src/pages/IssueDetails/IssueDetails.tsx
dashboard/src/pages/TreeBuildDetails/TreeBuildDetails.tsx
dashboard/src/pages/TreeDetails/Tabs/Boots/BootsTab.tsx
dashboard/src/pages/TreeDetails/Tabs/Build/TreeDetailsBuildsTable.tsx
dashboard/src/pages/TreeDetails/Tabs/Tests/TestsTab.tsx
dashboard/src/pages/TreeDetails/TreeDetails.tsx
dashboard/src/pages/TreeTestDetails/TreeTestDetails.tsx
dashboard/src/pages/hardwareDetails/HardwareDetails.tsx
dashboard/src/pages/hardwareDetails/Tabs/Boots/BootsTab.tsx
dashboard/src/pages/hardwareDetails/Tabs/Build/HardwareDetailsBuildsTable.tsx
dashboard/src/pages/hardwareDetails/Tabs/HardwareCommitNavigationGraph.tsx
dashboard/src/pages/hardwareDetails/Tabs/Tests/HardwareDetailsTestsTable.tsx
dashboard/src/routes/_main/build/$buildId/route.tsx
dashboard/src/routes/_main/hardware/$hardwareId/index.tsx
dashboard/src/routes/_main/hardware/$hardwareId/route.tsx
dashboard/src/routes/_main/issue/$issueId/route.tsx
dashboard/src/routes/_main/test/$testId/route.tsx

Closes #1008 
- Try to enter a issue/build/test details and check that no unnecessary search parameter is in the URL
- Try to go back to the tree/hardware page using the breadcrumb and check that the previous parameters are there

Feat: pass search params by state

---

backend/kernelCI_app/unitTests/hardware_test.py
backend/kernelCI_app/unitTests/utils/hardwareClient.py
backend/kernelCI_app/views/hardwareDetailsBootsView.py
backend/kernelCI_app/views/hardwareDetailsBuildsView.py
backend/kernelCI_app/views/hardwareDetailsTestsView.py

Create tests to the endpoints:
- Hardware Details Boots View
- Hardware Details Builds View
- Hardware Details Tests View

Test: hardware details tab views

---

dashboard/public/robots.txt

Chore: add robots.txt config

---

README.md
backend/.gitignore
backend/kernelCI_app/management/commands/data/recipients.yaml
backend/kernelCI_app/management/commands/data/summary-signup.yaml
backend/kernelCI_app/management/commands/libs/email.py
backend/kernelCI_app/management/commands/libs/kcidb.py
backend/kernelCI_app/management/commands/notifications.py
backend/kernelCI_app/management/commands/templates/base.txt
backend/kernelCI_app/management/commands/templates/issue_boot.txt.j2
backend/kernelCI_app/management/commands/templates/issue_build.txt.j2
backend/kernelCI_app/management/commands/templates/issues.txt.j2
backend/kernelCI_app/management/commands/templates/summary.txt.j2
backend/poetry.lock
backend/pyproject.toml
backend/scripts/look-for-issues.sh
backend/scripts/send-summary-emails.sh
docs/notifications.md

We will be reusing and sharing infra with the dashboard, so from now on notifications lives inside the dashboard.
This commit bring most of the code as is. Then with time we will improve it to share infra with the dashboard.

Bring notifications tooling into the dashboard

---

backend/kernelCI_app/management/commands/libs/kcidb.py
backend/kernelCI_app/management/commands/notifications.py
backend/poetry.lock
backend/pyproject.toml
backend/scripts/send-summary-emails.sh

A round of notifications improvements. Contains two bug fixes and the transition to use the Django DB conn instead of creating our own.

Notifications improvements

---

backend/kernelCI_app/unitTests/hardwareDetails_test.py
backend/kernelCI_app/unitTests/hardware_test.py
backend/kernelCI_app/unitTests/utils/client/hardwareClient.py
backend/kernelCI_app/unitTests/utils/fields/hardware.py

Added test for hardware listing
Closes #981
Make sure to run `poetry run pytest --run-all` to check that it's working properly

test: hardware listing

---

backend/kernelCI_app/management/commands/data/summary-signup.yaml
backend/kernelCI_app/management/commands/libs/kcidb.py
backend/kernelCI_app/management/commands/notifications.py
backend/kernelCI_app/management/commands/templates/issue_boot.txt.j2
backend/kernelCI_app/management/commands/templates/issue_build.txt.j2
backend/kernelCI_app/management/commands/templates/issues.txt.j2
backend/scripts/look-for-issues.sh

Still making PRs with a bunch of changes together to make faster progress on the transition to use the notifications infra in the dashboard. I plan to reduce the intensity in the coming days.
In this PR:
- Open notifications for more origins
- Optimize some queries
- bug fixes and misc

Another round of notifications improvements

---

backend/kernelCI_app/unitTests/treeCommitHistory_test.py
backend/kernelCI_app/unitTests/utils/client/treeClient.py
backend/kernelCI_app/unitTests/utils/commonTreeAsserts.py
backend/kernelCI_app/unitTests/utils/fields/tree.py

test: tree commit history

---

backend/kernelCI_app/unitTests/hardwareDetailsSummary_test.py
backend/kernelCI_app/unitTests/utils/client/hardwareClient.py
backend/kernelCI_app/unitTests/utils/fields/hardware.py
backend/kernelCI_app/views/hardwareDetailsSummaryView.py

test: hardware details summary

---

backend/kernelCI_app/unitTests/treeDetailsBuilds_test.py
backend/kernelCI_app/unitTests/treeDetailsFull_test.py
backend/kernelCI_app/unitTests/utils/asserts.py
backend/kernelCI_app/unitTests/utils/client/treeClient.py
backend/kernelCI_app/unitTests/utils/fields/tree.py
backend/kernelCI_app/unitTests/utils/treeDetailsCommonTestCases.py

- Tree Details Full
- Tree Details Builds
Close #982
Close #986

Test: add tree details routes tests

---

backend/kernelCI_app/unitTests/hardwareDetailsFull_test.py
backend/kernelCI_app/unitTests/hardwareDetails_test.py
backend/kernelCI_app/unitTests/utils/client/hardwareClient.py
backend/kernelCI_app/unitTests/utils/hardwareDetailsCommonTestCases.py
backend/kernelCI_app/views/hardwareDetailsView.py

Test: add test to hardware details full view

---

backend/kernelCI_app/management/commands/libs/kcidb.py

We should be selecting distinct id and look at data ordered by start time.

notifications: fix test status query

---

dashboard/src/pages/hardwareDetails/HardwareDetailsFilter.tsx

Fix: change build valid to status in hd filter modal

---

backend/kernelCI/settings.py
backend/kernelCI_app/constants/general.py
backend/kernelCI_app/helpers/system.py
backend/kernelCI_app/management/commands/libs/kcidb.py
backend/kernelCI_app/management/commands/notifications.py

Deploy the notifications to crontab. The current code has:
`if not is_production_instance():`
so we will be testing them in staging first and then we drop the `not` for production deploy.

Add notifications cron job

---

dashboard/src/components/Tooltip/TruncatedValueTooltip.tsx
dashboard/src/utils/misc.tsx

Closes #1067
Check these pages and other issue pages compared to staging:
- [localhost](http://localhost:5173/issue/maestro%3A3c454cb7e135c716fffa54104baec141989af234)  -- [staging](https://staging.dashboard.kernelci.org:9000/issue/maestro%3A3c454cb7e135c716fffa54104baec141989af234)
- [localhost](http://localhost:5173/issue/maestro%3A160e6c6fbe05a163b029f4e942a1d5b78d55fe65) -- [staging](https://staging.dashboard.kernelci.org:9000/issue/maestro%3A160e6c6fbe05a163b029f4e942a1d5b78d55fe65)

fix: update truncate logic for objects in misc

---

dashboard/src/api/buildDetails.ts
dashboard/src/api/testDetails.ts
dashboard/src/components/BootsTable/BootsTable.tsx
dashboard/src/components/Breadcrumb/BreadcrumbGenerator.tsx
dashboard/src/components/BuildDetails/BuildDetails.tsx
dashboard/src/components/BuildsTable/BuildsTable.tsx
dashboard/src/components/Button/ButtonOpenLogSheet.tsx
dashboard/src/components/Filter/CodeBlock.tsx
dashboard/src/components/Icons/SearchIcon.tsx
dashboard/src/components/Log/LogViewerCard.tsx
dashboard/src/components/Sheet/LogOrJsonSheetContent.tsx
dashboard/src/components/TestDetails/TestDetails.tsx
dashboard/src/components/TestsTable/IndividualTestsTable.tsx
dashboard/src/hooks/useLogData.ts
dashboard/src/locales/messages/index.ts
dashboard/src/pages/LogViewer.tsx
dashboard/src/pages/TreeDetails/Tabs/WrapperTableWithLogSheet.tsx
dashboard/src/routes/log-viewer.tsx

feat: log-viewer- improvements

---

dashboard/src/pages/TreeDetails/TreeDetails.tsx
dashboard/src/pages/hardwareDetails/HardwareDetails.tsx

Closes #1090
- Enter a tree details with the network tab of inspect open
- Filter for anything in the page and check that it's doing only one request instead of many

fix: verify cache before making a new request

---

dashboard/src/api/issueDetails.ts
dashboard/src/api/treeDetails.ts
dashboard/src/main.tsx
dashboard/src/types/general.ts
dashboard/src/utils/query.ts

Creates a custom function to handle any retries, checking if they sent a status 200 and only disallowing retry if so
Closes #1108
- Check that any "200 error" does not retry
- Check that any other situation (actual errors) has retries

fix: disable retry if status is 200

---

backend/kernelCI_app/management/commands/data/recipients.yaml
backend/kernelCI_app/management/commands/data/summary-signup.yaml

Add more trees notification

---

backend/kernelCI_app/queries/tree.py

Changes the tree listing fast query to avoid direct use of variable in the query and therefore avoid sql injection
- Replaces direct passing of variable to the tree listing fast query with a named parameter.
- Small refactor on a constant variable for selected checkouts clause
Make a request for tree listing fast, and try to pass an origin with apostrophes or quotes in it. It should return status 200 with 0 results instead of the error 500 on staging.
Closes #1229

Fix: Tree fast query variable

---

backend/kernelCI_app/queries/tree.py

This PR updates the TreeDetails endpoint to support resolving trees not only by commit hash but also by commit tag.
Previously, the URL structure required a commit hash to identify the tree. With this change, it is now possible to access the same endpoint using a tag name, improving flexibility and usability for users who rely on tags.
No conflict resolution logic between hashes and tags was introduced since they are very different from each other (I've queried in the database to confirm this).
There are cases where the checkout constraints in KCIDB yield multiple matches. In such scenarios, the data returned is based on the latest associated checkout.
1. Use the TreeDetails page with a known commit hash. It should behave as before. e.g. …

feat(treedetails): allow lookup by commit tag or hash

---

backend/data/notifications/subscriptions/next.yaml
backend/data/notifications/subscriptions/stable.yaml
backend/kernelCI/settings.py

Update next and stable-rc report generation for maestro and microsoft and also update default email for microsoft.

Update notifications reports and recipients

---

CONTRIBUTING.md

Created CONTRIBUTING.md with instructions for reporting bugs, submitting
patches, and following development workflow. Includes links to resources,
commit message conventions, and automated code checks.
To provide clear guidelines for contributors on how to report issues,
submit patches, and follow the development workflow. This will help maintain
a consistent and efficient contribution process.
Closes #1293

docs: add CONTRIBUTING guide for new contributors

---

backend/README.md

Update the backend README to include instructions for psycopg errors, and how to select the correct interpreter.

chore: update backend README

---

.github/workflows/deploy-production.yaml

It is better we get notified in discord about deploy, for records and diagnostics.

Create discord notification

---

backend/kernelCI_app/helpers/email.py
backend/kernelCI_app/helpers/hardwareDetails.py
backend/kernelCI_app/helpers/misc.py
backend/kernelCI_app/helpers/treeDetails.py
backend/kernelCI_app/tests/unitTests/helpers/commonDetails_helpers_test.py
backend/kernelCI_app/tests/unitTests/helpers/database_test.py
backend/kernelCI_app/tests/unitTests/helpers/discordWebhook_test.py
backend/kernelCI_app/tests/unitTests/helpers/email_test.py
backend/kernelCI_app/tests/unitTests/helpers/errorHandling_test.py
backend/kernelCI_app/tests/unitTests/helpers/logger_test.py
backend/kernelCI_app/tests/unitTests/helpers/misc_test.py
backend/kernelCI_app/tests/unitTests/helpers/system_test.py
backend/kernelCI_app/views/treeCommitsHistory.py

**Increase to 47**
100% coverage for
- commonDetails
- database
- discordWebhook
- email
- errorHandling
- logger
- misc
- system
part of #1496

test: add unit tests for remaining helpers

---

backend/kernelCI_app/tests/unitTests/helpers/detailsIssues_test.py
backend/kernelCI_app/tests/unitTests/helpers/fixtures/issue_data.py
backend/kernelCI_app/tests/unitTests/helpers/issueExtras_test.py
backend/kernelCI_app/tests/unitTests/helpers/issueListing_test.py

**Increase to 47%**
100% coverage for
- detailsIssues
- issueExtras
- issueListing
- part of #1496

test: add unit tests for issues helpers
